-- Smartsell Management — schéma initial Supabase
create extension if not exists "pgcrypto";

do $$ begin create type public.app_role as enum ('SUPER_ADMIN','ADMIN','MANAGER','CHEF_DE_PROJET','COMMERCIAL','COMMUNITY_MANAGER','GRAPHISTE','VIDEASTE','PHOTOGRAPHE','DEVELOPPEUR','COMPTABLE','COLLABORATEUR'); exception when duplicate_object then null; end $$;
do $$ begin create type public.record_status as enum ('DRAFT','ACTIVE','PAUSED','DONE','CANCELLED','ARCHIVED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.communication_status as enum ('DRAFT','QUEUED','SENT','DELIVERED','FAILED','BOUNCED'); exception when duplicate_object then null; end $$;

create table if not exists public.departments (id uuid primary key default gen_random_uuid(), name text not null unique, created_at timestamptz not null default now());
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '', role public.app_role not null default 'COLLABORATEUR', roles public.app_role[] not null default array['COLLABORATEUR']::public.app_role[], department_id uuid references public.departments(id),
  avatar_url text, phone text, active boolean not null default true, must_change_password boolean not null default true,
  notification_preferences jsonb not null default '{"IN_APP":true,"EMAIL":true,"SMS":false}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.app_settings (id uuid primary key default gen_random_uuid(), key text not null unique, value jsonb not null, updated_by uuid references public.profiles(id), updated_at timestamptz not null default now());
create table if not exists public.company_profile (
  id uuid primary key default gen_random_uuid(), company_name text not null default 'Smartsell', logo_light text, logo_dark text,
  primary_color text default '#6A2B85', secondary_color text default '#0A0A0D', accent_color text default '#FAEE35',
  phone text, whatsapp text, email text, address text, website text, social_links jsonb not null default '{}'::jsonb,
  currency text not null default 'GNF' check (currency in ('GNF','EUR','USD')), invoice_prefix text default 'FAC', quote_prefix text default 'DEV', payment_terms text, updated_at timestamptz not null default now()
);
insert into public.company_profile(company_name,phone,whatsapp,email,address) select 'Smartsell','620 619 064','620 619 064','contact@smartsell.pro','Soloprimo, Conakry' where not exists(select 1 from public.company_profile);

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(), name text not null, legal_name text, sector text, address text, phone text, whatsapp text, email text, website text, tax_id text,
  account_manager_id uuid references public.profiles(id), status public.record_status not null default 'ACTIVE', notes text, started_on date, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.client_contacts (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id) on delete cascade, full_name text not null, role text, phone text, whatsapp text, email text, is_primary boolean default false, sms_opt_in boolean default false, email_opt_in boolean default true, marketing_opt_in boolean default false, opted_out_at timestamptz);
create table if not exists public.prospects (
  id uuid primary key default gen_random_uuid(), company text not null, contact_name text, phone text, whatsapp text, email text, sector text, source text, need text, estimated_budget numeric(16,2), currency text default 'GNF', owner_id uuid references public.profiles(id), stage text not null default 'NOUVEAU', last_contact_at timestamptz, next_follow_up_at timestamptz, notes text, sms_opt_in boolean default false, email_opt_in boolean default true, marketing_opt_in boolean default false, opted_out_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.prospect_activities (id uuid primary key default gen_random_uuid(), prospect_id uuid not null references public.prospects(id) on delete cascade, kind text not null, content text, author_id uuid references public.profiles(id), created_at timestamptz not null default now());
create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(), client_id uuid references public.clients(id), name text not null, type text, manager_id uuid references public.profiles(id), starts_on date, ends_on date, budget numeric(16,2) default 0, currency text default 'GNF', status text not null default 'PLANIFIE', priority text default 'NORMALE', progress smallint default 0 check(progress between 0 and 100), description text, created_at timestamptz not null default now()
);
create table if not exists public.project_members (project_id uuid references public.projects(id) on delete cascade, profile_id uuid references public.profiles(id) on delete cascade, role text, primary key(project_id,profile_id));
create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id) on delete cascade, title text not null, description text, assignee_id uuid references public.profiles(id), creator_id uuid references public.profiles(id), status text not null default 'A_FAIRE', priority text default 'NORMALE', due_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.task_comments (id uuid primary key default gen_random_uuid(), task_id uuid not null references public.tasks(id) on delete cascade, author_id uuid references public.profiles(id), body text not null, created_at timestamptz not null default now());
create table if not exists public.shoots (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id), client_id uuid references public.clients(id), kind text not null check(kind in ('TOURNAGE','SHOOTING')), title text not null, location text, starts_at timestamptz not null, ends_at timestamptz, status text default 'PREPARATION', call_sheet jsonb default '{}'::jsonb);
create table if not exists public.shoot_members (shoot_id uuid references public.shoots(id) on delete cascade, profile_id uuid references public.profiles(id), role text, primary key(shoot_id,profile_id));
create table if not exists public.editorial_items (id uuid primary key default gen_random_uuid(), client_id uuid references public.clients(id), project_id uuid references public.projects(id), title text not null, platform text, content_type text, caption text, publish_at timestamptz, status text not null default 'A_REDIGER', assignee_id uuid references public.profiles(id), created_at timestamptz default now());
create table if not exists public.editorial_comments (id uuid primary key default gen_random_uuid(), item_id uuid not null references public.editorial_items(id) on delete cascade, author_name text, body text not null, is_client boolean default false, created_at timestamptz default now());

create table if not exists public.quotes (id uuid primary key default gen_random_uuid(), number text not null unique, client_id uuid not null references public.clients(id), project_id uuid references public.projects(id), issue_date date not null default current_date, valid_until date, status text not null default 'BROUILLON', currency text default 'GNF', discount numeric(16,2) default 0, tax numeric(16,2) default 0, total numeric(16,2) default 0, created_at timestamptz default now());
create table if not exists public.quote_items (id uuid primary key default gen_random_uuid(), quote_id uuid not null references public.quotes(id) on delete cascade, description text not null, quantity numeric(12,2) default 1, unit_price numeric(16,2) not null, tax_rate numeric(5,2) default 0, sort_order int default 0);
create table if not exists public.invoices (id uuid primary key default gen_random_uuid(), number text not null unique, client_id uuid not null references public.clients(id), project_id uuid references public.projects(id), quote_id uuid references public.quotes(id), issue_date date not null default current_date, due_date date, status text not null default 'BROUILLON', currency text default 'GNF', discount numeric(16,2) default 0, tax numeric(16,2) default 0, total numeric(16,2) default 0, created_at timestamptz default now());
create table if not exists public.invoice_items (id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.invoices(id) on delete cascade, description text not null, quantity numeric(12,2) default 1, unit_price numeric(16,2) not null, tax_rate numeric(5,2) default 0, sort_order int default 0);
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), invoice_id uuid not null references public.invoices(id), amount numeric(16,2) not null check(amount>0), currency text default 'GNF', paid_at timestamptz not null default now(), method text, reference text, recorded_by uuid references public.profiles(id));
create table if not exists public.expenses (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id), category text, description text not null, amount numeric(16,2) not null check(amount>=0), currency text default 'GNF', spent_on date default current_date, status text default 'BROUILLON', submitted_by uuid references public.profiles(id), approved_by uuid references public.profiles(id), receipt_url text, created_at timestamptz default now());

create table if not exists public.equipment (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, category text, serial_number text, purchase_date date, purchase_price numeric(16,2), status text not null default 'DISPONIBLE', condition text, photo_url text, notes text);
create table if not exists public.equipment_bookings (id uuid primary key default gen_random_uuid(), equipment_id uuid not null references public.equipment(id), project_id uuid references public.projects(id), shoot_id uuid references public.shoots(id), starts_at timestamptz not null, ends_at timestamptz not null, booked_by uuid references public.profiles(id), status text default 'RESERVE', check(ends_at>starts_at));
create table if not exists public.equipment_movements (id uuid primary key default gen_random_uuid(), equipment_id uuid not null references public.equipment(id), booking_id uuid references public.equipment_bookings(id), movement_type text not null check(movement_type in ('SORTIE','RETOUR')), moved_at timestamptz default now(), handled_by uuid references public.profiles(id), condition_notes text);
create table if not exists public.purchase_requests (id uuid primary key default gen_random_uuid(), title text not null, justification text, estimated_cost numeric(16,2), currency text default 'GNF', priority text default 'NORMALE', status text default 'PROPOSE', requested_by uuid references public.profiles(id), approved_by uuid references public.profiles(id), created_at timestamptz default now());
create table if not exists public.contracts (id uuid primary key default gen_random_uuid(), client_id uuid references public.clients(id), project_id uuid references public.projects(id), title text not null, status text default 'BROUILLON', starts_on date, ends_on date, file_url text, created_at timestamptz default now());
create table if not exists public.documents (id uuid primary key default gen_random_uuid(), client_id uuid references public.clients(id), project_id uuid references public.projects(id), title text not null, category text, file_url text not null, uploaded_by uuid references public.profiles(id), created_at timestamptz default now());
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), profile_id uuid not null references public.profiles(id) on delete cascade, channel text not null default 'IN_APP', title text not null, body text, read_at timestamptz, entity_type text, entity_id uuid, created_at timestamptz default now());
create table if not exists public.activity_logs (id bigint generated always as identity primary key, actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.user_sessions (id uuid primary key default gen_random_uuid(), profile_id uuid not null references public.profiles(id) on delete cascade, signed_in_at timestamptz not null default now(), last_seen_at timestamptz not null default now(), signed_out_at timestamptz, active_seconds int not null default 0 check(active_seconds>=0), pages_viewed int not null default 0 check(pages_viewed>=0), ip_hash text, user_agent text);
create table if not exists public.monitoring_preferences (profile_id uuid primary key references public.profiles(id) on delete cascade, notify_long_session_minutes int default 600, notify_outside_hours boolean default false, notify_sensitive_actions boolean default true, daily_summary boolean default true, updated_at timestamptz default now());

create table if not exists public.communication_providers (id uuid primary key default gen_random_uuid(), channel text not null check(channel in ('SMS','EMAIL')), provider text not null, public_config jsonb default '{}'::jsonb, active boolean default false, test_mode boolean default true, updated_at timestamptz default now());
create table if not exists public.user_access_controls (profile_id uuid primary key references public.profiles(id) on delete cascade, allowed_modules text[] not null default '{}', denied_permissions text[] not null default '{}', can_initiate_calls boolean default false, max_sms_per_day int not null default 0 check(max_sms_per_day>=0), max_emails_per_day int not null default 10 check(max_emails_per_day>=0), max_calls_per_day int not null default 0 check(max_calls_per_day>=0), max_export_rows int not null default 100 check(max_export_rows>=0), max_approval_amount numeric(16,2) not null default 0 check(max_approval_amount>=0), updated_by uuid references public.profiles(id), updated_at timestamptz default now());
create table if not exists public.call_logs (id uuid primary key default gen_random_uuid(), contact_type text, contact_id uuid, phone text not null, provider text, provider_call_id text, status text not null default 'QUEUED', duration_seconds int, cost numeric(12,4), currency text, consent_confirmed boolean not null default false, initiated_by uuid not null references public.profiles(id), created_at timestamptz default now(), ended_at timestamptz);
create table if not exists public.communication_templates (id uuid primary key default gen_random_uuid(), channel text not null, name text not null, subject text, body text not null, variables text[] default '{}', created_at timestamptz default now());
create table if not exists public.campaigns (id uuid primary key default gen_random_uuid(), name text not null, channel text not null, template_id uuid references public.communication_templates(id), status public.communication_status default 'DRAFT', scheduled_at timestamptz, recipient_count int default 0, created_by uuid references public.profiles(id), created_at timestamptz default now());
create table if not exists public.campaign_recipients (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references public.campaigns(id) on delete cascade, contact_type text, contact_id uuid, address text not null, status public.communication_status default 'QUEUED', provider_message_id text, error text);
create table if not exists public.communication_jobs (id uuid primary key default gen_random_uuid(), campaign_id uuid references public.campaigns(id) on delete cascade, status public.communication_status default 'QUEUED', processed_count int default 0, total_count int default 0, last_error text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.communication_logs (id bigint generated always as identity primary key, channel text not null, recipient text not null, template_id uuid references public.communication_templates(id), campaign_id uuid references public.campaigns(id), status public.communication_status not null, provider_message_id text, sms_cost numeric(12,4), sms_currency text, sent_by uuid references public.profiles(id), sent_at timestamptz default now(), metadata jsonb default '{}'::jsonb);
create table if not exists public.client_notification_preferences (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id) on delete cascade, in_app boolean default true, sms boolean default false, email boolean default true, unique(client_id));
create table if not exists public.publication_notifications (id uuid primary key default gen_random_uuid(), editorial_item_id uuid not null references public.editorial_items(id) on delete cascade, channel text not null, communication_log_id bigint references public.communication_logs(id), created_at timestamptz default now());

create index if not exists idx_projects_client on public.projects(client_id);
create index if not exists idx_tasks_project on public.tasks(project_id);
create index if not exists idx_tasks_assignee on public.tasks(assignee_id,due_at);
create index if not exists idx_invoices_client on public.invoices(client_id,status);
create index if not exists idx_editorial_client_publish on public.editorial_items(client_id,publish_at);
create index if not exists idx_equipment_bookings_dates on public.equipment_bookings(equipment_id,starts_at,ends_at);
create index if not exists idx_notifications_profile on public.notifications(profile_id,read_at,created_at desc);

create or replace function public.has_role(required_role public.app_role) returns boolean language sql stable security definer set search_path=public as $$ select coalesce(required_role = any(roles), role = required_role, false) from public.profiles where id=auth.uid() $$;
create or replace function public.current_role() returns public.app_role language sql stable security definer set search_path=public as $$ select coalesce((select candidate from unnest(array['SUPER_ADMIN','ADMIN','MANAGER','CHEF_DE_PROJET','COMMERCIAL','COMMUNITY_MANAGER','COMPTABLE','DEVELOPPEUR','GRAPHISTE','VIDEASTE','PHOTOGRAPHE','COLLABORATEUR']::public.app_role[]) candidate where candidate = any(coalesce(roles,array[role])) limit 1), role) from public.profiles where id=auth.uid() $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.has_role('SUPER_ADMIN') or public.has_role('ADMIN'),false) $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,roles) values(new.id,coalesce(new.raw_user_meta_data->>'name',''),array['COLLABORATEUR']::public.app_role[]) on conflict(id) do nothing; return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

do $$ declare t text; begin foreach t in array array['profiles','departments','app_settings','company_profile','clients','client_contacts','prospects','prospect_activities','projects','project_members','tasks','task_comments','shoots','shoot_members','editorial_items','editorial_comments','quotes','quote_items','invoices','invoice_items','payments','expenses','equipment','equipment_bookings','equipment_movements','purchase_requests','contracts','documents','notifications','activity_logs','user_sessions','monitoring_preferences','communication_providers','communication_templates','campaigns','campaign_recipients','communication_jobs','communication_logs','client_notification_preferences','publication_notifications','user_access_controls','call_logs'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;

-- Les utilisateurs authentifiés voient les données métier; les écritures restent contrôlées par rôle.
do $$ declare t text; begin foreach t in array array['departments','clients','client_contacts','prospects','prospect_activities','projects','project_members','tasks','task_comments','shoots','shoot_members','editorial_items','editorial_comments','quotes','quote_items','invoices','invoice_items','payments','expenses','equipment','equipment_bookings','equipment_movements','purchase_requests','contracts','documents','notifications','activity_logs','communication_templates','campaigns','campaign_recipients','communication_jobs','communication_logs','client_notification_preferences','publication_notifications'] loop
  execute format('drop policy if exists authenticated_read on public.%I',t);
  execute format('create policy authenticated_read on public.%I for select to authenticated using (true)',t);
  execute format('drop policy if exists authenticated_write on public.%I',t);
  execute format('create policy authenticated_write on public.%I for all to authenticated using (public.current_role() <> ''COLLABORATEUR'') with check (public.current_role() <> ''COLLABORATEUR'')',t);
end loop; end $$;
drop policy if exists access_admin on public.user_access_controls; create policy access_admin on public.user_access_controls for all to authenticated using(public.is_admin() or profile_id=auth.uid()) with check(public.is_admin());
drop policy if exists call_logs_owner on public.call_logs; create policy call_logs_owner on public.call_logs for select to authenticated using(initiated_by=auth.uid() or public.is_admin());
drop policy if exists call_logs_insert on public.call_logs; create policy call_logs_insert on public.call_logs for insert to authenticated with check(initiated_by=auth.uid());
drop policy if exists sessions_owner on public.user_sessions; create policy sessions_owner on public.user_sessions for select to authenticated using(profile_id=auth.uid() or public.is_admin());
drop policy if exists sessions_write on public.user_sessions; create policy sessions_write on public.user_sessions for all to authenticated using(profile_id=auth.uid() or public.is_admin()) with check(profile_id=auth.uid() or public.is_admin());
drop policy if exists monitoring_admin on public.monitoring_preferences; create policy monitoring_admin on public.monitoring_preferences for all to authenticated using(profile_id=auth.uid() and public.current_role()='SUPER_ADMIN') with check(profile_id=auth.uid() and public.current_role()='SUPER_ADMIN');
drop policy if exists own_profile on public.profiles; create policy own_profile on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
drop policy if exists admin_profiles on public.profiles; create policy admin_profiles on public.profiles for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists own_notifications on public.notifications; create policy own_notifications on public.notifications for all to authenticated using(profile_id=auth.uid() or public.is_admin()) with check(profile_id=auth.uid() or public.is_admin());
drop policy if exists settings_admin on public.app_settings; create policy settings_admin on public.app_settings for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists authenticated_read on public.activity_logs; drop policy if exists authenticated_write on public.activity_logs;
drop policy if exists audit_admin on public.activity_logs; create policy audit_admin on public.activity_logs for select to authenticated using(public.is_admin());
drop policy if exists audit_self_insert on public.activity_logs; create policy audit_self_insert on public.activity_logs for insert to authenticated with check(actor_id=auth.uid());
drop policy if exists company_authenticated on public.company_profile; create policy company_authenticated on public.company_profile for select to authenticated using(true);
drop policy if exists company_admin on public.company_profile; create policy company_admin on public.company_profile for all to authenticated using(public.is_admin()) with check(public.is_admin());

insert into storage.buckets(id,name,public) values
('avatars','avatars',false),('client-files','client-files',false),('project-files','project-files',false),('editorial-assets','editorial-assets',false),('expense-receipts','expense-receipts',false),('equipment-photos','equipment-photos',false),('contracts','contracts',false),('payments','payments',false)
on conflict(id) do nothing;
drop policy if exists authenticated_storage_read on storage.objects; create policy authenticated_storage_read on storage.objects for select to authenticated using(true);
drop policy if exists authenticated_storage_write on storage.objects; create policy authenticated_storage_write on storage.objects for all to authenticated using(public.current_role()<>'COLLABORATEUR') with check(public.current_role()<>'COLLABORATEUR');
