import { supabase } from './supabase'
import type { AccessControl, ActivityLog, AgencyBriefing, AgencyScenario, AutopilotAction, AutopilotRun, AutopilotSettings, CalendarConnection, CallList, CallListContact, CallLog, Campaign, CampaignAiDraft, Client, ClientPortalMessage, ClientPortalWorkspace, CommercialDocument, CommercialRadar, CompanySettings, ContactGroup, CommunicationTemplate, CreativeApproval, DigitalTwinSnapshot, EditorialItem, EmployeeRecord, Equipment, EquipmentCategory, EquipmentMovement, Expense, Invoice, InvoiceItem, LeaveRequest, NextBestAction, Notification, Payment, PortalAccess, Profile, Project, Prospect, Quote, Service, SocialIntegration, Supplier, SupportMessage, SupportTicket, Task, TeamChatMessage, UserSession } from '../types/models'

const db=()=>{if(!supabase)throw new Error('Supabase n’est pas configuré.');return supabase}
const fail=(error:{message:string}|null)=>{if(error)throw new Error(error.message)}
const queryCache=new Map<string,{until:number,value:unknown}>()
async function cached<T>(key:string,loader:()=>Promise<T>,ttl=45_000):Promise<T>{const hit=queryCache.get(key);if(hit&&hit.until>Date.now())return hit.value as T;const pending=loader();queryCache.set(key,{until:Date.now()+ttl,value:pending});try{const value=await pending;queryCache.set(key,{until:Date.now()+ttl,value});return value}catch(error){queryCache.delete(key);throw error}}
const invalidate=(...keys:string[])=>keys.forEach(key=>queryCache.delete(key))
async function invokeEdge<T>(name:string,body?:Record<string,unknown>,retryNetwork=false):Promise<T>{
  const client=db();
  for(let attempt=0;attempt<(retryNetwork?2:1);attempt+=1){
    const {data,error}=await client.functions.invoke(name,{body});
    if(!error)return data as T;
    let message=error.message;
    const context=(error as {context?:Response}).context;
    if(context)try{const detail=await context.clone().json() as {error?:string};message=detail.error||message}catch{/* réponse non JSON */}
    const transient=!context&&/failed to send|fetch|network|connexion/i.test(message);
    if(!transient||attempt===1)throw new Error(transient?'Connexion instable : impossible de joindre le briefing. Réessayez dans quelques secondes.':message);
  }
  throw new Error('Briefing indisponible');
}

export async function signIn(email:string,password:string){
  const client=db();
  const {data,error}=await client.auth.signInWithPassword({email,password});
  if(error){
    const message=error.message.toLowerCase();
    if(message.includes('email not confirmed')) throw new Error('Adresse e-mail non confirmée. Demandez un nouveau lien de confirmation.');
    if(message.includes('invalid login credentials')) throw new Error('E-mail ou mot de passe incorrect. Si vous venez de vous inscrire, confirmez d’abord le lien reçu par e-mail.');
    throw new Error(error.message);
  }
  if(!data.user)return data;
  const {data:profile, error:profileError}=await client.from('profiles').select('active,access_expires_at').eq('id',data.user.id).single();
  if(profileError){await client.auth.signOut();throw new Error('Profil utilisateur introuvable.');}
  if(!profile.active){await client.auth.signOut();throw new Error('Ce compte est suspendu. Contactez le Super Admin.');}
  // An expired SaaS trial stays signed in so the workspace remains readable.
  return data;
}
export async function signUpWithPassword(input:{email:string;password:string;fullName:string;companyName:string;referralCode?:string}){
  const redirectTo=new URL(import.meta.env.BASE_URL,location.origin);redirectTo.hash='app';
  const {data,error}=await db().auth.signUp({email:input.email,password:input.password,options:{emailRedirectTo:redirectTo.href,data:{name:input.fullName,full_name:input.fullName,company_name:input.companyName,trial_hours:72,referral_code:input.referralCode||null}}});
  fail(error);return data
}
export async function resendConfirmationEmail(email:string){
  const redirectTo=new URL(import.meta.env.BASE_URL,location.origin);redirectTo.hash='app';
  const {error}=await db().auth.resend({type:'signup',email,options:{emailRedirectTo:redirectTo.href}});
  fail(error);
}
export async function startSmsSignupOtp(input:{phone:string;email:string;fullName:string;companyName:string}){
  return invokeEdge<{challenge_id:string;expires_at:string}>('signup-otp-start',{phone:input.phone,email:input.email,full_name:input.fullName,company_name:input.companyName});
}
export async function verifySmsSignupOtp(input:{challengeId:string;code:string;password:string;referralCode?:string}){
  return invokeEdge<{success:boolean;email:string}>('signup-otp-verify',{challenge_id:input.challengeId,code:input.code,password:input.password,referral_code:input.referralCode||null});
}
export async function startPasswordResetOtp(input:{email:string;phone:string}){
  return invokeEdge<{challenge_id:string;expires_at:string}>('password-reset-otp-start',{email:input.email,phone:input.phone});
}
export async function verifyPasswordResetOtp(input:{challengeId:string;code:string;password:string}){
  return invokeEdge<{success:boolean}>('password-reset-otp-verify',{challenge_id:input.challengeId,code:input.code,password:input.password});
}
export async function signInWithGoogle(){
  const redirectTo=new URL(import.meta.env.BASE_URL,location.origin);redirectTo.hash='app';
  const {data,error}=await db().auth.signInWithOAuth({provider:'google',options:{redirectTo:redirectTo.href,queryParams:{access_type:'offline',prompt:'consent'}}});
  fail(error);return data
}
export async function signOut(){const {error}=await db().auth.signOut();fail(error)}
export async function currentSession(){return (await db().auth.getSession()).data.session}
export function onAuthChange(callback:()=>void){return db().auth.onAuthStateChange(callback).data.subscription}
export async function getProfile():Promise<Profile>{
  const client=db(),{data:{user}}=await client.auth.getUser()
  if(!user)throw new Error('Session expirée')
  const {data,error}=await client.from('profiles').select('*').eq('id',user.id).single();fail(error)
  const profile=data as Profile
  if(!profile.active){await client.auth.signOut();throw new Error('Votre compte est suspendu.')}
  const code=String(user.user_metadata?.referral_code||localStorage.getItem('smartsell-referral-code')||'').toUpperCase()
  if(/^[A-F0-9]{10}$/.test(code)){
    void client.rpc('claim_referral_code',{p_code:code}).then(({error:claimError})=>{if(!claimError)localStorage.removeItem('smartsell-referral-code')})
  }
  return profile
}
export async function getReferralSummary():Promise<{code:string;signups:number;converted:number;credits_available:number;credits_redeemed:number}>{const {data,error}=await db().rpc('my_referral_summary');fail(error);return data as {code:string;signups:number;converted:number;credits_available:number;credits_redeemed:number}}
export async function getOrCreateReferralCode():Promise<string>{const {data,error}=await db().rpc('get_or_create_referral_code');fail(error);return data as string}
export async function getTenantTrialStatus(profile:Profile):Promise<{is_temporary:boolean;access_expires_at:string|null}>{const ownerId=profile.tenant_owner_id||profile.id;if(ownerId===profile.id)return {is_temporary:Boolean(profile.is_temporary),access_expires_at:profile.access_expires_at||null};const {data,error}=await db().from('profiles').select('is_temporary,access_expires_at').eq('id',ownerId).single();fail(error);if(!data)throw new Error('Espace introuvable');return {is_temporary:Boolean(data.is_temporary),access_expires_at:data.access_expires_at}}
export async function createSubscriptionRequest(input:{plan:'ESSENTIEL'|'CROISSANCE'|'ENTREPRISE';billing_period:'MONTHLY'|'ANNUAL';payment_method:'ORANGE_MONEY'|'MOBILE_MONEY';phone:string}){const {data,error}=await db().rpc('create_subscription_request',{p_plan:input.plan,p_billing_period:input.billing_period,p_payment_method:input.payment_method,p_phone:input.phone.trim()});fail(error);return data as {id:string;base_amount_gnf:number;discount_gnf:number;discount_kind:'NONE'|'FILLEUL'|'PARRAIN';amount_gnf:number}}

export async function listClients():Promise<Client[]>{return cached('clients',async()=>{const {data,error}=await db().from('clients').select('*').order('created_at',{ascending:false});fail(error);return data as Client[]})}
export async function createClient(input:Partial<Client>){const {data,error}=await db().from('clients').insert({name:input.name,legal_name:input.legal_name||null,sector:input.sector||null,phone:input.phone||null,whatsapp:input.whatsapp||null,email:input.email||null,address:input.address||null,avatar_url:input.avatar_url||null,status:'ACTIVE'}).select().single();fail(error);invalidate('clients');return data as Client}
export async function updateClient(id:string,input:Partial<Client>){const {data,error}=await db().from('clients').update(input).eq('id',id).select().single();fail(error);return data as Client}
export async function deleteClient(id:string){const {error}=await db().from('clients').delete().eq('id',id);fail(error)}
export async function getClientWorkspace(id:string){const [client,projects,tasks,invoices]=await Promise.all([db().from('clients').select('*').eq('id',id).single(),db().from('projects').select('*,clients(name),project_members(profile_id,role,profiles(full_name))').eq('client_id',id).order('created_at',{ascending:false}),db().from('tasks').select('*,projects!inner(name,client_id),profiles:assignee_id(full_name),task_assignees(profile_id,profiles(full_name))').eq('projects.client_id',id).order('created_at',{ascending:false}),db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('client_id',id).order('created_at',{ascending:false})]);fail(client.error);fail(projects.error);fail(tasks.error);fail(invoices.error);return {client:client.data as Client,projects:projects.data as Project[],tasks:tasks.data as Task[],invoices:invoices.data as Invoice[]}}
export async function listProjects():Promise<Project[]>{return cached('projects',async()=>{const {data,error}=await db().from('projects').select('*,clients(name),profiles:manager_id(full_name),project_members(profile_id,role,profiles(full_name))').order('created_at',{ascending:false});fail(error);return data as Project[]})}
async function syncProjectMembers(projectId:string,profileIds:string[]){const client=db();const unique=[...new Set(profileIds.filter(Boolean))];const {error:deleteError}=await client.from('project_members').delete().eq('project_id',projectId);fail(deleteError);if(unique.length){const {error}=await client.from('project_members').insert(unique.map((profile_id,index)=>({project_id:projectId,profile_id,role:index===0?'RESPONSABLE':'MEMBRE'})));fail(error)}}
export async function createProject(input:Partial<Project>,memberIds:string[]=[]){const primary=memberIds[0]||input.manager_id||null;const {data,error}=await db().from('projects').insert({name:input.name,client_id:input.client_id||null,manager_id:primary,type:input.type||'Autre',starts_on:input.starts_on||null,ends_on:input.ends_on||null,budget:Number(input.budget||0),currency:input.currency||'GNF',status:'PLANIFIE',priority:input.priority||'NORMALE',progress:0,description:input.description||null}).select().single();fail(error);await syncProjectMembers(data.id,memberIds.length?memberIds:primary?[primary]:[]);invalidate('projects');return data as Project}
export async function updateProject(id:string,input:Partial<Project>,memberIds?:string[]){const patch={...input,...(memberIds?{manager_id:memberIds[0]||null}:{})};const {data,error}=await db().from('projects').update(patch).eq('id',id).select().single();fail(error);if(memberIds)await syncProjectMembers(id,memberIds);invalidate('projects');return data as Project}
export async function deleteProject(id:string){const {error}=await db().from('projects').delete().eq('id',id);fail(error);invalidate('projects')}
export async function getProjectWorkspace(id:string){const [project,tasks,invoices]=await Promise.all([db().from('projects').select('*,clients(name),profiles:manager_id(full_name),project_members(profile_id,role,profiles(full_name))').eq('id',id).single(),db().from('tasks').select('*,projects(name),profiles:assignee_id(full_name),task_assignees(profile_id,profiles(full_name))').eq('project_id',id).order('created_at',{ascending:false}),db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('project_id',id).order('created_at',{ascending:false})]);fail(project.error);fail(tasks.error);fail(invoices.error);return {project:project.data as Project,tasks:tasks.data as Task[],invoices:invoices.data as Invoice[]}}
export async function listTasks():Promise<Task[]>{return cached('tasks',async()=>{const {data,error}=await db().from('tasks').select('*,projects(name,client_id),profiles:assignee_id(full_name),task_assignees(profile_id,profiles(full_name))').order('created_at',{ascending:false});fail(error);return data as Task[]})}
async function syncTaskAssignees(taskId:string,profileIds:string[]){const client=db();const unique=[...new Set(profileIds.filter(Boolean))];const {error:deleteError}=await client.from('task_assignees').delete().eq('task_id',taskId);fail(deleteError);if(unique.length){const {error}=await client.from('task_assignees').insert(unique.map(profile_id=>({task_id:taskId,profile_id})));fail(error)}}
export async function createTask(input:Partial<Task>&{reminder_minutes?:number;notification_channels?:string[]},assigneeIds:string[]=[]){const {data:{user}}=await db().auth.getUser();const channels=input.notification_channels?.length?input.notification_channels:['IN_APP','SMS'];const primary=assigneeIds[0]||input.assignee_id||null;const {data,error}=await db().from('tasks').insert({title:input.title,project_id:input.project_id||null,assignee_id:primary,description:input.description||null,status:'A_FAIRE',priority:input.priority||'NORMALE',due_at:input.due_at||null,reminder_minutes:input.reminder_minutes||30,notification_channels:channels,creator_id:user?.id}).select().single();fail(error);await syncTaskAssignees(data.id,assigneeIds.length?assigneeIds:primary?[primary]:[]);invalidate('tasks');return data as Task}
export async function updateTask(id:string,input:Partial<Task>,assigneeIds?:string[]){const patch={...input,...(assigneeIds?{assignee_id:assigneeIds[0]||null}:{}),...(input.status==='TERMINE'?{completed_at:new Date().toISOString()}:input.status?{completed_at:null}:{})};const {data,error}=await db().from('tasks').update(patch).eq('id',id).select().single();fail(error);if(assigneeIds)await syncTaskAssignees(id,assigneeIds);invalidate('tasks');return data as Task}
export async function deleteTask(id:string){const {error}=await db().from('tasks').delete().eq('id',id);fail(error);invalidate('tasks')}
export async function listInvoices():Promise<Invoice[]>{return cached('invoices',async()=>{const {data,error}=await db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').order('created_at',{ascending:false});fail(error);return data as Invoice[]})}
export async function getDocumentVerificationToken(kind:'FACTURE'|'DEVIS',documentId:string):Promise<string>{const {data,error}=await db().rpc('get_document_verification_token',{p_kind:kind,p_document_id:documentId});fail(error);if(!data)throw new Error('QR de vérification indisponible.');return data as string}
export async function isPlatformTenant():Promise<boolean>{const {data,error}=await db().rpc('is_platform_tenant');fail(error);return data===true}
export type VerifiedCommercialDocument={valid:boolean;kind?:'FACTURE'|'DEVIS';number?:string;issue_date?:string;issuer?:string}
export async function verifyCommercialDocument(token:string):Promise<VerifiedCommercialDocument>{const {data,error}=await db().rpc('verify_commercial_document',{p_token:token});fail(error);return data as VerifiedCommercialDocument}
export async function createInvoice(input:{client_id:string;project_id?:string;due_date:string;currency:string;discount:number;items:InvoiceItem[]}):Promise<Invoice>{const {data,error}=await db().rpc('create_invoice_with_items',{p_client_id:input.client_id,p_project_id:input.project_id||null,p_due_date:input.due_date,p_currency:input.currency,p_discount:input.discount,p_items:input.items});fail(error);const id=typeof data==='string'?data:(data as {id:string})?.id;if(!id)throw new Error('La création n’a renvoyé aucun numéro. Vérifiez la liste avant de réessayer.');invalidate('invoices');const {data:invoice,error:readError}=await db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('id',id).single();if(readError)throw new Error(`La facture a été créée, mais son affichage a échoué (${readError.message}). Actualisez la liste avant de réessayer pour éviter un doublon.`);return invoice as Invoice}
export async function deleteInvoice(id:string){const {error}=await db().from('invoices').delete().eq('id',id);fail(error);invalidate('invoices')}
export async function updateInvoiceStatus(id:string,status:string){const {data,error}=await db().from('invoices').update({status}).eq('id',id).select().single();fail(error);invalidate('invoices');return data as Invoice}
export async function listPayments():Promise<Payment[]>{const {data,error}=await db().from('payments').select('*,invoices(number,total,clients(name))').order('paid_at',{ascending:false});fail(error);return data as Payment[]}
export async function recordPayment(input:{invoice_id:string;amount:number;method:string;reference?:string}){const {data,error}=await db().rpc('record_invoice_payment',{p_invoice_id:input.invoice_id,p_amount:input.amount,p_method:input.method,p_reference:input.reference||null});fail(error);invalidate('invoices');return data}
export async function convertQuoteToInvoice(quoteId:string,dueDate:string):Promise<Invoice>{const {data,error}=await db().rpc('create_invoice_from_quote',{p_quote_id:quoteId,p_due_date:dueDate});fail(error);if(!data)throw new Error('Conversion sans facture créée. Vérifiez la liste avant de réessayer.');invalidate('invoices');const {data:invoice,error:readError}=await db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('id',data).single();fail(readError);return invoice as Invoice}
export async function listProfiles():Promise<Profile[]>{return cached('profiles',async()=>{let result:any=await db().from('profiles').select('id,full_name,role,roles,active,must_change_password,is_beta_tester,is_temporary,is_platform_owner,access_expires_at,department_id,phone,email,avatar_url,created_at').order('full_name');if(result.error)result=await db().from('profiles').select('id,full_name,role,roles,active,must_change_password,is_beta_tester,is_temporary,access_expires_at,department_id,phone,avatar_url,created_at').order('full_name');fail(result.error);return result.data as Profile[]})}
export type WelcomeDelivery={channel:'EMAIL'|'SMS';status:'SENT'|'SKIPPED'|'FAILED';detail?:string}
export async function createTeamMember(input:{email:string;password:string;name:string;phone?:string;roles:string[];trial_days?:number|null;notify_email?:boolean;notify_sms?:boolean}){const result=await invokeEdge<{id:string;deliveries:WelcomeDelivery[];access_expires_at?:string|null}>('create-team-member',input as unknown as Record<string,unknown>);invalidate('profiles');return result}
export async function deleteTeamMember(profileId:string){const result=await invokeEdge<{success:boolean}>('delete-team-member',{profile_id:profileId});invalidate('profiles');return result}
export async function completePasswordChange(password:string){return invokeEdge<{success:boolean}>('complete-password-change',{password})}
export async function updateProfile(id:string,input:Partial<Profile>){const {data,error}=await db().from('profiles').update(input).eq('id',id).select().single();fail(error);invalidate('profiles');return data as Profile}
export async function updateTeamMemberProfile(input:{id:string;fullName:string;phone:string|null;avatarUrl:string|null}){
  const {data,error}=await db().rpc('update_team_member_profile',{
    p_profile_id:input.id,p_full_name:input.fullName.trim(),p_phone:input.phone?.trim()||null,p_avatar_url:input.avatarUrl,
  });fail(error);invalidate('profiles');return data as Profile
}
export async function uploadProfileAvatar(profileId:string,file:File){
  if(!file.type.startsWith('image/'))throw new Error('Choisissez une image pour la photo du collaborateur.')
  if(file.size>5*1024*1024)throw new Error('La photo doit peser moins de 5 Mo.')
  const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg'
  const path=`profiles/${profileId}/${crypto.randomUUID()}.${ext}`
  const {error}=await db().storage.from('avatars').upload(path,file,{upsert:false,contentType:file.type});fail(error)
  const {data,error:signError}=await db().storage.from('avatars').createSignedUrl(path,60*60*24*365);fail(signError)
  if(!data)throw new Error('Photo indisponible')
  return data.signedUrl
}
export async function listSupportTickets():Promise<SupportTicket[]>{const {data,error}=await db().from('support_tickets').select('*').order('updated_at',{ascending:false});fail(error);return data as SupportTicket[]}
export async function listSupportMessages(ticketId:string):Promise<SupportMessage[]>{const {data,error}=await db().from('support_messages').select('*').eq('ticket_id',ticketId).order('created_at',{ascending:true});fail(error);return data as SupportMessage[]}
export async function createSupportTicket(input:{subject:string;body:string;pageUrl?:string}){const {data,error}=await db().rpc('create_support_ticket',{p_subject:input.subject,p_body:input.body,p_page_url:input.pageUrl||null});fail(error);return data as string}
export async function sendSupportMessage(ticketId:string,body:string){const {data,error}=await db().rpc('send_support_message',{p_ticket_id:ticketId,p_body:body});fail(error);return data as string}
export async function closeSupportTicket(ticketId:string){const {error}=await db().rpc('close_support_ticket',{p_ticket_id:ticketId});fail(error)}
export async function uploadClientAvatar(file:File){const ext=file.name.split('.').pop()||'jpg',path=`clients/${crypto.randomUUID()}.${ext}`;const {error}=await db().storage.from('avatars').upload(path,file,{upsert:false,contentType:file.type||'image/jpeg'});fail(error);const {data,error:signError}=await db().storage.from('avatars').createSignedUrl(path,60*60*24*365);fail(signError);if(!data)throw new Error('Photo indisponible');return data.signedUrl}
export async function listServices():Promise<Service[]>{const {data,error}=await db().from('service_catalog').select('*,suppliers(name)').order('category').order('name');fail(error);return data as Service[]}
export async function createService(input:Partial<Service>){const {data,error}=await db().from('service_catalog').insert(input).select().single();fail(error);return data as Service}
export async function updateService(id:string,input:Partial<Service>){const {data,error}=await db().from('service_catalog').update(input).eq('id',id).select().single();fail(error);return data as Service}
export async function deleteService(id:string){const {error}=await db().from('service_catalog').delete().eq('id',id);fail(error)}
export async function listEditorialItems():Promise<EditorialItem[]>{const {data,error}=await db().from('editorial_items').select('*,clients(name),projects(name),profiles:assignee_id(full_name)').order('publish_at',{ascending:true});fail(error);return data as EditorialItem[]}
export async function createEditorialItem(input:Partial<EditorialItem>){const {data,error}=await db().from('editorial_items').insert(input).select().single();fail(error);return data as EditorialItem}
export async function updateEditorialItem(id:string,input:Partial<EditorialItem>){const {data,error}=await db().from('editorial_items').update(input).eq('id',id).select().single();fail(error);return data as EditorialItem}
export async function deleteEditorialItem(id:string){const {error}=await db().from('editorial_items').delete().eq('id',id);fail(error)}
export async function listExpenses():Promise<Expense[]>{const {data,error}=await db().from('expenses').select('*,projects(name)').order('spent_on',{ascending:false});fail(error);return data as Expense[]}
export async function createExpense(input:Partial<Expense>){const {data:{user}}=await db().auth.getUser();const {data,error}=await db().from('expenses').insert({...input,submitted_by:user?.id}).select().single();fail(error);return data as Expense}
export async function updateExpenseStatus(id:string,status:string){const {data:{user}}=await db().auth.getUser();const {data,error}=await db().from('expenses').update({status,approved_by:status==='APPROUVE'?user?.id:null}).eq('id',id).select().single();fail(error);return data as Expense}
export async function listEquipment():Promise<Equipment[]>{const {data,error}=await db().from('equipment').select('*').order('name');fail(error);return data as Equipment[]}
export async function createEquipment(input:Partial<Equipment>){const {data,error}=await db().from('equipment').insert(input).select().single();fail(error);return data as Equipment}
export async function updateEquipment(id:string,input:Partial<Equipment>){const {data,error}=await db().from('equipment').update(input).eq('id',id).select().single();fail(error);return data as Equipment}
export async function deleteEquipment(id:string){const {error}=await db().from('equipment').delete().eq('id',id);fail(error)}
export async function listEquipmentCategories():Promise<EquipmentCategory[]>{const {data,error}=await db().from('equipment_categories').select('*').eq('active',true).order('name');fail(error);return data as EquipmentCategory[]}
export async function createEquipmentCategory(input:{name:string;description?:string}){const {data,error}=await db().from('equipment_categories').insert({name:input.name.trim(),description:input.description?.trim()||null}).select().single();fail(error);return data as EquipmentCategory}
export async function listEquipmentMovements(equipmentId?:string):Promise<EquipmentMovement[]>{let query=db().from('equipment_movements').select('*,equipment(name,code),profiles:handled_by(full_name)').order('moved_at',{ascending:false});if(equipmentId)query=query.eq('equipment_id',equipmentId);const {data,error}=await query.limit(100);fail(error);return data as EquipmentMovement[]}
export async function recordEquipmentMovement(input:{equipment_id:string;movement_type:'SORTIE'|'ENTREE'|'RETOUR';condition_notes?:string;reason?:string}){const {data,error}=await db().rpc('record_equipment_movement',{p_equipment_id:input.equipment_id,p_movement_type:input.movement_type,p_condition_notes:input.condition_notes||null,p_reason:input.reason||null});fail(error);return data}
export async function listActivityLogs():Promise<ActivityLog[]>{const {data,error}=await db().from('activity_logs').select('*,profiles:actor_id(full_name)').order('created_at',{ascending:false}).limit(200);fail(error);return data as ActivityLog[]}
export async function listUserSessions():Promise<UserSession[]>{const {data,error}=await db().from('user_sessions').select('*,profiles:profile_id(full_name)').order('last_seen_at',{ascending:false}).limit(200);fail(error);return data as UserSession[]}
export async function listNotifications():Promise<Notification[]>{const client=db(),{data:{user}}=await client.auth.getUser();if(!user)throw new Error('Session expirée');const {data,error}=await client.from('notifications').select('*,profiles:profile_id(full_name)').eq('profile_id',user.id).order('created_at',{ascending:false}).limit(100);fail(error);return data as Notification[]}
export async function markNotificationRead(id:string){const client=db(),{data:{user}}=await client.auth.getUser();if(!user)throw new Error('Session expirée');const {data,error}=await client.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('profile_id',user.id).select().single();fail(error);return data as Notification}
export async function markAllNotificationsRead(){const {data:{user}}=await db().auth.getUser();if(!user)throw new Error('Session expirée');const {error}=await db().from('notifications').update({read_at:new Date().toISOString()}).eq('profile_id',user.id).is('read_at',null);fail(error)}
export async function getCompanySettings():Promise<CompanySettings|null>{const {data,error}=await db().from('company_profile').select('*').limit(1).maybeSingle();fail(error);return data as CompanySettings|null}
export async function updateCompanySettings(input:Partial<CompanySettings>){const current=await getCompanySettings();const query=current?db().from('company_profile').update(input).eq('id',current.id):db().from('company_profile').insert(input);const {data,error}=await query.select().single();fail(error);return data as CompanySettings}
export async function getAppSetting<T=unknown>(key:string):Promise<T|null>{const {data,error}=await db().from('app_settings').select('value').eq('key',key).maybeSingle();fail(error);return (data?.value??null) as T|null}
export async function saveAppSetting(key:string,value:unknown){const client=db(),{data:{user}}=await client.auth.getUser();if(!user)throw new Error('Session expirée');const {data:profile,error:profileError}=await client.from('profiles').select('tenant_owner_id').eq('id',user.id).single();fail(profileError);const {data,error}=await client.from('app_settings').upsert({key,value,tenant_owner_id:profile?.tenant_owner_id||user.id,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:'tenant_owner_id,key'}).select().single();fail(error);return data}
export async function listCommercialDocuments():Promise<CommercialDocument[]>{const {data,error}=await db().from('commercial_documents').select('*,clients(name),projects(name)').order('created_at',{ascending:false});fail(error);return data as CommercialDocument[]}
export async function createCommercialDocument(input:Partial<CommercialDocument>){const {data,error}=await db().rpc('create_commercial_document',{p_kind:input.kind,p_client_id:input.client_id,p_project_id:input.project_id||null,p_expected_date:input.expected_date||null,p_currency:input.currency||'GNF',p_total:Number(input.total||0),p_notes:input.notes||null});fail(error);return data}
export async function updateCommercialDocument(id:string,input:Partial<CommercialDocument>){const {data,error}=await db().from('commercial_documents').update(input).eq('id',id).select().single();fail(error);return data as CommercialDocument}
export async function sendCommunication(input:{channel:'SMS'|'EMAIL';recipients:string[];message:string;subject?:string}){return invokeEdge<{status:string;testMode:boolean;recipientCount:number;providerStatus?:string|null}>('send-communication',input as unknown as Record<string,unknown>)}
export async function listProspects():Promise<Prospect[]>{const {data,error}=await db().from('prospects').select('*').order('created_at',{ascending:false});fail(error);return data as Prospect[]}
export async function createProspect(input:Partial<Prospect>){const {data,error}=await db().from('prospects').insert({company:input.company,contact_name:input.contact_name||null,phone:input.phone||null,whatsapp:input.whatsapp||null,email:input.email||null,sector:input.sector||null,source:input.source||'Prospection',need:input.need||null,stage:'NOUVEAU',sms_opt_in:Boolean(input.sms_opt_in),email_opt_in:input.email_opt_in!==false,marketing_opt_in:Boolean(input.marketing_opt_in)}).select().single();fail(error);return data as Prospect}
export async function updateProspect(id:string,input:Partial<Prospect>){const {data,error}=await db().from('prospects').update({company:input.company,contact_name:input.contact_name,phone:input.phone,whatsapp:input.whatsapp,email:input.email,sector:input.sector,need:input.need,stage:input.stage,last_contact_at:input.last_contact_at,next_follow_up_at:input.next_follow_up_at,notes:input.notes}).eq('id',id).select().single();fail(error);return data as Prospect}
export async function listCommunicationTemplates():Promise<CommunicationTemplate[]>{const {data,error}=await db().from('communication_templates').select('*').order('channel').order('name');fail(error);return data as CommunicationTemplate[]}
export async function createCommunicationTemplate(input:{channel:'SMS'|'EMAIL';name:string;subject?:string;body:string}){const {data,error}=await db().from('communication_templates').insert({channel:input.channel,name:input.name,subject:input.subject||null,body:input.body}).select().single();fail(error);return data as CommunicationTemplate}
export async function listCampaigns():Promise<Campaign[]>{const enhanced=await db().from('campaigns').select('*,clients(name),communication_templates(subject,body)').order('created_at',{ascending:false});if(!enhanced.error)return enhanced.data as Campaign[];const fallback=await db().from('campaigns').select('*,communication_templates(subject,body)').order('created_at',{ascending:false});fail(fallback.error);return fallback.data as Campaign[]}
export async function updateCampaignApproval(id:string,approval_status:'A_VALIDER'|'APPROUVE'|'REJETE'){const {data,error}=await db().from('campaigns').update({approval_status,approved_at:approval_status==='APPROUVE'?new Date().toISOString():null,status:approval_status==='APPROUVE'?'QUEUED':'DRAFT'}).eq('id',id).select('*,clients(name),communication_templates(subject,body)').single();fail(error);return data as Campaign}
export async function createCampaign(input:{name:string;channel:'SMS'|'EMAIL';subject?:string;message:string;recipients:string[];scheduled_at?:string|null;send_now?:boolean;scope?:'MARCEL'|'CLIENT';client_id?:string|null;objective?:string;approval_status?:'BROUILLON'|'A_VALIDER'|'APPROUVE';template_id?:string|null}){const client=db(),{data:{user}}=await client.auth.getUser();if(!user)throw new Error('Session expirée');let templateId=input.template_id||null;if(!templateId){const {data:template,error:templateError}=await client.from('communication_templates').insert({channel:input.channel,name:input.name,subject:input.subject||null,body:input.message}).select().single();fail(templateError);templateId=template.id}const approval=input.approval_status|| (input.send_now?'APPROUVE':'A_VALIDER');const enhancedPayload={name:input.name,channel:input.channel,template_id:templateId,status:approval==='APPROUVE'?'QUEUED':'DRAFT',approval_status:approval,scope:input.scope||'MARCEL',client_id:input.client_id||null,objective:input.objective||null,scheduled_at:input.send_now?new Date().toISOString():input.scheduled_at,recipient_count:input.recipients.length,created_by:user.id,approved_at:approval==='APPROUVE'?new Date().toISOString():null};let created=await client.from('campaigns').insert(enhancedPayload).select().single();if(created.error)created=await client.from('campaigns').insert({name:input.name,channel:input.channel,template_id:templateId,status:input.send_now?'QUEUED':'DRAFT',scheduled_at:input.send_now?new Date().toISOString():input.scheduled_at,recipient_count:input.recipients.length,created_by:user.id}).select().single();fail(created.error);const {data:campaign}=created;const {error:recipientsError}=await client.from('campaign_recipients').insert(input.recipients.map(address=>({campaign_id:campaign.id,address,status:'QUEUED'})));fail(recipientsError);if(input.send_now&&approval==='APPROUVE')await invokeEdge('campaign-dispatch',{campaign_id:campaign.id});return campaign as Campaign}
export async function listCallLogs():Promise<CallLog[]>{const {data,error}=await db().from('call_logs').select('*').order('created_at',{ascending:false}).limit(100);fail(error);return data as CallLog[]}
export async function startCall(input:{contact_type:'PROSPECT'|'CLIENT'|'CALL_LIST';contact_id:string;phone:string}){const client=db(),{data:{user}}=await client.auth.getUser();if(!user)throw new Error('Session expirée');const {data,error}=await client.from('call_logs').insert({...input,status:'DIALING',provider:'NATIVE_DIALER',consent_confirmed:true,initiated_by:user.id}).select().single();fail(error);if(input.contact_type==='CALL_LIST')await client.from('call_list_contacts').update({status:'DIALING',last_called_at:new Date().toISOString()}).eq('id',input.contact_id);return data as CallLog}
export async function finishCall(id:string,input:{status:string;outcome:string;notes:string;duration_seconds?:number;appointment_at?:string|null}){const client=db(),{data:current,error:currentError}=await client.from('call_logs').select('contact_type,contact_id').eq('id',id).single();fail(currentError);const {data,error}=await client.from('call_logs').update({status:input.status,outcome:input.outcome,notes:input.notes,duration_seconds:input.duration_seconds,ended_at:new Date().toISOString()}).eq('id',id).select().single();fail(error);if(current?.contact_type==='CALL_LIST'&&current.contact_id){const nextStatus=input.outcome.includes('RENDEZ-VOUS ACCEPTÉ')?'APPOINTMENT':input.outcome==='À RELANCER'||input.outcome==='INJOIGNABLE'?'CALLBACK':'CALLED';const {data:contact}=await client.from('call_list_contacts').select('attempts,total_call_seconds').eq('id',current.contact_id).single();await client.from('call_list_contacts').update({status:nextStatus,outcome:input.outcome,notes:input.notes,appointment_at:input.appointment_at||null,attempts:Number(contact?.attempts||0)+1,total_call_seconds:Number(contact?.total_call_seconds||0)+Number(input.duration_seconds||0),last_called_at:new Date().toISOString()}).eq('id',current.contact_id)}return data as CallLog}
export async function listContactGroups():Promise<ContactGroup[]>{const {data,error}=await db().from('contact_groups').select('*,contact_group_members(*)').order('created_at',{ascending:false});fail(error);return data as ContactGroup[]}
export async function createContactGroup(input:{name:string;description?:string;members:Array<{name:string;phone?:string;email?:string;company?:string;tags?:string}>}){const client=db(),{data:{user}}=await client.auth.getUser();if(!user)throw new Error('Session expirée');const {data:group,error}=await client.from('contact_groups').insert({name:input.name,description:input.description||null,created_by:user.id}).select().single();fail(error);if(input.members.length){const {error:membersError}=await client.from('contact_group_members').insert(input.members.map(member=>({group_id:group.id,name:member.name||'Sans nom',phone:member.phone||null,email:member.email||null,company:member.company||null,tags:member.tags||null,marketing_opt_in:true})));fail(membersError)}return group as ContactGroup}
export async function listCallLists():Promise<CallList[]>{const {data,error}=await db().from('call_lists').select('*,call_list_contacts(count)').order('created_at',{ascending:false});fail(error);return data as CallList[]}
export async function listCallListContacts(callListId:string):Promise<CallListContact[]>{const {data,error}=await db().from('call_list_contacts').select('*').eq('call_list_id',callListId).order('created_at');fail(error);return data as CallListContact[]}
export async function createCallList(input:{name:string;source_filename:string;contacts:Array<{name:string;phone:string;email?:string;company?:string}>}){const client=db(),{data:{user}}=await client.auth.getUser();if(!user)throw new Error('Session expirée');const {data:list,error}=await client.from('call_lists').insert({name:input.name,source_filename:input.source_filename,created_by:user.id}).select().single();fail(error);const usable=input.contacts.filter(contact=>contact.phone);if(!usable.length)throw new Error('Le fichier ne contient aucun numéro à appeler.');const {error:contactsError}=await client.from('call_list_contacts').insert(usable.map(contact=>({call_list_id:list.id,name:contact.name||'Sans nom',phone:contact.phone,email:contact.email||null,company:contact.company||null})));fail(contactsError);return list as CallList}
export async function getCalendarConnection():Promise<CalendarConnection|null>{const {data:{user}}=await db().auth.getUser();if(!user)return null;const {data,error}=await db().from('calendar_connections').select('profile_id,provider,calendar_email,connected,sync_enabled,calendar_id,updated_at').eq('profile_id',user.id).maybeSingle();fail(error);return data as CalendarConnection|null}
export async function connectGoogleCalendar(){const body=await invokeEdge<{url:string}>('google-calendar-start',{});location.assign(body.url)}

export async function listSuppliers():Promise<Supplier[]>{const {data,error}=await db().from('suppliers').select('*').order('name');fail(error);return data as Supplier[]}
export async function saveSupplier(input:Partial<Supplier>){const query=input.id?db().from('suppliers').update(input).eq('id',input.id):db().from('suppliers').insert(input);const {data,error}=await query.select().single();fail(error);return data as Supplier}
export async function deleteSupplier(id:string){const {error}=await db().from('suppliers').delete().eq('id',id);fail(error)}
export async function getAccessControl(profileId:string):Promise<AccessControl|null>{const {data,error}=await db().from('user_access_controls').select('*').eq('profile_id',profileId).maybeSingle();fail(error);return data as AccessControl|null}
export async function listSocialIntegrations(clientId?:string):Promise<SocialIntegration[]>{let query=db().from('social_integrations').select('*').order('provider');if(clientId)query=query.eq('client_id',clientId);const {data,error}=await query;fail(error);return data as SocialIntegration[]}
export async function saveSocialIntegration(input:Partial<SocialIntegration>){const payload={provider:input.provider,client_id:input.client_id||null,account_name:input.account_name||null,account_url:input.account_url||null,status:input.status||'CONNECTE',metrics:input.metrics||{},last_synced_at:input.last_synced_at||null};const query=input.id?db().from('social_integrations').update(payload).eq('id',input.id):db().from('social_integrations').insert(payload);const {data,error}=await query.select().single();fail(error);return data as SocialIntegration}
export async function saveAccessControl(input:AccessControl){const {data:{user}}=await db().auth.getUser();const {data,error}=await db().from('user_access_controls').upsert({...input,updated_by:user?.id}).select().single();fail(error);return data as AccessControl}
export async function listEmployeeRecords():Promise<EmployeeRecord[]>{const {data,error}=await db().from('employee_records').select('*,profiles(full_name,phone,role)').order('updated_at',{ascending:false});fail(error);return data as EmployeeRecord[]}
export async function saveEmployeeRecord(input:Partial<EmployeeRecord>){const {data,error}=await db().from('employee_records').upsert(input).select().single();fail(error);return data as EmployeeRecord}
export async function listLeaveRequests():Promise<LeaveRequest[]>{const {data,error}=await db().from('leave_requests').select('*,profiles(full_name)').order('created_at',{ascending:false});fail(error);return data as LeaveRequest[]}
export async function saveLeaveRequest(input:Partial<LeaveRequest>){const {data,error}=input.id?await db().from('leave_requests').update(input).eq('id',input.id).select().single():await db().from('leave_requests').insert(input).select().single();fail(error);return data as LeaveRequest}
export async function listQuotes():Promise<Quote[]>{const {data,error}=await db().from('quotes').select('*,clients(name,email,address),projects(name),quote_items(*)').order('created_at',{ascending:false});fail(error);return data as Quote[]}
export async function createQuote(input:{client_id:string;project_id?:string;valid_until:string;currency:string;discount:number;items:InvoiceItem[]}):Promise<Quote>{const {data,error}=await db().rpc('create_quote_with_items',{p_client_id:input.client_id,p_project_id:input.project_id||null,p_valid_until:input.valid_until,p_currency:input.currency,p_discount:input.discount,p_items:input.items});fail(error);if(!data)throw new Error('La création n’a renvoyé aucun numéro. Vérifiez la liste avant de réessayer.');invalidate('quotes');const {data:quote,error:readError}=await db().from('quotes').select('*,clients(name,email,address),projects(name),quote_items(*)').eq('id',data).single();if(readError)throw new Error(`Le devis a été créé, mais son affichage a échoué (${readError.message}). Actualisez la liste avant de réessayer pour éviter un doublon.`);return quote as Quote}
export async function deleteQuote(id:string){const {error}=await db().from('quotes').delete().eq('id',id);fail(error);invalidate('quotes')}
export async function askAiAssistant(prompt:string,context:string){const body=await invokeEdge<{answer:string}>('ai-assistant',{prompt,context});return body.answer}
export type TenantSmsState={can_manage:boolean;tenant_owner_id:string;tenants:{id:string;name:string}[];message?:string;trial?:{eligible:boolean;remaining:number;limit?:number;phone?:string;expires_at?:string;reason?:string};settings:null|{organization_name:string;sender_name:string;status:string;updated_at:string;credentials_saved:boolean}}
export async function tenantSmsSettings(body:Record<string,unknown>){return invokeEdge<TenantSmsState>('tenant-sms-settings',body)}
export async function performanceGoals(body:Record<string,unknown>={mode:'list'}){return invokeEdge<import('../lib/performanceGoals').GoalState>('performance-goals',body)}
export async function generateAgencyIntelligence(){return invokeEdge<{briefing:AgencyBriefing;actions:NextBestAction[]}>('agency-intelligence',{},true)}
export async function generateDigitalTwin(input?:{name?:string;client_delay_days?:number;new_contract_value?:number;expense_change_percent?:number}){return invokeEdge<DigitalTwinSnapshot>('growth-intelligence',{mode:'digital_twin',...input})}
export async function generateCommercialRadar(){return invokeEdge<CommercialRadar>('growth-intelligence',{mode:'commercial_radar'})}
export async function generateCampaignPlan(input:{name:string;objective:string;audience:string;offer?:string;channels:string[];tone:string;budget:number;currency?:string}){return invokeEdge<{draft:CampaignAiDraft}>('growth-intelligence',{mode:'campaign_plan',...input})}
export async function listAgencyScenarios():Promise<AgencyScenario[]>{const {data,error}=await db().from('agency_scenarios').select('*').order('created_at',{ascending:false}).limit(12);fail(error);return data as AgencyScenario[]}
export async function listCampaignAiDrafts():Promise<CampaignAiDraft[]>{const {data,error}=await db().from('campaign_ai_drafts').select('*').order('created_at',{ascending:false});fail(error);return data as CampaignAiDraft[]}
export async function updateCampaignAiDraftStatus(id:string,status:'A_VALIDER'|'APPROUVE'|'REJETE'){const {data,error}=await db().from('campaign_ai_drafts').update({status,approved_at:status==='APPROUVE'?new Date().toISOString():null}).eq('id',id).select().single();fail(error);return data as CampaignAiDraft}
export async function getAutopilotSettings():Promise<AutopilotSettings>{const {data:{user}}=await db().auth.getUser();if(!user)throw new Error('Session expirée');const {data,error}=await db().from('autopilot_settings').select('*').eq('profile_id',user.id).maybeSingle();fail(error);return (data||{profile_id:user.id,enabled:true,mode:'COPILOTE',daily_briefing:true,max_actions_per_run:12,approval_threshold:'TOUJOURS',updated_at:new Date().toISOString()}) as AutopilotSettings}
export async function saveAutopilotSettings(input:AutopilotSettings){const {data,error}=await db().from('autopilot_settings').upsert(input).select().single();fail(error);return data as AutopilotSettings}
export async function runAutopilot(){return invokeEdge<{run:AutopilotRun}>('autopilot',{mode:'run'})}
export async function listAutopilotRuns():Promise<AutopilotRun[]>{const {data,error}=await db().from('autopilot_runs').select('*,autopilot_actions(*)').order('started_at',{ascending:false}).limit(12);fail(error);return data as AutopilotRun[]}
export async function decideAutopilotAction(actionId:string,decision:'APPROVE'|'REJECT'){return invokeEdge<{action:AutopilotAction}>('autopilot',{mode:'decide',action_id:actionId,decision})}
export async function executeAutopilotAction(actionId:string){return invokeEdge<{action:AutopilotAction}>('autopilot',{mode:'execute',action_id:actionId})}
export async function updateNextBestAction(id:string,status:'TERMINEE'|'IGNOREE'){const {data,error}=await db().from('next_best_actions').update({status,executed_at:new Date().toISOString()}).eq('id',id).select().single();fail(error);return data as NextBestAction}
export async function executeNextBestAction(action:NextBestAction){if(action.action_type==='COMPLETE_TASK'&&action.source_id)await updateTask(action.source_id,{status:'TERMINE'});else if(action.action_type==='MARK_INVOICE_SENT'&&action.source_id)await updateInvoiceStatus(action.source_id,'ENVOYEE');return updateNextBestAction(action.id,'TERMINEE')}
export async function uploadEditorialAsset(file:File){const ext=file.name.split('.').pop()||'bin',path=`${crypto.randomUUID()}.${ext}`;const {error}=await db().storage.from('editorial-assets').upload(path,file,{upsert:false});fail(error);const {data,error:signError}=await db().storage.from('editorial-assets').createSignedUrl(path,60*60*24*365);fail(signError);if(!data)throw new Error('Lien du fichier indisponible');return data.signedUrl}
export async function listPortalAccess():Promise<PortalAccess[]>{const {data,error}=await db().from('client_portal_access').select('*,profiles(full_name),clients(name)').order('created_at',{ascending:false});fail(error);return data as PortalAccess[]}
export async function listCreativeApprovals(clientId?:string):Promise<CreativeApproval[]>{let query=db().from('creative_approvals').select('*,clients(name),editorial_items(title),creative_feedback(*,profiles(full_name))').order('created_at',{ascending:false});if(clientId)query=query.eq('client_id',clientId);const {data,error}=await query;fail(error);return data as CreativeApproval[]}
export async function createCreativeApproval(input:{client_id:string;editorial_item_id?:string;title:string;description?:string;asset_url:string;asset_type?:string;version?:number}){const {data:{user}}=await db().auth.getUser();if(!user)throw new Error('Session expirée');const {data,error}=await db().from('creative_approvals').insert({...input,editorial_item_id:input.editorial_item_id||null,description:input.description||null,asset_type:input.asset_type||'VISUEL',version:input.version||1,created_by:user.id,status:'A_VALIDER'}).select().single();fail(error);return data as CreativeApproval}
export async function respondCreativeApproval(id:string,decision:'APPROUVE'|'MODIFICATIONS_DEMANDEES',comment:string){const {data,error}=await db().rpc('respond_creative_approval',{p_approval_id:id,p_decision:decision,p_comment:comment});fail(error);return data as CreativeApproval}
export async function savePortalAccess(input:PortalAccess){const {data,error}=await db().from('client_portal_access').upsert(input).select().single();fail(error);return data as PortalAccess}
export async function createClientPortalAccess(input:{client_id:string;password:string;notify_email?:boolean;notify_sms?:boolean}){return invokeEdge<{id:string;deliveries:WelcomeDelivery[]}>('create-client-access',input)}
const portalMessage=(row:{id:string;client_id:string;sender_id:string;body:string;created_at:string;profiles?:{full_name:string}[]|{full_name:string}|null}):ClientPortalMessage=>({...row,profiles:Array.isArray(row.profiles)?row.profiles[0]||null:row.profiles||null})
export async function listClientPortalMessages(clientId:string):Promise<ClientPortalMessage[]>{const {data,error}=await db().from('client_portal_messages').select('id,client_id,sender_id,body,created_at,profiles(full_name)').eq('client_id',clientId).order('created_at',{ascending:true}).limit(200);fail(error);return (data||[]).map(portalMessage)}
export async function sendClientPortalMessage(clientId:string,body:string):Promise<ClientPortalMessage>{const {data:{user},error:authError}=await db().auth.getUser();fail(authError);if(!user)throw new Error('Session expirée');const value=body.trim();if(!value||value.length>4000)throw new Error('Le message doit contenir entre 1 et 4 000 caractères.');const {data,error}=await db().from('client_portal_messages').insert({client_id:clientId,sender_id:user.id,body:value}).select('id,client_id,sender_id,body,created_at,profiles(full_name)').single();fail(error);if(!data)throw new Error('Message non enregistré');return portalMessage(data)}
export async function listTeamChatMessages():Promise<TeamChatMessage[]>{const {data,error}=await db().from('team_chat_messages').select('id,sender_id,body,created_at,profiles(full_name)').order('created_at',{ascending:true}).limit(200);fail(error);return (data||[]).map(row=>({...row,profiles:Array.isArray(row.profiles)?row.profiles[0]||null:row.profiles||null}))}
export async function sendTeamChatMessage(body:string):Promise<TeamChatMessage>{const {data:{user},error:authError}=await db().auth.getUser();fail(authError);if(!user)throw new Error('Session expirée');const value=body.trim();if(!value||value.length>4000)throw new Error('Le message doit contenir entre 1 et 4 000 caractères.');const {data,error}=await db().from('team_chat_messages').insert({sender_id:user.id,body:value}).select('id,sender_id,body,created_at,profiles(full_name)').single();fail(error);if(!data)throw new Error('Message non enregistré');return {...data,profiles:Array.isArray(data.profiles)?data.profiles[0]||null:data.profiles||null}}
export async function getMyClientPortal():Promise<ClientPortalWorkspace>{const {data:{user}}=await db().auth.getUser();if(!user)throw new Error('Session expirée');const {data:access,error}=await db().from('client_portal_access').select('*').eq('profile_id',user.id).eq('active',true).single();fail(error);const clientId=access.client_id;const [client,projects,editorial,invoices,approvals]=await Promise.all([db().from('clients').select('*').eq('id',clientId).single(),db().from('projects').select('*,clients(name)').eq('client_id',clientId).order('created_at',{ascending:false}),db().from('editorial_items').select('*,clients(name),projects(name)').eq('client_id',clientId).order('publish_at',{ascending:true}),db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('client_id',clientId).order('created_at',{ascending:false}),db().from('creative_approvals').select('*,editorial_items(title),creative_feedback(*,profiles(full_name))').eq('client_id',clientId).order('created_at',{ascending:false})]);fail(client.error);fail(projects.error);fail(editorial.error);fail(invoices.error);fail(approvals.error);return {access:access as PortalAccess,client:client.data as Client,projects:projects.data as Project[],editorial:editorial.data as EditorialItem[],invoices:invoices.data as Invoice[],approvals:approvals.data as CreativeApproval[]}}
