import { supabase } from './supabase'
import type { ActivityLog, Client, CommercialDocument, EditorialItem, Equipment, Expense, Invoice, InvoiceItem, Payment, Profile, Project, Service, Task, UserSession } from '../types/models'

const db=()=>{if(!supabase)throw new Error('Supabase n’est pas configuré.');return supabase}
const fail=(error:{message:string}|null)=>{if(error)throw new Error(error.message)}

export async function signIn(email:string,password:string){const {data,error}=await db().auth.signInWithPassword({email,password});fail(error);return data}
export async function signOut(){const {error}=await db().auth.signOut();fail(error)}
export async function requestPasswordReset(email:string){const {error}=await db().auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/`});fail(error)}
export async function currentSession(){return (await db().auth.getSession()).data.session}
export function onAuthChange(callback:()=>void){return db().auth.onAuthStateChange(callback).data.subscription}
export async function getProfile():Promise<Profile>{const {data:{user}}=await db().auth.getUser();if(!user)throw new Error('Session expirée');const {data,error}=await db().from('profiles').select('*').eq('id',user.id).single();fail(error);return data as Profile}

export async function listClients():Promise<Client[]>{const {data,error}=await db().from('clients').select('*').order('created_at',{ascending:false});fail(error);return data as Client[]}
export async function createClient(input:Partial<Client>){const {data,error}=await db().from('clients').insert({name:input.name,legal_name:input.legal_name||null,sector:input.sector||null,phone:input.phone||null,whatsapp:input.whatsapp||null,email:input.email||null,address:input.address||null,status:'ACTIVE'}).select().single();fail(error);return data as Client}
export async function updateClient(id:string,input:Partial<Client>){const {data,error}=await db().from('clients').update(input).eq('id',id).select().single();fail(error);return data as Client}
export async function deleteClient(id:string){const {error}=await db().from('clients').delete().eq('id',id);fail(error)}
export async function getClientWorkspace(id:string){const [client,projects,tasks,invoices]=await Promise.all([db().from('clients').select('*').eq('id',id).single(),db().from('projects').select('*,clients(name)').eq('client_id',id).order('created_at',{ascending:false}),db().from('tasks').select('*,projects!inner(name,client_id),profiles:assignee_id(full_name)').eq('projects.client_id',id).order('created_at',{ascending:false}),db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('client_id',id).order('created_at',{ascending:false})]);fail(client.error);fail(projects.error);fail(tasks.error);fail(invoices.error);return {client:client.data as Client,projects:projects.data as Project[],tasks:tasks.data as Task[],invoices:invoices.data as Invoice[]}}
export async function listProjects():Promise<Project[]>{const {data,error}=await db().from('projects').select('*,clients(name),profiles:manager_id(full_name)').order('created_at',{ascending:false});fail(error);return data as Project[]}
export async function createProject(input:Partial<Project>){const {data,error}=await db().from('projects').insert({name:input.name,client_id:input.client_id||null,type:input.type||'Autre',starts_on:input.starts_on||null,ends_on:input.ends_on||null,budget:Number(input.budget||0),currency:input.currency||'GNF',status:'PLANIFIE',priority:input.priority||'NORMALE',progress:0,description:input.description||null}).select().single();fail(error);return data as Project}
export async function updateProject(id:string,input:Partial<Project>){const {data,error}=await db().from('projects').update(input).eq('id',id).select().single();fail(error);return data as Project}
export async function deleteProject(id:string){const {error}=await db().from('projects').delete().eq('id',id);fail(error)}
export async function getProjectWorkspace(id:string){const [project,tasks,invoices]=await Promise.all([db().from('projects').select('*,clients(name),profiles:manager_id(full_name)').eq('id',id).single(),db().from('tasks').select('*,projects(name),profiles:assignee_id(full_name)').eq('project_id',id).order('created_at',{ascending:false}),db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('project_id',id).order('created_at',{ascending:false})]);fail(project.error);fail(tasks.error);fail(invoices.error);return {project:project.data as Project,tasks:tasks.data as Task[],invoices:invoices.data as Invoice[]}}
export async function listTasks():Promise<Task[]>{const {data,error}=await db().from('tasks').select('*,projects(name,client_id),profiles:assignee_id(full_name)').order('created_at',{ascending:false});fail(error);return data as Task[]}
export async function createTask(input:Partial<Task>){const {data:{user}}=await db().auth.getUser();const {data,error}=await db().from('tasks').insert({title:input.title,project_id:input.project_id||null,description:input.description||null,status:'A_FAIRE',priority:input.priority||'NORMALE',due_at:input.due_at||null,creator_id:user?.id}).select().single();fail(error);return data as Task}
export async function updateTask(id:string,input:Partial<Task>){const patch={...input,...(input.status==='TERMINE'?{completed_at:new Date().toISOString()}:{completed_at:null})};const {data,error}=await db().from('tasks').update(patch).eq('id',id).select().single();fail(error);return data as Task}
export async function deleteTask(id:string){const {error}=await db().from('tasks').delete().eq('id',id);fail(error)}
export async function listInvoices():Promise<Invoice[]>{const {data,error}=await db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').order('created_at',{ascending:false});fail(error);return data as Invoice[]}
export async function createInvoice(input:{client_id:string;project_id?:string;due_date:string;currency:string;discount:number;items:InvoiceItem[]}):Promise<Invoice>{const {data,error}=await db().rpc('create_invoice_with_items',{p_client_id:input.client_id,p_project_id:input.project_id||null,p_due_date:input.due_date,p_currency:input.currency,p_discount:input.discount,p_items:input.items});fail(error);const id=typeof data==='string'?data:(data as {id:string})?.id;const {data:invoice,error:readError}=await db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('id',id).single();fail(readError);return invoice as Invoice}
export async function listPayments():Promise<Payment[]>{const {data,error}=await db().from('payments').select('*,invoices(number,total,clients(name))').order('paid_at',{ascending:false});fail(error);return data as Payment[]}
export async function recordPayment(input:{invoice_id:string;amount:number;method:string;reference?:string}){const {data,error}=await db().rpc('record_invoice_payment',{p_invoice_id:input.invoice_id,p_amount:input.amount,p_method:input.method,p_reference:input.reference||null});fail(error);return data}
export async function listProfiles():Promise<Profile[]>{const {data,error}=await db().from('profiles').select('*').order('full_name');fail(error);return data as Profile[]}
export async function createTeamMember(input:{email:string;password:string;name:string;role:string}){const {data:{session}}=await db().auth.getSession();if(!session)throw new Error('Session expirée');const response=await fetch('/.netlify/functions/create-team-member',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`},body:JSON.stringify(input)});const body=await response.json();if(!response.ok)throw new Error(body.error||'Création impossible');return body}
export async function updateProfile(id:string,input:Partial<Profile>){const {data,error}=await db().from('profiles').update(input).eq('id',id).select().single();fail(error);return data as Profile}
export async function listServices():Promise<Service[]>{const {data,error}=await db().from('service_catalog').select('*').order('category').order('name');fail(error);return data as Service[]}
export async function createService(input:Partial<Service>){const {data,error}=await db().from('service_catalog').insert(input).select().single();fail(error);return data as Service}
export async function updateService(id:string,input:Partial<Service>){const {data,error}=await db().from('service_catalog').update(input).eq('id',id).select().single();fail(error);return data as Service}
export async function deleteService(id:string){const {error}=await db().from('service_catalog').delete().eq('id',id);fail(error)}
export async function listEditorialItems():Promise<EditorialItem[]>{const {data,error}=await db().from('editorial_items').select('*,clients(name),projects(name),profiles:assignee_id(full_name)').order('publish_at',{ascending:true});fail(error);return data as EditorialItem[]}
export async function createEditorialItem(input:Partial<EditorialItem>){const {data,error}=await db().from('editorial_items').insert(input).select().single();fail(error);return data as EditorialItem}
export async function updateEditorialItem(id:string,input:Partial<EditorialItem>){const {data,error}=await db().from('editorial_items').update(input).eq('id',id).select().single();fail(error);return data as EditorialItem}
export async function deleteEditorialItem(id:string){const {error}=await db().from('editorial_items').delete().eq('id',id);fail(error)}
export async function listExpenses():Promise<Expense[]>{const {data,error}=await db().from('expenses').select('*,projects(name)').order('spent_on',{ascending:false});fail(error);return data as Expense[]}
export async function createExpense(input:Partial<Expense>){const {data:{user}}=await db().auth.getUser();const {data,error}=await db().from('expenses').insert({...input,submitted_by:user?.id}).select().single();fail(error);return data as Expense}
export async function listEquipment():Promise<Equipment[]>{const {data,error}=await db().from('equipment').select('*').order('name');fail(error);return data as Equipment[]}
export async function createEquipment(input:Partial<Equipment>){const {data,error}=await db().from('equipment').insert(input).select().single();fail(error);return data as Equipment}
export async function listActivityLogs():Promise<ActivityLog[]>{const {data,error}=await db().from('activity_logs').select('*,profiles:actor_id(full_name)').order('created_at',{ascending:false}).limit(200);fail(error);return data as ActivityLog[]}
export async function listUserSessions():Promise<UserSession[]>{const {data,error}=await db().from('user_sessions').select('*,profiles:profile_id(full_name)').order('last_seen_at',{ascending:false}).limit(200);fail(error);return data as UserSession[]}
export async function listCommercialDocuments():Promise<CommercialDocument[]>{const {data,error}=await db().from('commercial_documents').select('*,clients(name),projects(name)').order('created_at',{ascending:false});fail(error);return data as CommercialDocument[]}
export async function createCommercialDocument(input:Partial<CommercialDocument>){const {data,error}=await db().rpc('create_commercial_document',{p_kind:input.kind,p_client_id:input.client_id,p_project_id:input.project_id||null,p_expected_date:input.expected_date||null,p_currency:input.currency||'GNF',p_total:Number(input.total||0),p_notes:input.notes||null});fail(error);return data}
export async function updateCommercialDocument(id:string,input:Partial<CommercialDocument>){const {data,error}=await db().from('commercial_documents').update(input).eq('id',id).select().single();fail(error);return data as CommercialDocument}
export async function sendCommunication(input:{channel:'SMS'|'EMAIL';recipients:string[];message:string}){const response=await fetch('/.netlify/functions/send-communication',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});const body=await response.json();if(!response.ok)throw new Error(body.error||'Envoi impossible');return body}
