import { supabase } from './supabase'
import type { AccessControl, ActivityLog, CalendarConnection, Client, ClientPortalWorkspace, CommercialDocument, EditorialItem, EmployeeRecord, Equipment, Expense, Invoice, InvoiceItem, LeaveRequest, Payment, PortalAccess, Profile, Project, Quote, Service, Supplier, Task, UserSession } from '../types/models'

const db=()=>{if(!supabase)throw new Error('Supabase n’est pas configuré.');return supabase}
const fail=(error:{message:string}|null)=>{if(error)throw new Error(error.message)}
const queryCache=new Map<string,{until:number,value:unknown}>()
async function cached<T>(key:string,loader:()=>Promise<T>,ttl=45_000):Promise<T>{const hit=queryCache.get(key);if(hit&&hit.until>Date.now())return hit.value as T;const pending=loader();queryCache.set(key,{until:Date.now()+ttl,value:pending});try{const value=await pending;queryCache.set(key,{until:Date.now()+ttl,value});return value}catch(error){queryCache.delete(key);throw error}}
const invalidate=(...keys:string[])=>keys.forEach(key=>queryCache.delete(key))
async function invokeEdge<T>(name:string,body?:Record<string,unknown>):Promise<T>{const client=db();const {data,error}=await client.functions.invoke(name,{body});if(error){let message=error.message;const context=(error as {context?:Response}).context;if(context)try{const detail=await context.clone().json() as {error?:string};message=detail.error||message}catch{/* réponse non JSON */}throw new Error(message)}return data as T}

export async function signIn(email:string,password:string){const {data,error}=await db().auth.signInWithPassword({email,password});fail(error);return data}
export async function signOut(){const {error}=await db().auth.signOut();fail(error)}
export async function requestPasswordReset(email:string){const {error}=await db().auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/`});fail(error)}
export async function currentSession(){return (await db().auth.getSession()).data.session}
export function onAuthChange(callback:()=>void){return db().auth.onAuthStateChange(callback).data.subscription}
export async function getProfile():Promise<Profile>{const {data:{user}}=await db().auth.getUser();if(!user)throw new Error('Session expirée');const {data,error}=await db().from('profiles').select('*').eq('id',user.id).single();fail(error);return data as Profile}

export async function listClients():Promise<Client[]>{return cached('clients',async()=>{const {data,error}=await db().from('clients').select('*').order('created_at',{ascending:false});fail(error);return data as Client[]})}
export async function createClient(input:Partial<Client>){const {data,error}=await db().from('clients').insert({name:input.name,legal_name:input.legal_name||null,sector:input.sector||null,phone:input.phone||null,whatsapp:input.whatsapp||null,email:input.email||null,address:input.address||null,status:'ACTIVE'}).select().single();fail(error);invalidate('clients');return data as Client}
export async function updateClient(id:string,input:Partial<Client>){const {data,error}=await db().from('clients').update(input).eq('id',id).select().single();fail(error);return data as Client}
export async function deleteClient(id:string){const {error}=await db().from('clients').delete().eq('id',id);fail(error)}
export async function getClientWorkspace(id:string){const [client,projects,tasks,invoices]=await Promise.all([db().from('clients').select('*').eq('id',id).single(),db().from('projects').select('*,clients(name)').eq('client_id',id).order('created_at',{ascending:false}),db().from('tasks').select('*,projects!inner(name,client_id),profiles:assignee_id(full_name)').eq('projects.client_id',id).order('created_at',{ascending:false}),db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('client_id',id).order('created_at',{ascending:false})]);fail(client.error);fail(projects.error);fail(tasks.error);fail(invoices.error);return {client:client.data as Client,projects:projects.data as Project[],tasks:tasks.data as Task[],invoices:invoices.data as Invoice[]}}
export async function listProjects():Promise<Project[]>{return cached('projects',async()=>{const {data,error}=await db().from('projects').select('*,clients(name),profiles:manager_id(full_name)').order('created_at',{ascending:false});fail(error);return data as Project[]})}
export async function createProject(input:Partial<Project>){const {data,error}=await db().from('projects').insert({name:input.name,client_id:input.client_id||null,type:input.type||'Autre',starts_on:input.starts_on||null,ends_on:input.ends_on||null,budget:Number(input.budget||0),currency:input.currency||'GNF',status:'PLANIFIE',priority:input.priority||'NORMALE',progress:0,description:input.description||null}).select().single();fail(error);invalidate('projects');return data as Project}
export async function updateProject(id:string,input:Partial<Project>){const {data,error}=await db().from('projects').update(input).eq('id',id).select().single();fail(error);invalidate('projects');return data as Project}
export async function deleteProject(id:string){const {error}=await db().from('projects').delete().eq('id',id);fail(error);invalidate('projects')}
export async function getProjectWorkspace(id:string){const [project,tasks,invoices]=await Promise.all([db().from('projects').select('*,clients(name),profiles:manager_id(full_name)').eq('id',id).single(),db().from('tasks').select('*,projects(name),profiles:assignee_id(full_name)').eq('project_id',id).order('created_at',{ascending:false}),db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('project_id',id).order('created_at',{ascending:false})]);fail(project.error);fail(tasks.error);fail(invoices.error);return {project:project.data as Project,tasks:tasks.data as Task[],invoices:invoices.data as Invoice[]}}
export async function listTasks():Promise<Task[]>{return cached('tasks',async()=>{const {data,error}=await db().from('tasks').select('*,projects(name,client_id),profiles:assignee_id(full_name)').order('created_at',{ascending:false});fail(error);return data as Task[]})}
export async function createTask(input:Partial<Task>&{reminder_minutes?:number;notification_channels?:string[]}){const {data:{user}}=await db().auth.getUser();const {data,error}=await db().from('tasks').insert({title:input.title,project_id:input.project_id||null,assignee_id:input.assignee_id||null,description:input.description||null,status:'A_FAIRE',priority:input.priority||'NORMALE',due_at:input.due_at||null,reminder_minutes:input.reminder_minutes||30,notification_channels:input.notification_channels||['IN_APP'],creator_id:user?.id}).select().single();fail(error);invalidate('tasks');return data as Task}
export async function updateTask(id:string,input:Partial<Task>){const patch={...input,...(input.status==='TERMINE'?{completed_at:new Date().toISOString()}:{completed_at:null})};const {data,error}=await db().from('tasks').update(patch).eq('id',id).select().single();fail(error);invalidate('tasks');return data as Task}
export async function deleteTask(id:string){const {error}=await db().from('tasks').delete().eq('id',id);fail(error);invalidate('tasks')}
export async function listInvoices():Promise<Invoice[]>{return cached('invoices',async()=>{const {data,error}=await db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').order('created_at',{ascending:false});fail(error);return data as Invoice[]})}
export async function createInvoice(input:{client_id:string;project_id?:string;due_date:string;currency:string;discount:number;items:InvoiceItem[]}):Promise<Invoice>{const {data,error}=await db().rpc('create_invoice_with_items',{p_client_id:input.client_id,p_project_id:input.project_id||null,p_due_date:input.due_date,p_currency:input.currency,p_discount:input.discount,p_items:input.items});fail(error);const id=typeof data==='string'?data:(data as {id:string})?.id;const {data:invoice,error:readError}=await db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('id',id).single();fail(readError);return invoice as Invoice}
export async function deleteInvoice(id:string){const {error}=await db().from('invoices').delete().eq('id',id);fail(error);invalidate('invoices')}
export async function updateInvoiceStatus(id:string,status:string){const {data,error}=await db().from('invoices').update({status}).eq('id',id).select().single();fail(error);invalidate('invoices');return data as Invoice}
export async function listPayments():Promise<Payment[]>{const {data,error}=await db().from('payments').select('*,invoices(number,total,clients(name))').order('paid_at',{ascending:false});fail(error);return data as Payment[]}
export async function recordPayment(input:{invoice_id:string;amount:number;method:string;reference?:string}){const {data,error}=await db().rpc('record_invoice_payment',{p_invoice_id:input.invoice_id,p_amount:input.amount,p_method:input.method,p_reference:input.reference||null});fail(error);return data}
export async function listProfiles():Promise<Profile[]>{return cached('profiles',async()=>{const {data,error}=await db().from('profiles').select('id,full_name,role,roles,active,must_change_password,department_id,phone,created_at').order('full_name');fail(error);return data as Profile[]})}
export type WelcomeDelivery={channel:'EMAIL'|'SMS';status:'SENT'|'SKIPPED'|'FAILED';detail?:string}
export async function createTeamMember(input:{email:string;password:string;name:string;phone?:string;roles:string[];notify_email?:boolean;notify_sms?:boolean}){const result=await invokeEdge<{id:string;deliveries:WelcomeDelivery[]}>('create-team-member',input as unknown as Record<string,unknown>);invalidate('profiles');return result}
export async function completePasswordChange(password:string){return invokeEdge<{success:boolean}>('complete-password-change',{password})}
export async function updateProfile(id:string,input:Partial<Profile>){const {data,error}=await db().from('profiles').update(input).eq('id',id).select().single();fail(error);invalidate('profiles');return data as Profile}
export async function listServices():Promise<Service[]>{const {data,error}=await db().from('service_catalog').select('*').order('category').order('name');fail(error);return data as Service[]}
export async function createService(input:Partial<Service>){const {data,error}=await db().from('service_catalog').insert(input).select().single();fail(error);return data as Service}
export async function updateService(id:string,input:Partial<Service>){const {data,error}=await db().from('service_catalog').update(input).eq('id',id).select().single();fail(error);return data as Service}
export async function deleteService(id:string){const {error}=await db().from('service_catalog').delete().eq('id',id);fail(error)}
export async function listEditorialItems():Promise<EditorialItem[]>{const {data,error}=await db().from('editorial_items').select('*,clients(name),projects(name),profiles:assignee_id(full_name)').order('publish_at',{ascending:true});fail(error);return data as EditorialItem[]}
export async function createEditorialItem(input:Partial<EditorialItem>){const {data,error}=await db().from('editorial_items').insert(input).select().single();fail(error);return data as EditorialItem}
export async function updateEditorialItem(id:string,input:Partial<EditorialItem>){const {data,error}=await db().from('editorial_items').update(input).eq('id',id).select().single();fail(error);return data as EditorialItem}
export async function deleteEditorialItem(id:string){const {error}=await db().from('editorial_items').delete().eq('id',id);fail(error)}
export async function listExpenses():Promise<Expense[]>{const {data,error}=await db().from('expenses').select('*,projects(name)').order('spent_on',{ascending:false});fail(error);return data as Expense[]}
export async function createExpense(input:Partial<Expense>){const {data:{user}}=await db().auth.getUser();const {data,error}=await db().from('expenses').insert({...input,submitted_by:user?.id}).select().single();fail(error);return data as Expense}
export async function listEquipment():Promise<Equipment[]>{const {data,error}=await db().from('equipment').select('*').order('name');fail(error);return data as Equipment[]}
export async function createEquipment(input:Partial<Equipment>){const {data,error}=await db().from('equipment').insert(input).select().single();fail(error);return data as Equipment}
export async function listActivityLogs():Promise<ActivityLog[]>{const {data,error}=await db().from('activity_logs').select('*,profiles:actor_id(full_name)').order('created_at',{ascending:false}).limit(200);fail(error);return data as ActivityLog[]}
export async function listUserSessions():Promise<UserSession[]>{const {data,error}=await db().from('user_sessions').select('*,profiles:profile_id(full_name)').order('last_seen_at',{ascending:false}).limit(200);fail(error);return data as UserSession[]}
export async function listCommercialDocuments():Promise<CommercialDocument[]>{const {data,error}=await db().from('commercial_documents').select('*,clients(name),projects(name)').order('created_at',{ascending:false});fail(error);return data as CommercialDocument[]}
export async function createCommercialDocument(input:Partial<CommercialDocument>){const {data,error}=await db().rpc('create_commercial_document',{p_kind:input.kind,p_client_id:input.client_id,p_project_id:input.project_id||null,p_expected_date:input.expected_date||null,p_currency:input.currency||'GNF',p_total:Number(input.total||0),p_notes:input.notes||null});fail(error);return data}
export async function updateCommercialDocument(id:string,input:Partial<CommercialDocument>){const {data,error}=await db().from('commercial_documents').update(input).eq('id',id).select().single();fail(error);return data as CommercialDocument}
export async function sendCommunication(input:{channel:'SMS'|'EMAIL';recipients:string[];message:string}){return invokeEdge<{status:string;testMode:boolean;recipientCount:number;providerStatus?:string|null}>('send-communication',input as unknown as Record<string,unknown>)}
export async function getCalendarConnection():Promise<CalendarConnection|null>{const {data:{user}}=await db().auth.getUser();if(!user)return null;const {data,error}=await db().from('calendar_connections').select('profile_id,provider,calendar_email,connected,sync_enabled,calendar_id,updated_at').eq('profile_id',user.id).maybeSingle();fail(error);return data as CalendarConnection|null}
export async function connectGoogleCalendar(){const body=await invokeEdge<{url:string}>('google-calendar-start',{});location.assign(body.url)}

export async function listSuppliers():Promise<Supplier[]>{const {data,error}=await db().from('suppliers').select('*').order('name');fail(error);return data as Supplier[]}
export async function saveSupplier(input:Partial<Supplier>){const query=input.id?db().from('suppliers').update(input).eq('id',input.id):db().from('suppliers').insert(input);const {data,error}=await query.select().single();fail(error);return data as Supplier}
export async function deleteSupplier(id:string){const {error}=await db().from('suppliers').delete().eq('id',id);fail(error)}
export async function getAccessControl(profileId:string):Promise<AccessControl|null>{const {data,error}=await db().from('user_access_controls').select('*').eq('profile_id',profileId).maybeSingle();fail(error);return data as AccessControl|null}
export async function saveAccessControl(input:AccessControl){const {data:{user}}=await db().auth.getUser();const {data,error}=await db().from('user_access_controls').upsert({...input,updated_by:user?.id}).select().single();fail(error);return data as AccessControl}
export async function listEmployeeRecords():Promise<EmployeeRecord[]>{const {data,error}=await db().from('employee_records').select('*,profiles(full_name,phone,role)').order('updated_at',{ascending:false});fail(error);return data as EmployeeRecord[]}
export async function saveEmployeeRecord(input:Partial<EmployeeRecord>){const {data,error}=await db().from('employee_records').upsert(input).select().single();fail(error);return data as EmployeeRecord}
export async function listLeaveRequests():Promise<LeaveRequest[]>{const {data,error}=await db().from('leave_requests').select('*,profiles(full_name)').order('created_at',{ascending:false});fail(error);return data as LeaveRequest[]}
export async function saveLeaveRequest(input:Partial<LeaveRequest>){const {data,error}=input.id?await db().from('leave_requests').update(input).eq('id',input.id).select().single():await db().from('leave_requests').insert(input).select().single();fail(error);return data as LeaveRequest}
export async function listQuotes():Promise<Quote[]>{const {data,error}=await db().from('quotes').select('*,clients(name,email,address),projects(name),quote_items(*)').order('created_at',{ascending:false});fail(error);return data as Quote[]}
export async function createQuote(input:{client_id:string;project_id?:string;valid_until:string;currency:string;discount:number;items:InvoiceItem[]}):Promise<Quote>{const {data,error}=await db().rpc('create_quote_with_items',{p_client_id:input.client_id,p_project_id:input.project_id||null,p_valid_until:input.valid_until,p_currency:input.currency,p_discount:input.discount,p_items:input.items});fail(error);if(!data)throw new Error('Création du devis impossible');const {data:quote,error:readError}=await db().from('quotes').select('*,clients(name,email,address),projects(name),quote_items(*)').eq('id',data).single();fail(readError);return quote as Quote}
export async function deleteQuote(id:string){const {error}=await db().from('quotes').delete().eq('id',id);fail(error)}
export async function askAiAssistant(prompt:string,context:string){const body=await invokeEdge<{answer:string}>('ai-assistant',{prompt,context});return body.answer}
export async function uploadEditorialAsset(file:File){const ext=file.name.split('.').pop()||'bin',path=`${crypto.randomUUID()}.${ext}`;const {error}=await db().storage.from('editorial-assets').upload(path,file,{upsert:false});fail(error);const {data,error:signError}=await db().storage.from('editorial-assets').createSignedUrl(path,60*60*24*365);fail(signError);if(!data)throw new Error('Lien du fichier indisponible');return data.signedUrl}
export async function listPortalAccess():Promise<PortalAccess[]>{const {data,error}=await db().from('client_portal_access').select('*,profiles(full_name),clients(name)').order('created_at',{ascending:false});fail(error);return data as PortalAccess[]}
export async function savePortalAccess(input:PortalAccess){const {data,error}=await db().from('client_portal_access').upsert(input).select().single();fail(error);return data as PortalAccess}
export async function createClientPortalAccess(input:{client_id:string;password:string;notify_email?:boolean;notify_sms?:boolean}){return invokeEdge<{id:string;deliveries:WelcomeDelivery[]}>('create-client-access',input)}
export async function getMyClientPortal():Promise<ClientPortalWorkspace>{const {data:{user}}=await db().auth.getUser();if(!user)throw new Error('Session expirée');const {data:access,error}=await db().from('client_portal_access').select('*').eq('profile_id',user.id).eq('active',true).single();fail(error);const clientId=access.client_id;const [client,projects,editorial,invoices]=await Promise.all([db().from('clients').select('*').eq('id',clientId).single(),db().from('projects').select('*,clients(name)').eq('client_id',clientId).order('created_at',{ascending:false}),db().from('editorial_items').select('*,clients(name),projects(name)').eq('client_id',clientId).order('publish_at',{ascending:true}),db().from('invoices').select('*,clients(name,email,address),projects(name),invoice_items(*),payments(*)').eq('client_id',clientId).order('created_at',{ascending:false})]);fail(client.error);fail(projects.error);fail(editorial.error);fail(invoices.error);return {access:access as PortalAccess,client:client.data as Client,projects:projects.data as Project[],editorial:editorial.data as EditorialItem[],invoices:invoices.data as Invoice[]}}
