// @vitest-environment jsdom
import{afterEach,beforeEach,describe,expect,it,vi}from'vitest'
import{cleanup,fireEvent,render,screen,waitFor}from'@testing-library/react'
import ClientBrandProfile from './ClientBrandProfile'
import ClientJourney from './ClientJourney'
import CreativeReview from './CreativeReview'
import BillingRecovery from './BillingRecovery'
const api=vi.hoisted(()=>({brand:vi.fn(),save:vi.fn(),start:vi.fn(),annotations:vi.fn(),add:vi.fn(),draft:vi.fn(),write:vi.fn(),clear:vi.fn(),quotes:vi.fn()}))
vi.mock('./services/agencyWorkflow',()=>({emptyBrand:{logo_url:'',colors:'',fonts:'',tone:'',audience:'',offers:'',objectives:'',avoid:'',contacts:'',links:''},loadClientBrand:api.brand,saveClientBrand:api.save,startClientDelivery:api.start,loadClientBillingJourney:api.quotes,listCreativeAnnotations:api.annotations,addCreativeAnnotation:api.add,readBillingDraft:api.draft,writeBillingDraft:api.write,clearBillingDraft:api.clear}))
vi.mock('./services/repository',()=>({listQuotes:api.quotes}))
beforeEach(()=>{vi.clearAllMocks();api.brand.mockResolvedValue(null);api.annotations.mockResolvedValue([]);api.quotes.mockResolvedValue({quotes:[],invoices:[]});api.draft.mockResolvedValue(null);api.write.mockResolvedValue(undefined);api.clear.mockResolvedValue(undefined)})
afterEach(cleanup)
describe('agency workflow',()=>{
 it('shows paid and remaining amounts without aggregating different currencies',async()=>{api.quotes.mockResolvedValue({quotes:[],invoices:[{id:'i',client_id:'c',number:'FAC-1',total:1000,currency:'GNF',payments:[{amount:200}]},{id:'j',client_id:'c',number:'FAC-2',total:50,currency:'EUR',payments:[]},{id:'secret',client_id:'other',number:'SECRET',total:10,currency:'GNF'}]});render(<ClientJourney clientId="c" onChanged={()=>{}}/>);await screen.findByText('FAC-1');expect(screen.getByText('PARTIELLEMENT PAYEE').className).toContain('warning');expect(screen.getByText('IMPAYEE').className).toContain('danger');expect(screen.getByText(/Encaissé : 200 GNF/).textContent).toContain('Reste : 800 GNF');expect(screen.queryByText('SECRET')).toBeNull()})
 it('lets a failed client journey load be retried without a false empty success',async()=>{api.quotes.mockRejectedValueOnce(new Error('Connexion perdue')).mockResolvedValueOnce({quotes:[],invoices:[]});render(<ClientJourney clientId="c" onChanged={()=>{}}/>);await screen.findByRole('alert');fireEvent.click(screen.getByText('Réessayer le chargement'));await screen.findByText('Aucun document commercial pour ce client.');expect(screen.queryByRole('alert')).toBeNull()})
 it('does not show a previous client brand after a late response',async()=>{let resolveFirst!:(value:unknown)=>void;api.brand.mockImplementationOnce(()=>new Promise(resolve=>{resolveFirst=resolve})).mockResolvedValueOnce({revision:1,data:{tone:'Deuxième client'}});const view=render(<ClientBrandProfile clientId="first"/>);view.rerender(<ClientBrandProfile clientId="second"/>);await screen.findByDisplayValue('Deuxième client');resolveFirst({revision:1,data:{tone:'Premier client'}});await waitFor(()=>expect(screen.queryByDisplayValue('Premier client')).toBeNull())})
 it('brand readers cannot edit or save',async()=>{render(<ClientBrandProfile clientId="c"/>);await screen.findByText('Consultation uniquement.');expect(screen.getByLabelText('Ton de communication').matches(':disabled')).toBe(true);expect(screen.queryByText('Enregistrer le dossier')).toBeNull()})
 it('keeps brand edits after a save error',async()=>{api.brand.mockResolvedValue({revision:1,data:{tone:'Initial'}});api.save.mockRejectedValue(new Error('Conflit de version'));render(<ClientBrandProfile clientId="c" canEdit/>);const field=await screen.findByLabelText('Ton de communication');await waitFor(()=>expect((field as HTMLTextAreaElement).disabled).toBe(false));fireEvent.change(field,{target:{value:'Nouveau ton'}});fireEvent.click(screen.getByText('Enregistrer le dossier'));await screen.findByRole('alert');expect((field as HTMLTextAreaElement).value).toBe('Nouveau ton');expect(api.save).toHaveBeenCalledWith('c',expect.objectContaining({tone:'Nouveau ton'}),1)})
 it('shows only this client quotes and no start controls for readers',async()=>{api.quotes.mockResolvedValue({quotes:[{id:'q',client_id:'c',number:'DEV-1',total:100,currency:'GNF'},{id:'other',client_id:'b',number:'SECRET',total:500,currency:'GNF'}],invoices:[]});render(<ClientJourney clientId="c" onChanged={()=>{}}/>);await screen.findByText(/DEV-1/);expect(screen.queryByText(/SECRET/)).toBeNull();expect(screen.queryByText('Confirmer et démarrer le projet')).toBeNull()})
 it('closed versions cannot receive annotations',async()=>{render(<CreativeReview approval={{id:'r',title:'Test',version:1,status:'ARCHIVE',asset_type:'VISUEL',asset_url:'https://example.com/image.png'} as never} canComment/>);await waitFor(()=>expect(api.annotations).toHaveBeenCalled());expect(screen.queryByText('Enregistrer le commentaire')).toBeNull()})
 it('preserves a comment when its delivery fails',async()=>{api.add.mockRejectedValue(new Error('Réseau indisponible'));render(<CreativeReview approval={{id:'r',title:'Test',version:1,status:'A_VALIDER',asset_type:'VISUEL',asset_url:null} as never} canComment/>);fireEvent.change(screen.getByLabelText('Votre commentaire'),{target:{value:'Corriger le titre'}});fireEvent.click(screen.getByText('Enregistrer le commentaire'));await screen.findByRole('alert');expect((screen.getByLabelText('Votre commentaire') as HTMLTextAreaElement).value).toBe('Corriger le titre');expect(api.add).toHaveBeenCalledWith('r','Corriger le titre',null,null,null)})
 it('offers explicit draft recovery, never silently overwrites a form',async()=>{const restore=vi.fn();api.draft.mockResolvedValue({updated_at:'2026-10-10T10:00:00Z',payload:{clientId:'c',operationId:'fixed'}});render(<BillingRecovery draftKey="billing:DEVIS" revision="1" collect={()=>({})} restore={restore}/>);await screen.findByText('Reprendre');expect(restore).not.toHaveBeenCalled();fireEvent.click(screen.getByText('Reprendre'));expect(restore).toHaveBeenCalledWith({clientId:'c',operationId:'fixed'})})
})
