import{useEffect,useRef,useState}from'react'
import{readBillingDraft,writeBillingDraft,clearBillingDraft}from'./services/agencyWorkflow'
import './agency-workflow.css'
export default function BillingRecovery({draftKey,revision,collect,restore,enabled=true}:{draftKey:string;revision:string;collect:()=>Record<string,unknown>;restore:(data:Record<string,unknown>)=>void;enabled?:boolean}){
 const[saved,setSaved]=useState<{payload:Record<string,unknown>;updated_at:string}|null>(null),[loaded,setLoaded]=useState(false),[notice,setNotice]=useState(''),[retry,setRetry]=useState(0);const initial=useRef(true),collectRef=useRef(collect);collectRef.current=collect
 useEffect(()=>{if(!enabled)return;let live=true;void readBillingDraft(draftKey).then(row=>{if(live){setSaved(row);setLoaded(true)}}).catch(()=>{if(live){setLoaded(true);setNotice('Brouillons indisponibles : gardez ce formulaire ouvert pour conserver votre saisie.')}});return()=>{live=false}},[draftKey,enabled])
 useEffect(()=>{if(!enabled||!loaded||saved)return;if(initial.current){initial.current=false;return}let live=true;const timer=setTimeout(()=>{const snapshot=collectRef.current();if(!snapshot.clientId)return;setNotice('Sauvegarde du brouillon…');void writeBillingDraft(draftKey,snapshot).then(()=>{if(live)setNotice('Brouillon enregistré dans votre compte.')}).catch(()=>{if(live)setNotice('Brouillon non synchronisé. Votre saisie reste ici : vérifiez la connexion puis réessayez.')})},1000);return()=>{live=false;clearTimeout(timer)}},[revision,retry,loaded,saved,draftKey,enabled])
 if(!enabled)return null
 return <div className="draft-recovery" role="status">{saved?<><strong>Brouillon récupérable du {new Date(saved.updated_at).toLocaleString('fr-FR')}</strong><button type="button" onClick={()=>{restore(saved.payload);setSaved(null);initial.current=false;setNotice('Brouillon restauré.')}}>Reprendre</button><button type="button" onClick={()=>{void clearBillingDraft(draftKey).then(()=>{setSaved(null);setNotice('Ancien brouillon supprimé.')}).catch(()=>setNotice('Suppression du brouillon impossible. Réessayez.'))}}>Abandonner ce brouillon</button></>:<>{notice||'Vos brouillons seront sauvegardés dans votre compte après une modification.'}{notice.includes('non synchronisé')&&<button type="button" onClick={()=>setRetry(value=>value+1)}>Réessayer la sauvegarde</button>}</>}</div>
}
