import { useMemo, useState } from 'react'
import type { Campaign } from './types/models'
import './campaign-dashboard.css'

type Summary=Record<string,{sent:number;failed:number;queued:number}>
const monday=(date:Date)=>{const result=new Date(date.getFullYear(),date.getMonth(),date.getDate());result.setDate(result.getDate()-(result.getDay()+6)%7);return result}
export default function CampaignDashboard({campaigns,summary,loading}:{campaigns:Campaign[];summary:Summary;loading:boolean}){
  const [channel,setChannel]=useState<'ALL'|'SMS'|'EMAIL'>('ALL')
  const shown=campaigns.filter(item=>channel==='ALL'||item.channel===channel)
  const totals=shown.reduce((acc,item)=>{const row=summary[item.id];acc.recipients+=item.recipient_count||0;acc.sent+=row?.sent||0;acc.failed+=row?.failed||0;acc.queued+=row?.queued||0;return acc},{recipients:0,sent:0,failed:0,queued:0})
  const weeks=useMemo(()=>Array.from({length:6},(_,index)=>{const end=monday(new Date());const start=new Date(end);start.setDate(end.getDate()-(5-index)*7);const after=new Date(start);after.setDate(start.getDate()+7);return {label:start.toLocaleDateString('fr-FR',{day:'numeric',month:'short'}),count:shown.filter(item=>{const date=new Date(item.created_at);return date>=start&&date<after}).length}}),[shown])
  const max=Math.max(1,...weeks.map(week=>week.count))
  return <section className="campaign-dashboard" aria-label="Tableau de bord des campagnes"><div className="campaign-dashboard-head"><div><span className="eyebrow"><i/> ANALYSE DES CAMPAGNES</span><h3>Vue d’ensemble</h3></div><div className="segmented"><button type="button" className={channel==='ALL'?'active':''} onClick={()=>setChannel('ALL')}>Tout</button><button type="button" className={channel==='SMS'?'active':''} onClick={()=>setChannel('SMS')}>SMS</button><button type="button" className={channel==='EMAIL'?'active':''} onClick={()=>setChannel('EMAIL')}>E-mail</button></div></div><div className="campaign-dashboard-metrics"><div><small>Campagnes</small><strong>{shown.length}</strong></div><div><small>Destinataires prévus</small><strong>{totals.recipients}</strong></div><div><small>Acceptés par le fournisseur</small><strong>{totals.sent}</strong></div><div><small>En attente</small><strong>{totals.queued}</strong></div><div><small>Échecs</small><strong>{totals.failed}</strong></div></div><div className="campaign-dashboard-lower"><div className="panel campaign-volume"><h4>Campagnes créées · 6 semaines</h4><div className="campaign-bars">{weeks.map(week=><div key={week.label}><span>{week.count}</span><b style={{height:`${Math.max(5,week.count/max*100)}%`}}/><small>{week.label}</small></div>)}</div></div><div className="panel campaign-breakdown"><h4>Répartition des canaux</h4><div><span>SMS</span><strong>{shown.filter(item=>item.channel==='SMS').length}</strong></div><div><span>E-mail</span><strong>{shown.filter(item=>item.channel==='EMAIL').length}</strong></div><p>{loading?'Chargement des résultats…':'« Accepté » signifie transmis au fournisseur, pas nécessairement livré au téléphone.'}</p></div></div></section>
}
