import { useEffect, useState } from 'react'
import { ExternalLink, RefreshCw } from 'lucide-react'
import { canvaAction, type CanvaDesign } from './services/repository'
import './canva-integration.css'

export default function CanvaIntegrationPanel({canManage}:{canManage:boolean}){
  const [connected,setConnected]=useState(false),[configured,setConfigured]=useState(false),[ownerCanManage,setOwnerCanManage]=useState(false),[designs,setDesigns]=useState<CanvaDesign[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
  useEffect(()=>{void canvaAction<{connected:boolean;configured:boolean;canManage:boolean}>('status').then(result=>{setConnected(result.connected);setConfigured(result.configured);setOwnerCanManage(result.canManage)}).catch(cause=>setError(cause instanceof Error?cause.message:'Statut Canva indisponible'))},[])
  const connect=async()=>{setBusy(true);setError('');try{const result=await canvaAction<{url:string}>('start');window.location.assign(result.url)}catch(cause){setError(cause instanceof Error?cause.message:'Connexion Canva impossible');setBusy(false)}}
  const load=async()=>{setBusy(true);setError('');try{const result=await canvaAction<{items:CanvaDesign[]}>('designs');setDesigns(result.items)}catch(cause){setError(cause instanceof Error?cause.message:'Créations Canva indisponibles')}finally{setBusy(false)}}
  const disconnect=async()=>{if(!window.confirm('Déconnecter votre compte Canva de Smartsell ?'))return;setBusy(true);try{await canvaAction('disconnect');setConnected(false);setDesigns([])}catch(cause){setError(cause instanceof Error?cause.message:'Déconnexion impossible')}finally{setBusy(false)}}
  return <section className="panel canva-integration"><div className="canva-integration-head"><div className="canva-mark">C</div><div><span className="eyebrow"><i/> OUTIL CRÉATIF PARTAGÉ</span><h2>Canva</h2><p>Un seul compte Canva pour votre espace Smartsell : les collaborateurs autorisés à voir l’éditorial retrouvent les mêmes créations.</p></div><span className={`status ${connected?'success':'pending'}`}>{connected?'Connecté par Canva':'Non connecté'}</span></div>{error&&<p className="error-banner" role="alert">{error}</p>}<div className="canva-integration-actions">{connected?<><button type="button" className="primary-btn compact" disabled={busy} onClick={()=>void load()}><RefreshCw/>Afficher mes créations</button>{canManage&&ownerCanManage&&<button type="button" className="ghost-action" disabled={busy} onClick={()=>void disconnect()}>Déconnecter</button>}</>:ownerCanManage?<><button type="button" className="primary-btn compact" disabled={!canManage||busy||!configured} onClick={()=>void connect()}>Autoriser Canva</button>{!configured&&<span>Configuration Canva Developers requise avant la première connexion.</span>}</>:<span>Le propriétaire de cet espace peut connecter Canva pour toute l’équipe.</span>}</div>{designs.length>0&&<div className="canva-designs">{designs.map(design=><article key={design.id}>{design.thumbnail?<img src={design.thumbnail} alt="" loading="lazy"/>:<div className="canva-design-placeholder">C</div>}<strong>{design.title||'Création sans titre'}</strong>{design.edit_url&&<a href={design.edit_url} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Ouvrir dans Canva</a>}</article>)}</div>}</section>
}
