import { useEffect, useState } from 'react'
import { ExternalLink, RefreshCw } from 'lucide-react'
import { canvaAction, type CanvaDesign } from './services/repository'
import './canva-integration.css'

export default function CanvaIntegrationPanel({canManage}:{canManage:boolean}){
  const [statusLoading,setStatusLoading]=useState(true)
  const [connected,setConnected]=useState(false),[configured,setConfigured]=useState(false),[ownerCanManage,setOwnerCanManage]=useState(false),[sharedConnected,setSharedConnected]=useState(false),[accessGranted,setAccessGranted]=useState(false),[designs,setDesigns]=useState<CanvaDesign[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
  useEffect(()=>{let active=true;void canvaAction<{connected:boolean;configured:boolean;canManage:boolean;sharedConnected:boolean;accessGranted:boolean}>('status').then(result=>{if(!active)return;setConnected(result.connected);setConfigured(result.configured);setOwnerCanManage(result.canManage);setSharedConnected(result.sharedConnected);setAccessGranted(result.accessGranted)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Statut Canva indisponible')}).finally(()=>{if(active)setStatusLoading(false)});return()=>{active=false}},[])
  if(statusLoading)return <section className="panel canva-integration" aria-busy="true"><h2>Canva</h2><p role="status">Vérification de la connexion Canva…</p></section>
  if(error&&!connected&&!ownerCanManage&&!sharedConnected)return <section className="panel canva-integration"><h2>Canva</h2><p className="error-banner" role="alert">{error}</p><p>Le statut de la connexion n’a pas pu être vérifié. Rouvrez cette vue pour réessayer.</p></section>
  const connect=async()=>{setBusy(true);setError('');try{const result=await canvaAction<{url:string}>('start');window.location.assign(result.url)}catch(cause){setError(cause instanceof Error?cause.message:'Connexion Canva impossible');setBusy(false)}}
  const load=async()=>{setBusy(true);setError('');try{const result=await canvaAction<{items:CanvaDesign[]}>('designs');setDesigns(result.items)}catch(cause){setError(cause instanceof Error?cause.message:'Créations Canva indisponibles')}finally{setBusy(false)}}
  const disconnect=async()=>{if(!window.confirm('Déconnecter votre compte Canva de Smartsell ?'))return;setBusy(true);try{await canvaAction('disconnect');setConnected(false);setDesigns([])}catch(cause){setError(cause instanceof Error?cause.message:'Déconnexion impossible')}finally{setBusy(false)}}
  return <section className="panel canva-integration"><div className="canva-integration-head"><div className="canva-mark">C</div><div><span className="eyebrow"><i/> OUTIL CRÉATIF PARTAGÉ</span><h2>Canva</h2><p>Le propriétaire choisit dans RH quels collaborateurs peuvent ouvrir les créations Canva de cet espace.</p></div><span className={`status ${connected?'success':'pending'}`}>{connected?'Connecté par Canva':sharedConnected?'Accès non accordé':'Non connecté'}</span></div>{error&&<p className="error-banner" role="alert">{error}</p>}<div className="canva-integration-actions">{connected?<><button type="button" className="primary-btn compact" disabled={busy} onClick={()=>void load()}><RefreshCw/>Afficher mes créations</button>{canManage&&ownerCanManage&&<button type="button" className="ghost-action" disabled={busy} onClick={()=>void disconnect()}>Déconnecter</button>}</>:ownerCanManage?<><button type="button" className="primary-btn compact" disabled={!canManage||busy||!configured} onClick={()=>void connect()}>Autoriser Canva</button>{!configured&&<span>Configuration Canva Developers requise avant la première connexion.</span>}</>:sharedConnected&&!accessGranted?<span>Demandez au propriétaire de vous autoriser dans RH → Accès Canva.</span>:<span>Le propriétaire de cet espace peut connecter Canva pour toute l’équipe.</span>}</div>{designs.length>0&&<div className="canva-designs">{designs.map(design=><article key={design.id}>{design.thumbnail?<img src={design.thumbnail} alt="" loading="lazy"/>:<div className="canva-design-placeholder">C</div>}<strong>{design.title||'Création sans titre'}</strong>{design.edit_url&&<a href={design.edit_url} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Ouvrir dans Canva</a>}</article>)}</div>}</section>
}
