import{useEffect,useState,type FormEvent}from'react'
import{listQuotes}from'./services/repository'
import{startClientDelivery}from'./services/agencyWorkflow'
import type{Quote}from'./types/models'
import './agency-workflow.css'
export default function ClientJourney({clientId,canStart=false,onChanged}:{clientId:string;canStart?:boolean;onChanged:()=>void}){
 const[quotes,setQuotes]=useState<Quote[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 useEffect(()=>{let live=true;void listQuotes().then(rows=>{if(live)setQuotes(rows.filter(q=>q.client_id===clientId))}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[clientId])
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy||!canStart)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await startClientDelivery(selected,String(f.get('name')),String(f.get('starts')),String(f.get('ends')));setNotice('Projet créé ou récupéré. Le devis et ses prestations sont liés au projet.');setQuotes(current=>current.map(q=>q.id===selected?{...q,project_id:'linked'}:q));setSelected('');onChanged()}catch(e){setError(e instanceof Error?e.message:'Démarrage impossible')}finally{setBusy(false)}}
 return <section className="agency-workflow"><header><div><small>DU DEVIS À LA LIVRAISON</small><h3>Démarrer une mission client</h3><p>Reprenez le client, le budget, la devise et les prestations d’un devis sans double saisie. Le démarrage doit être confirmé par le manager.</p></div></header>{quotes.length?<ul>{quotes.map(q=><li key={q.id}>{q.number} · {new Intl.NumberFormat('fr-FR').format(q.total)} {q.currency} · {q.project_id?'Projet lié':'Projet à démarrer'}</li>)}</ul>:<p>Aucun devis disponible pour ce client.</p>}{canStart&&<form onSubmit={submit}><div className="agency-form-grid"><label>Devis<select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choisir…</option>{quotes.filter(q=>!q.project_id).map(q=><option value={q.id} key={q.id}>{q.number}</option>)}</select></label><label>Nom du projet<input name="name" required/></label><label>Début<input name="starts" type="date" required/></label><label>Livraison prévue<input name="ends" type="date" required/></label></div><label><input type="checkbox" required/> Je confirme que le client a accepté ces prestations et autorise le démarrage.</label><button className="primary-btn compact" disabled={busy}>{busy?'Démarrage…':'Confirmer et démarrer le projet'}</button></form>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>
}
