import { useEffect, useMemo, useRef, useState } from 'react'
import { BarChart3, Download, FileText, Plus, RefreshCw, Target, X } from 'lucide-react'
import { achievement, compareSocialMeasurements, effectiveCommitment, interpretClientResults, monthlyDeliveries, socialMeasures, socialNetworks, type ContractCommitment, type MonthlyCommitment, type MonthlyReport, type SocialMeasurement } from './lib/clientSocialReporting'
import { generateClientMonthlyReport, loadClientSocialReporting, saveClientMonthlyCommitment, saveClientServiceCommitment, saveClientSocialMeasurement } from './services/clientSocialReportingRepository'
import { invoicePdfFile } from './lib/invoicePdf'
import './client-social-dashboard.css'

const monthLabel=(month:string)=>new Date(`${month.slice(0,7)}-01T12:00:00Z`).toLocaleDateString('fr-FR',{month:'long',year:'numeric'})
const number=(value:number|null|undefined)=>value==null?'Non renseigné':new Intl.NumberFormat('fr-FR').format(value)
const deliverables=[['publications','Publications'],['videos','Vidéos'],['reels','Reels']] as const

export default function ClientSocialDashboard({tenantOwnerId,clientId,clientName,canEdit=false}:{tenantOwnerId:string;clientId:string;clientName:string;canEdit?:boolean}) {
  const [data,setData]=useState<Awaited<ReturnType<typeof loadClientSocialReporting>>|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[version,setVersion]=useState(0)
  const [month,setMonth]=useState(new Date().toISOString().slice(0,7)),[measurement,setMeasurement]=useState<Partial<SocialMeasurement>|null>(null),[targetOpen,setTargetOpen]=useState<'CONTRACT'|'MONTH'|null>(null),[report,setReport]=useState<MonthlyReport|null>(null)
  const pdfRef=useRef<HTMLDivElement>(null),lock=useRef(false)
  useEffect(()=>{
    let active=true;setData(null);setError('');setLoading(true);setReport(null);setMeasurement(null);setTargetOpen(null)
    void loadClientSocialReporting(tenantOwnerId,clientId).then(result=>{if(active)setData(result)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Suivi client indisponible.')}).finally(()=>{if(active)setLoading(false)})
    return()=>{active=false}
  },[tenantOwnerId,clientId,version])
  const target=data?effectiveCommitment(month,data.contracts,data.commitments):undefined
  const override=data?.commitments.find(row=>row.month.slice(0,7)===month)
  const contractAtMonth=data?.contracts.find(row=>row.effective_month.slice(0,7)===month)
  const delivered=useMemo(()=>monthlyDeliveries(data?.items||[],month),[data?.items,month])
  const comparisons=useMemo(()=>compareSocialMeasurements(data?.measurements||[],month),[data?.measurements,month])
  const interpretations=interpretClientResults(delivered,target,comparisons)
  const savedReport=data?.reports.find(row=>row.month.slice(0,7)===month)
  const action=async(callback:()=>Promise<void>,message:string)=>{
    if(lock.current||!canEdit)return
    lock.current=true;setBusy(true);setError('');setNotice('')
    try{await callback();setNotice(message);setVersion(value=>value+1)}catch(cause){setError(cause instanceof Error?cause.message:'Enregistrement impossible.')}finally{lock.current=false;setBusy(false)}
  }
  return <section className="client-social-dashboard" aria-label={`Performance de ${clientName}`}>
    <div className="client-social-heading"><div><span>SUIVI DU SERVICE COMMUNITY MANAGEMENT</span><h2>Objectifs & performance sociale</h2><p>Situation de départ, engagements récurrents, contenus livrés et bilan mensuel du client.</p></div><div className="client-social-actions"><label>Période<input type="month" aria-label="Mois du suivi client" value={month} onChange={event=>{if(event.target.value){setMonth(event.target.value);setTargetOpen(null)}}}/></label><button type="button" disabled={loading||busy} onClick={()=>setVersion(value=>value+1)} aria-label="Actualiser le suivi client"><RefreshCw/></button></div></div>
    {error&&<p className="client-social-error" role="alert">{error}<br/>Si le module vient d’être ajouté, sa migration Supabase doit être appliquée avant utilisation.</p>}{notice&&<p role="status">{notice}</p>}
    {loading?<p role="status">Chargement du suivi client…</p>:!data?<button type="button" onClick={()=>setVersion(value=>value+1)}>Réessayer</button>:<>
      {canEdit&&(!data.contracts.length||!data.measurements.some(row=>row.kind==='BASELINE'))&&<div className="client-social-onboarding"><h3>Initialiser le suivi de ce client</h3><ol><li>Fixez une fois les engagements récurrents : publications, vidéos et reels par mois.</li><li>Enregistrez la situation de départ de chaque page : date, abonnés, likes et partages.</li><li>Chaque mois, relevez les statistiques ; les contenus publiés alimentent automatiquement le bilan.</li></ol><small>Les engagements se répètent chaque mois. Une révision datée ne remplace pas les rapports déjà établis.</small></div>}
      {canEdit&&<div className="client-social-actions"><button type="button" disabled={busy} onClick={()=>setTargetOpen(value=>value==='CONTRACT'?null:'CONTRACT')}><Target/>{target?'Réviser le contrat à partir de ce mois':'Fixer les engagements récurrents'}</button><button type="button" disabled={busy} onClick={()=>setTargetOpen(value=>value==='MONTH'?null:'MONTH')}>Exception pour ce mois</button><button type="button" disabled={busy} onClick={()=>{setError('');setMeasurement({network:'FACEBOOK',account_key:'',kind:'BASELINE',measured_on:new Date().toISOString().slice(0,10)})}}><Plus/>Situation de départ</button><button type="button" disabled={busy} onClick={()=>{setError('');setMeasurement({network:comparisons[0]?.baseline.network||'FACEBOOK',account_key:comparisons[0]?.baseline.account_key||'',kind:'SNAPSHOT',measured_on:new Date().toISOString().slice(0,10)})}}><BarChart3/>Relever les statistiques</button></div>}
      {targetOpen&&canEdit&&<CommitmentForm key={`${month}-${targetOpen}`} month={month} recurring={targetOpen==='CONTRACT'} target={targetOpen==='CONTRACT'?(contractAtMonth||target):override} busy={busy} onSave={values=>action(()=>targetOpen==='CONTRACT'?saveClientServiceCommitment(tenantOwnerId,clientId,values,contractAtMonth?.id):saveClientMonthlyCommitment(tenantOwnerId,clientId,values,override?.id),targetOpen==='CONTRACT'?'Engagements contractuels récurrents enregistrés.':'Exception mensuelle enregistrée.')}/>}
      <section className="client-social-objectives"><h3>Engagements de {monthLabel(month)}</h3>{!target&&<p>Les engagements de ce mois n’ont pas encore été renseignés.</p>}<div className="client-social-kpis">{deliverables.map(([key,label])=>{const rate=achievement(delivered[key],target?.[key]);return <article key={key}><span>{label}</span><strong>{delivered[key]} <small>/ {target?target[key]:'—'}</small></strong><progress max={100} value={rate==null?0:Math.min(100,rate)} aria-label={`Avancement ${label}`}/><small>{rate===null?'Aucun objectif chiffré':`${rate}% de l’engagement réalisé`}</small></article>})}</div><p className="client-social-method">Seuls les contenus marqués « Publié » et datés dans le mois sont comptés, une fois par contenu. Les publications excluent les vidéos et les reels ; les vidéos excluent les reels.</p>{target?.notes&&<p>{target.notes}</p>}</section>
      <section><h3>Évolution des réseaux sociaux</h3><p className="client-social-method">Relevés manuels et datés. Une valeur absente n’est jamais remplacée par zéro. Les likes et partages doivent conserver la même définition entre les deux relevés.</p>{comparisons.length?comparisons.map(({baseline,latest})=><article className="client-social-network" key={baseline.id}><div className="client-social-heading"><h4>{baseline.network} · {baseline.account_key}</h4>{canEdit&&<button type="button" disabled={busy} onClick={()=>setMeasurement(baseline)}>Modifier la situation de départ</button>}</div><p>Départ : {baseline.measured_on} · Relevé du mois : {latest?.measured_on||'Non renseigné'}</p><div className="client-social-metrics">{socialMeasures.map(([key,label])=>{const delta=latest?.[key]!=null&&baseline[key]!=null?latest[key]!-baseline[key]!:null;return <div key={key}><span>{label}</span><strong>{number(latest?.[key])}</strong><small>Départ : {number(baseline[key])}</small>{delta!==null&&<em className={delta<0?'negative':'positive'}>{delta>0?'+':''}{number(delta)} depuis le départ</em>}</div>})}</div>{latest&&canEdit&&<button type="button" disabled={busy} onClick={()=>setMeasurement(latest)}>Modifier le relevé du mois</button>}</article>):<p>Aucune situation de départ renseignée pour ce client et cette période.</p>}</section>
      <section className="client-social-report-actions"><h3>Rapports mensuels</h3><p>Le rapport définitif est généré après la fin du mois et conservé dans le portail client. Le planificateur doit être activé dans Supabase. L’envoi par e-mail dépend de la configuration du fournisseur.</p><div className="client-social-actions">{savedReport?<button type="button" onClick={()=>setReport(savedReport)}><FileText/>Consulter le rapport de {monthLabel(month)}</button>:canEdit&&month<new Date().toISOString().slice(0,7)?<button type="button" disabled={busy} onClick={()=>void action(async()=>{await generateClientMonthlyReport(clientId,month)},'Rapport généré et disponible dans le portail client.')}>Générer le rapport du mois terminé</button>:<p>Aucun rapport définitif disponible pour cette période.</p>}</div>{data.reports.length>0&&<div className="client-social-report-list">{data.reports.map(row=><button type="button" key={row.id} onClick={()=>setReport(row)}>{monthLabel(row.month)} · Généré le {new Date(row.generated_at).toLocaleDateString('fr-FR')}</button>)}</div>}</section>
      <section className="client-social-interpretation"><h3>Lecture des résultats</h3><p className="client-social-method">Analyse fondée sur les chiffres renseignés et les livrables enregistrés, sans prédiction ni attribution automatique.</p><ul>{interpretations.map(text=><li key={text}>{text}</li>)}</ul></section>
    </>}
    {measurement&&canEdit&&<section className="client-social-editor"><div className="client-social-heading"><h3>{measurement.kind==='BASELINE'?'Situation de départ':'Relevé des performances'}</h3><button type="button" disabled={busy} aria-label="Fermer le relevé" onClick={()=>setMeasurement(null)}><X/></button></div><form key={measurement.id||`${measurement.kind}-${measurement.measured_on}`} onSubmit={event=>{
      event.preventDefault();const fields=new FormData(event.currentTarget),metrics=Object.fromEntries(socialMeasures.map(([key])=>[key,String(fields.get(key)||'').trim()===''?null:Number(fields.get(key))]))
      void action(()=>saveClientSocialMeasurement(tenantOwnerId,clientId,{...metrics,network:String(fields.get('network')),account_key:String(fields.get('account_key')),kind:measurement.kind,measured_on:String(fields.get('measured_on')),notes:String(fields.get('notes')||'')},measurement.id),'Statistiques datées enregistrées.')
    }}><fieldset disabled={busy}><div className="client-social-form"><label>Réseau<select name="network" defaultValue={measurement.network}>{socialNetworks.map(network=><option key={network}>{network}</option>)}</select></label><label>Page / compte<input name="account_key" required defaultValue={measurement.account_key||''} placeholder="Ex. @pageclient"/></label><label>Date du relevé<input name="measured_on" type="date" required max={new Date().toISOString().slice(0,10)} defaultValue={measurement.measured_on}/></label>{socialMeasures.map(([key,label])=><label key={key}>{label}<input name={key} type="number" min={0} step={1} defaultValue={measurement[key]??''} placeholder="Non renseigné"/></label>)}<label className="wide">Notes / source des chiffres<textarea name="notes" defaultValue={measurement.notes||''} placeholder="Ex. statistiques de la page relevées à cette date"/></label></div></fieldset><button type="submit" disabled={busy}>Enregistrer le relevé</button></form></section>}
    {report&&<section className="client-social-report-preview"><div className="client-social-actions"><button type="button" disabled={busy} onClick={async()=>{if(!pdfRef.current||lock.current)return;lock.current=true;setBusy(true);setError('');try{const file=await invoicePdfFile(pdfRef.current,`Rapport-${clientName}-${report.payload.month}`),url=URL.createObjectURL(file),anchor=document.createElement('a');anchor.href=url;anchor.download=file.name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),60_000)}catch(cause){setError(cause instanceof Error?cause.message:'PDF indisponible.')}finally{lock.current=false;setBusy(false)}}}><Download/>Télécharger le rapport PDF</button><button type="button" disabled={busy} onClick={()=>setReport(null)}>Fermer le rapport</button></div><div ref={pdfRef} className="client-social-print"><h2>Rapport mensuel — {report.payload.client_name}</h2><p>{monthLabel(report.payload.month)} · Établi le {new Date(report.generated_at).toLocaleDateString('fr-FR')}</p><h3>Bilan des engagements</h3>{deliverables.map(([key,label])=><p key={key}>{label} : {report.payload.delivered[key]} réalisé(s) / {report.payload.commitments?.[key]??'objectif non renseigné'} prévu(s)</p>)}<h3>Performances sociales</h3>{report.payload.social.map(row=><div key={`${row.network}-${row.account_key}`}><h4>{row.network} · {row.account_key}</h4><p>Départ : {row.baseline.measured_on} · Relevé : {row.latest?.measured_on||'Non renseigné'}</p>{socialMeasures.map(([key,label])=><p key={key}>{label} : {number(row.baseline[key])} → {number(row.latest?.[key])}</p>)}</div>)}{!report.payload.social.length&&<p>Aucun relevé social enregistré.</p>}<p>{report.payload.commitments?.notes}</p><h3>Lecture des résultats</h3><ul>{interpretClientResults(report.payload.delivered,report.payload.commitments||undefined,report.payload.social.map(row=>({baseline:row.baseline,latest:row.latest}))).map(text=><li key={text}>{text}</li>)}</ul><small>{report.payload.method}</small></div></section>}
  </section>
}
function CommitmentForm({month,target,busy,onSave,recurring}:{month:string;target?:MonthlyCommitment|ContractCommitment;busy:boolean;recurring:boolean;onSave:(input:{month:string;publications:number;videos:number;reels:number;notes:string})=>Promise<void>}) {
  return <form className="client-social-editor" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);void onSave({month,publications:Number(fields.get('publications')),videos:Number(fields.get('videos')),reels:Number(fields.get('reels')),notes:String(fields.get('notes')||'')})}}><h3>{recurring?'Engagements contractuels récurrents':'Exception mensuelle'}</h3><p>{recurring?`Volumes répétés chaque mois à partir de ${monthLabel(month)}. Une révision future conservera les versions précédentes.`:`Volumes spécifiques pour ${monthLabel(month)}, sans changer les engagements des autres mois.`}</p><fieldset disabled={busy}><div className="client-social-form">{deliverables.map(([key,label])=><label key={key}>{label} promises<input name={key} type="number" min={0} step={1} required defaultValue={target?.[key]??0}/></label>)}<label className="wide">Engagements complémentaires<textarea name="notes" defaultValue={target?.notes||''}/></label></div></fieldset><button disabled={busy}>Enregistrer les engagements</button></form>
}
