import {useEffect,useState,type FormEvent} from 'react'
import{emptyBrand,loadClientBrand,saveClientBrand,type BrandData}from'./services/agencyWorkflow'
import './agency-workflow.css'
const labels:Record<keyof BrandData,string>={logo_url:'Lien HTTPS du logo',colors:'Couleurs et codes hexadécimaux',fonts:'Polices',tone:'Ton de communication',audience:'Public cible',offers:'Produits et offres',objectives:'Objectifs et engagements',avoid:'Expressions et sujets à éviter',contacts:'Interlocuteurs et validateur',links:'Liens et réseaux sociaux'}
export default function ClientBrandProfile({clientId,canEdit=false}:{clientId:string;canEdit?:boolean}){
 const[data,setData]=useState<BrandData>(emptyBrand),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[loaded,setLoaded]=useState(false)
 const load=async()=>{setLoading(true);setLoaded(false);setError('');try{const record=await loadClientBrand(clientId);setData({...emptyBrand,...record?.data});setRevision(record?.revision||0);setLoaded(true)}catch(e){setError(e instanceof Error?e.message:'Dossier indisponible')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[clientId])
 const save=async(e:FormEvent)=>{e.preventDefault();if(!canEdit||busy)return;setBusy(true);setError('');setNotice('');try{const result=await saveClientBrand(clientId,data,revision);setRevision(result.revision);setNotice('Dossier de marque enregistré.')}catch(e){setError(e instanceof Error?e.message:'Échec de sauvegarde. Vos champs restent disponibles.')}finally{setBusy(false)}}
 return <section className="agency-workflow"><header><div><small>RÉFÉRENTIEL CLIENT</small><h3>Dossier de marque</h3><p>Une source commune pour les briefs, créations et validations. Aucun mot de passe ne doit être enregistré ici.</p></div><button type="button" disabled={busy} onClick={()=>{if(!canEdit||confirm('Recharger et abandonner les changements non enregistrés ?'))void load()}}>Recharger</button></header>{loading?<p>Chargement…</p>:<form onSubmit={save}><fieldset disabled={!canEdit||busy||!loaded}><div className="agency-form-grid">{(Object.keys(labels) as (keyof BrandData)[]).map(key=><label key={key}>{labels[key]}{key==='logo_url'?<input type="url" value={data[key]} onChange={e=>setData({...data,[key]:e.target.value})}/>:<textarea rows={2} maxLength={4000} value={data[key]} onChange={e=>setData({...data,[key]:e.target.value})}/>}</label>)}</div></fieldset>{canEdit&&<button className="primary-btn compact" disabled={busy||!loaded}>{busy?'Sauvegarde…':'Enregistrer le dossier'}</button>}</form>}{error&&<p role="alert">{error} Vos saisies ne sont pas effacées.</p>}{notice&&<p role="status">{notice}</p>}{!canEdit&&<p>Consultation uniquement.</p>}</section>
}
