import{useEffect,useState,type FormEvent}from'react'
import{startClientDelivery,loadClientBillingJourney}from'./services/agencyWorkflow'
import type{Quote,Invoice}from'./types/models'
import {statusTone} from './lib/statusTone'
import './agency-workflow.css'
export default function ClientJourney({clientId,canStart=false,onChanged,onBilling}:{clientId:string;canStart?:boolean;onChanged:()=>void;onBilling?:()=>void}){
 const[quotes,setQuotes]=useState<Quote[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const[invoices,setInvoices]=useState<Invoice[]>([]),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0)
 useEffect(()=>{let live=true;setLoading(true);setSelected('');setQuotes([]);setInvoices([]);setNotice('');setError('');void loadClientBillingJourney(clientId).then(rows=>{if(live){setQuotes(rows.quotes.filter(q=>q.client_id===clientId));setInvoices(rows.invoices.filter(q=>q.client_id===clientId))}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[clientId,retry])
 const financialSteps=<section aria-label="Étapes de la mission"><h4>Devis, mission et encaissements</h4><p>Cette vue reprend uniquement les documents de ce client. Un devis enregistré ne signifie pas que le client l’a accepté.</p>{loading?<p>Chargement du parcours…</p>:error?<p>Le parcours ne peut pas être confirmé : réessayez le chargement.</p>:<><div className="agency-form-grid">{quotes.filter(q=>q.client_id===clientId).map(q=><article className="journey-card" key={q.id}><strong>{q.number}</strong><p>{new Intl.NumberFormat('fr-FR').format(q.total)} {q.currency}</p><span className={`status ${statusTone(q.status)}`}>{(q.status||'BROUILLON').replaceAll('_',' ')}</span><p>{q.project_id?'Mission rattachée au devis':'Mission non démarrée'}</p></article>)}</div><div className="agency-form-grid">{invoices.filter(i=>i.client_id===clientId).map(invoice=>{const paid=invoice.payments?.reduce((s,p)=>s+Number(p.amount),0)||0,remaining=Math.max(0,Number(invoice.total)-paid),status=remaining===0?'PAYEE':paid>0?'PARTIELLEMENT_PAYEE':'IMPAYEE';return <article className="journey-card" key={invoice.id}><strong>{invoice.number}</strong><p>Montant : {new Intl.NumberFormat('fr-FR').format(invoice.total)} {invoice.currency}</p><span className={`status ${statusTone(status)}`}>{status.replaceAll('_',' ')}</span><p>Encaissé : {new Intl.NumberFormat('fr-FR').format(paid)} {invoice.currency}<br/>Reste : {new Intl.NumberFormat('fr-FR').format(remaining)} {invoice.currency}</p></article>})}</div>{!quotes.length&&!invoices.length&&<p>Aucun document commercial pour ce client.</p>}</>}{onBilling&&<button type="button" onClick={onBilling}>Ouvrir les devis, factures et paiements</button>}{error&&<button type="button" disabled={loading||busy} onClick={()=>setRetry(v=>v+1)}>Réessayer le chargement</button>}</section>
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy||!canStart)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await startClientDelivery(selected,String(f.get('name')),String(f.get('starts')),String(f.get('ends')));setNotice('Projet créé ou récupéré. Le devis et ses prestations sont liés au projet.');setQuotes(current=>current.map(q=>q.id===selected?{...q,project_id:'linked'}:q));setSelected('');onChanged()}catch(e){setError(e instanceof Error?e.message:'Démarrage impossible')}finally{setBusy(false)}}
 return <section className="agency-workflow"><header><div><small>DU DEVIS À LA LIVRAISON</small><h3>Démarrer une mission client</h3><p>Reprenez le client, le budget, la devise et les prestations d’un devis sans double saisie. Le démarrage doit être confirmé par le manager.</p></div></header>{financialSteps}{canStart&&!loading&&!error&&quotes.some(q=>!q.project_id)&&<form onSubmit={submit}><div className="agency-form-grid"><label>Devis<select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choisir…</option>{quotes.filter(q=>!q.project_id).map(q=><option value={q.id} key={q.id}>{q.number}</option>)}</select></label><label>Nom du projet<input name="name" required/></label><label>Début<input name="starts" type="date" required/></label><label>Livraison prévue<input name="ends" type="date" required/></label></div><label><input type="checkbox" required/> Je confirme que le client a accepté ces prestations et autorise le démarrage.</label><button className="primary-btn compact" disabled={busy}>{busy?'Démarrage…':'Confirmer et démarrer le projet'}</button></form>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>
}
