import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarDays, CheckCircle2, FileSpreadsheet, Mail, Phone, Plus, Save, Send, Upload, Users, X } from "lucide-react";
import { contactsFromFile, ImportedContact } from "./lib/contactImport";
import { createCallList, createCampaign, createCommunicationTemplate, createContactGroup, finishCall, listCallListContacts, listCallLists, listCallLogs, listCampaigns, listClients, listCommunicationTemplates, listContactGroups, listProspects, sendCommunication, startCall, updateCampaignApproval } from "./services/repository";
import type { CallList, CallListContact, CallLog, Campaign, Client, CommunicationTemplate, ContactGroup, Prospect } from "./types/models";

type Tool="MESSAGE"|"CAMPAIGNS"|"CALLS";
const starterTemplates:CommunicationTemplate[] = [
  ['SMS','Bienvenue nouveau client','', 'Bonjour {{nom}}, bienvenue chez Smartsell. Votre espace Smartsell est prêt : {{lien}}'],
  ['SMS','Confirmation de rendez-vous','', 'Bonjour {{nom}}, votre rendez-vous est confirmé le {{date}} à {{heure}}. Répondez à ce SMS si besoin.'],
  ['SMS','Rappel de rendez-vous','', 'Rappel Smartsell : rendez-vous aujourd’hui à {{heure}}. Nous avons hâte de vous retrouver, {{nom}}.'],
  ['SMS','Rappel de tâche','', 'Bonjour {{nom}}, la tâche « {{tache}} » arrive à échéance. Mettez-la à jour ici : {{lien}}'],
  ['SMS','Projet démarré','', 'Bonne nouvelle {{nom}} ! Le projet « {{projet}} » démarre. Suivez son avancement : {{lien}}'],
  ['SMS','Publication en ligne','', 'Votre contenu « {{contenu}} » est en ligne. Découvrez-le : {{lien}} — Smartsell'],
  ['SMS','Facture disponible','', 'Bonjour {{nom}}, votre facture {{facture}} est disponible. Consultez-la en toute sécurité : {{lien}}'],
  ['SMS','Paiement reçu','', 'Merci {{nom}} ! Votre paiement a bien été reçu. Smartsell reste à votre écoute.'],
  ['SMS','Relance douce','', 'Bonjour {{nom}}, souhaitez-vous que nous reprenions ensemble notre proposition ? Répondez à ce SMS.'],
  ['SMS','Merci fidélité','', 'Merci {{nom}} pour votre confiance. Toute l’équipe Smartsell vous souhaite une excellente journée.'],
  ['EMAIL','Bienvenue nouveau client','Bienvenue chez Smartsell', 'Bonjour {{nom}},\n\nVotre espace client Smartsell est prêt. Retrouvez vos projets, validations et factures depuis votre portail.'],
  ['EMAIL','Confirmation de rendez-vous','Votre rendez-vous est confirmé', 'Bonjour {{nom}},\n\nNous confirmons votre rendez-vous du {{date}} à {{heure}}.'],
  ['EMAIL','Compte rendu de réunion','Compte rendu — {{projet}}', 'Bonjour {{nom}},\n\nMerci pour notre échange. Voici les prochaines étapes convenues :\n{{actions}}'],
  ['EMAIL','Projet démarré','Le projet {{projet}} démarre', 'Bonjour {{nom}},\n\nL’équipe Smartsell démarre le projet {{projet}}. Vous pourrez suivre son avancement depuis votre espace.'],
  ['EMAIL','Validation attendue','Votre validation est attendue', 'Bonjour {{nom}},\n\nUn livrable est prêt à être validé : {{lien}}'],
  ['EMAIL','Publication en ligne','Votre publication est en ligne', 'Bonjour {{nom}},\n\nLa publication {{contenu}} est en ligne : {{lien}}'],
  ['EMAIL','Facture disponible','Votre facture {{facture}} est disponible', 'Bonjour {{nom}},\n\nVotre facture est disponible dans votre espace client.'],
  ['EMAIL','Relance commerciale','Une proposition pour {{entreprise}}', 'Bonjour {{nom}},\n\nNous revenons vers vous concernant notre proposition. Nous restons disponibles pour en parler.'],
  ['EMAIL','Rapport de campagne','Rapport de campagne — {{entreprise}}', 'Bonjour {{nom}},\n\nVotre rapport de campagne est disponible : {{lien}}'],
  ['EMAIL','Merci fidélité','Merci pour votre confiance', 'Bonjour {{nom}},\n\nMerci pour votre confiance. Nous sommes heureux de continuer à faire grandir vos projets.'],
].map(([channel,name,subject,body],index)=>({id:`starter-${index}`,channel:channel as 'SMS'|'EMAIL',name,subject:subject||null,body,created_at:''}));
const duration=(seconds:number)=>`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m ${seconds%60}s`;
const humanStatus=(status:string)=>({TO_CALL:"À APPELER",DIALING:"EN APPEL",CALLED:"APPELÉ",CALLBACK:"À RELANCER",APPOINTMENT:"RENDEZ-VOUS"}[status]||status);
function Overlay({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal comm-modal" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button type="button" className="icon-btn" onClick={onClose}><X/></button></div>{children}</section></div>}

export default function CommunicationHub({onBack,onOpenIntegrations,canApprove=false}:{onBack:()=>void;onOpenIntegrations?:()=>void;canApprove?:boolean}){
  const[tool,setTool]=useState<Tool>("MESSAGE"),[channel,setChannel]=useState<"SMS"|"EMAIL">("SMS"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const[to,setTo]=useState(""),[subject,setSubject]=useState(""),[message,setMessage]=useState("");
  const[campaigns,setCampaigns]=useState<Campaign[]>([]),[templates,setTemplates]=useState<CommunicationTemplate[]>([]),[groups,setGroups]=useState<ContactGroup[]>([]),[clients,setClients]=useState<Client[]>([]),[prospects,setProspects]=useState<Prospect[]>([]);
  const[callLists,setCallLists]=useState<CallList[]>([]),[selectedList,setSelectedList]=useState(""),[queue,setQueue]=useState<CallListContact[]>([]),[calls,setCalls]=useState<CallLog[]>([]);
  const[campaignOpen,setCampaignOpen]=useState(false),[groupOpen,setGroupOpen]=useState(false),[templateOpen,setTemplateOpen]=useState(false),[activeCall,setActiveCall]=useState<{log:CallLog;contact:CallListContact;started:number}|null>(null),[elapsed,setElapsed]=useState(0);
  const[groupImports,setGroupImports]=useState<ImportedContact[]>([]),[groupSelected,setGroupSelected]=useState<string[]>([]),[campaignRecipients,setCampaignRecipients]=useState("");
  const availableTemplates=[...starterTemplates,...templates.filter(item=>!starterTemplates.some(starter=>starter.name===item.name&&starter.channel===item.channel))];
  const reload=async()=>{try{const[a,t,b,c,d,e,f]=await Promise.all([listCampaigns(),listCommunicationTemplates(),listContactGroups(),listClients(),listProspects(),listCallLists(),listCallLogs()]);setCampaigns(a);setTemplates(t);setGroups(b);setClients(c);setProspects(d);setCallLists(e);setCalls(f);if(!selectedList&&e[0])setSelectedList(e[0].id)}catch(error){setNotice(error instanceof Error?error.message:"Chargement impossible")}};
  useEffect(()=>{void reload()},[]);
  useEffect(()=>{if(selectedList)void listCallListContacts(selectedList).then(setQueue).catch(error=>setNotice(error.message));else setQueue([])},[selectedList]);
  useEffect(()=>{if(!activeCall)return;setElapsed(0);const timer=window.setInterval(()=>setElapsed(Math.floor((Date.now()-activeCall.started)/1000)),1000);return()=>window.clearInterval(timer)},[activeCall]);
  const totalSeconds=queue.reduce((sum,item)=>sum+Number(item.total_call_seconds||0),0),called=queue.filter(item=>item.status!=="TO_CALL").length,appointments=queue.filter(item=>item.status==="APPOINTMENT").length;
  const candidates=useMemo(()=>[...clients.map(item=>({id:`client-${item.id}`,name:item.name,phone:item.phone||"",email:item.email||"",company:item.legal_name||item.name,tags:"Client"})),...prospects.map(item=>({id:`prospect-${item.id}`,name:item.contact_name||item.company,phone:item.phone||"",email:item.email||"",company:item.company,tags:"Prospect"})),...groupImports].filter(item=>item.phone||item.email),[clients,prospects,groupImports]);
  const importCallFile=async(file:File)=>{setBusy(true);try{const imported=(await contactsFromFile(file)).filter(contact=>contact.phone);const list=await createCallList({name:file.name.replace(/\.(xlsx|csv)$/i,""),source_filename:file.name,contacts:imported});setSelectedList(list.id);setNotice(`${imported.length} contact(s) ajoutés à la liste.`);await reload()}catch(error){setNotice(error instanceof Error?error.message:"Import impossible")}finally{setBusy(false)}};
  const placeCall=async(contact:CallListContact)=>{try{const log=await startCall({contact_type:"CALL_LIST",contact_id:contact.id,phone:contact.phone});setActiveCall({log,contact,started:Date.now()});location.href=`tel:${contact.phone.replace(/\s/g,"")}`}catch(error){setNotice(error instanceof Error?error.message:"Appel impossible")}};
  const chooseGroup=(id:string)=>{const group=groups.find(item=>item.id===id);setCampaignRecipients(Array.from(new Set((group?.contact_group_members||[]).map(member=>channel==="SMS"?member.phone:member.email).filter(Boolean) as string[])).join("\n"))};
  return <section className="communication-hub">
    <div className="module-head"><div><span className="eyebrow"><i/> COMMUNICATION & PROSPECTION</span><h1>Campagnes et centre d’appels</h1><p>Diffusez vos messages par personne ou groupe, puis mesurez chaque appel commercial.</p></div><div className="head-actions">{onOpenIntegrations&&<button className="ghost-action" onClick={onOpenIntegrations}><BarChart3/> Réseaux sociaux & connecteurs</button>}<button className="ghost-action" onClick={onBack}>← Retour</button></div></div>
    <div className="communication-mode-tabs"><button className={tool==="MESSAGE"?"active":""} onClick={()=>setTool("MESSAGE")}><Mail/>Message rapide</button><button className={tool==="CAMPAIGNS"?"active":""} onClick={()=>setTool("CAMPAIGNS")}><Send/>Campagnes</button><button className={tool==="CALLS"?"active":""} onClick={()=>setTool("CALLS")}><Phone/>Call center</button></div>
    {notice&&<button className="beta-notice" onClick={()=>setNotice("")}>{notice}<X size={15}/></button>}
    {tool==="MESSAGE"&&<form className="panel communication-compose hub-compose" onSubmit={async event=>{event.preventDefault();setBusy(true);try{const response=await sendCommunication({channel,recipients:to.split(/[;,\n]/).map(v=>v.trim()).filter(Boolean),subject,message});setNotice(`Envoi accepté pour ${response.recipientCount} destinataire(s).`)}catch(error){setNotice(error instanceof Error?error.message:"Envoi impossible")}finally{setBusy(false)}}}>
      <div className="channel-tabs"><button type="button" className={channel==="SMS"?"active":""} onClick={()=>setChannel("SMS")}>SMS</button><button type="button" className={channel==="EMAIL"?"active":""} onClick={()=>setChannel("EMAIL")}>E-mail</button></div>
      <div className="template-picker"><div><strong>Modèles SMS et e-mail</strong><small>{availableTemplates.filter(item=>item.channel===channel).length} modèles disponibles · vous pouvez aussi créer les vôtres.</small></div><select value="" onChange={e=>{const template=availableTemplates.find(item=>item.id===e.target.value);if(template){setChannel(template.channel);setSubject(template.subject||'');setMessage(template.body)}}}><option value="">Choisir un modèle</option>{availableTemplates.filter(item=>item.channel===channel).map(template=><option value={template.id} key={template.id}>{template.name}</option>)}</select><button type="button" className="ghost-action" onClick={()=>setTemplateOpen(true)}><Save/>Créer un modèle</button></div>
      <label>Destinataires<textarea value={to} onChange={e=>setTo(e.target.value)} placeholder="Un numéro ou e-mail par ligne" required/></label>{channel==="EMAIL"&&<label>Objet<input value={subject} onChange={e=>setSubject(e.target.value)} required/></label>}<label>Message<textarea rows={7} value={message} onChange={e=>setMessage(e.target.value)} required/></label><button className="primary-btn compact" disabled={busy}><Send/>{busy?"Envoi…":"Envoyer"}</button>
    </form>}
    {tool==="CAMPAIGNS"&&<div className="campaign-workspace">
      <div className="panel campaign-toolbar"><div><span className="eyebrow"><i/> MARKETING</span><h2>Campagnes SMS & e-mail</h2><p>Une personne, une sélection manuelle ou un groupe enregistré.</p></div><div className="head-actions"><button className="ghost-action" onClick={()=>setGroupOpen(true)}><Users/>Nouveau groupe</button><button className="primary-btn compact" onClick={()=>{setCampaignRecipients("");setCampaignOpen(true)}}><Plus/>Nouvelle campagne</button></div></div>
      <div className="campaign-stats"><div className="panel"><b>{campaigns.length}</b><span>Campagnes</span></div><div className="panel"><b>{campaigns.filter(item=>item.scope==="MARCEL").length}</b><span>Campagnes Smartsell</span></div><div className="panel"><b>{campaigns.filter(item=>item.scope==="CLIENT").length}</b><span>Campagnes clients</span></div><div className="panel"><b>{campaigns.filter(item=>item.approval_status==="A_VALIDER").length}</b><span>À valider</span></div></div>
      {!campaigns.length&&<div className="panel campaign-empty"><BarChart3/><div><h2>Votre espace marketing est prêt</h2><p>Créez un groupe ou lancez directement une campagne vers un numéro unique.</p></div><button className="primary-btn compact" onClick={()=>setCampaignOpen(true)}>Créer la première campagne</button></div>}
      <div className="records panel">{campaigns.map(item=><article key={item.id}><div className="record-main"><span className="record-avatar">{item.channel==="SMS"?"SM":"EM"}</span><div><strong>{item.name}</strong><small>{item.scope==='CLIENT'?`Client · ${item.clients?.name||'à préciser'}`:'Smartsell · interne'} · {item.channel} · {item.recipient_count} destinataire(s)</small></div></div><span className={`status ${item.approval_status==='REJETE'?'danger':''}`}>{item.approval_status||item.status}</span><span className="record-meta">{item.objective||'Objectif non renseigné'} · {item.scheduled_at?new Date(item.scheduled_at).toLocaleString("fr-FR"):"Immédiat"}</span>{canApprove&&item.approval_status==='A_VALIDER'?<div className="record-actions"><button className="primary-btn compact" onClick={async()=>{await updateCampaignApproval(item.id,'APPROUVE');await reload()}}><CheckCircle2/>Approuver</button><button className="ghost-action" onClick={async()=>{await updateCampaignApproval(item.id,'REJETE');await reload()}}>Rejeter</button></div>:<b className="record-amount">{item.approval_status==='APPROUVE'?'Prête à diffuser':'En préparation'}</b>}</article>)}</div>
    </div>}
    {tool==="CALLS"&&<div className="call-center">
      <div className="call-dashboard"><div className="panel"><span>Contacts</span><b>{queue.length}</b><small>liste active</small></div><div className="panel"><span>Appels traités</span><b>{called}</b><small>{queue.length?Math.round(called/queue.length*100):0}% de progression</small></div><div className="panel"><span>Temps d'appel</span><b>{duration(totalSeconds)}</b><small>temps cumulé</small></div><div className="panel"><span>Rendez-vous</span><b>{appointments}</b><small>{called?Math.round(appointments/called*100):0}% de conversion</small></div></div>
      <div className="panel call-list-toolbar"><div><h2>Base de contacts à appeler</h2><p>Importez un fichier Excel/CSV avec Nom et Téléphone.</p></div><select value={selectedList} onChange={e=>setSelectedList(e.target.value)}><option value="">Choisir une liste</option>{callLists.map(list=><option key={list.id} value={list.id}>{list.name} ({list.call_list_contacts?.[0]?.count||0})</option>)}</select><a className="ghost-action" href={`${import.meta.env.BASE_URL}templates/Modele-import-contacts-Smartsell.xlsx`} download><FileSpreadsheet/>Modèle</a><label className="primary-btn compact upload-inline"><Upload/>{busy?"Import…":"Importer Excel"}<input type="file" accept=".xlsx,.csv" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void importCallFile(file);e.currentTarget.value=""}}/></label></div>
      <div className="call-center-grid"><div className="panel call-queue"><div className="call-table-head"><span>Contact</span><span>Statut</span><span>Résultat</span><span>Temps</span><span/></div>{queue.map(contact=><div className="call-table-row" key={contact.id}><div><strong>{contact.name}</strong><small>{contact.company||"—"} · {contact.phone}</small></div><span className="status">{humanStatus(contact.status)}</span><span>{contact.outcome||"Pas encore appelé"}{contact.appointment_at&&<small>{new Date(contact.appointment_at).toLocaleString("fr-FR")}</small>}</span><b>{duration(contact.total_call_seconds||0)}</b><button onClick={()=>void placeCall(contact)}><Phone/>Appeler</button></div>)}{!queue.length&&<div className="empty-state"><Phone/><h3>Aucune liste active</h3><p>Importez votre fichier Excel pour démarrer.</p></div>}</div><aside className="panel call-history"><h3>Derniers appels</h3>{calls.slice(0,12).map(call=><div key={call.id}><span>{call.phone}</span><b>{call.outcome||call.status}</b><small>{duration(call.duration_seconds||0)} · {new Date(call.created_at).toLocaleString("fr-FR")}</small></div>)}</aside></div>
    </div>}
    {groupOpen&&<Overlay title="Créer un groupe de campagne" onClose={()=>setGroupOpen(false)}><form className="entity-form" onSubmit={async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),members=candidates.filter(item=>groupSelected.includes(item.id));if(!members.length){setNotice("Sélectionnez au moins un contact.");return}setBusy(true);try{await createContactGroup({name:String(form.get("name")),description:String(form.get("description")||""),members});setGroupOpen(false);setGroupSelected([]);setGroupImports([]);setNotice(`Groupe créé avec ${members.length} contact(s).`);await reload()}catch(error){setNotice(error instanceof Error?error.message:"Création impossible")}finally{setBusy(false)}}}>
      <div className="form-grid"><label>Nom du groupe<input name="name" required placeholder="Ex. Prospects Conakry"/></label><label>Description<input name="description"/></label></div><label className="upload-card compact-upload"><Upload/><span>Ajouter des contacts Excel/CSV</span><input type="file" accept=".xlsx,.csv" onChange={async e=>{const file=e.target.files?.[0];if(file)setGroupImports(await contactsFromFile(file))}}/></label><div className="group-member-list">{candidates.map(item=><label key={item.id}><input type="checkbox" checked={groupSelected.includes(item.id)} onChange={e=>setGroupSelected(e.target.checked?[...groupSelected,item.id]:groupSelected.filter(id=>id!==item.id))}/><span><strong>{item.name}</strong><small>{item.phone||item.email} · {item.company}</small></span></label>)}</div><button className="primary-btn compact" disabled={busy}><Users/>Créer le groupe ({groupSelected.length})</button>
    </form></Overlay>}
    {campaignOpen&&<Overlay title="Nouvelle campagne marketing" onClose={()=>setCampaignOpen(false)}><form className="entity-form" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget),action=((event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement)?.value||"approval",recipients=campaignRecipients.split(/[;,\n]/).map(v=>v.trim()).filter(Boolean);if(!recipients.length){setNotice("Ajoutez au moins un destinataire.");return}const approval=action==='now'?'APPROUVE':action==='draft'?'BROUILLON':'A_VALIDER';setBusy(true);try{await createCampaign({name:String(form.get("name")),channel,subject:String(form.get("subject")||""),message:String(form.get("message")),recipients:Array.from(new Set(recipients)),scheduled_at:String(form.get("scheduled_at")||"")||null,send_now:action==='now',scope:String(form.get('scope')||'MARCEL') as 'MARCEL'|'CLIENT',client_id:String(form.get('client_id')||'')||null,objective:String(form.get('objective')||''),template_id:String(form.get('template_id')||'')||null,approval_status:approval});setCampaignOpen(false);setNotice(approval==='APPROUVE'?"Campagne approuvée et lancée.":approval==='BROUILLON'?"Brouillon enregistré.":"Campagne soumise à validation.");await reload()}catch(error){setNotice(error instanceof Error?error.message:"Campagne impossible")}finally{setBusy(false)}}}>
      <div className="form-grid"><label>Nom<input name="name" required/></label><label>Type de campagne<select name="scope" defaultValue="MARCEL"><option value="MARCEL">Campagne interne Smartsell</option><option value="CLIENT">Campagne pour un client</option></select></label><label className="wide">Client concerné (si applicable)<select name="client_id" defaultValue=""><option value="">Aucun — Smartsell</option>{clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Canal<select value={channel} onChange={e=>{setChannel(e.target.value as "SMS"|"EMAIL");setCampaignRecipients("")}}><option value="SMS">SMS</option><option value="EMAIL">E-mail</option></select></label>{channel==="EMAIL"&&<label>Objet<input name="subject" required/></label>}<label className="wide">Objectif<textarea name="objective" rows={2} placeholder="Ex. générer des demandes de devis…"/></label><label className="wide">Modèle existant<select name="template_id" defaultValue=""><option value="">Créer à partir du contenu ci-dessous</option>{availableTemplates.filter(item=>item.channel===channel).map(template=><option value={template.id} key={template.id}>{template.name}</option>)}</select></label><label className="wide">Audience<select defaultValue="" onChange={e=>chooseGroup(e.target.value)}><option value="">Numéro unique / saisie manuelle</option>{groups.map(group=><option key={group.id} value={group.id}>Groupe : {group.name} ({group.contact_group_members?.length||0})</option>)}</select><div className="campaign-audience-actions"><button type="button" onClick={()=>setCampaignRecipients(clients.map(item=>channel==="SMS"?item.phone:item.email).filter(Boolean).join("\n"))}>Tous les clients</button><button type="button" onClick={()=>setCampaignRecipients(prospects.filter(item=>item.marketing_opt_in).map(item=>channel==="SMS"?item.phone:item.email).filter(Boolean).join("\n"))}>Prospects consentants</button></div><textarea rows={5} value={campaignRecipients} onChange={e=>setCampaignRecipients(e.target.value)} placeholder="Un destinataire par ligne" required/></label><label className="wide">Message<textarea name="message" rows={6} required/></label><label className="wide">Date/heure<input name="scheduled_at" type="datetime-local" defaultValue={new Date(Date.now()+3600000).toISOString().slice(0,16)}/></label></div><div className="form-actions"><button className="ghost-action" value="draft" disabled={busy}><Save/>Brouillon</button><button className="ghost-action" value="approval" disabled={busy}><CheckCircle2/>Soumettre à validation</button><button className="primary-btn compact" value="now" disabled={busy}><Send/>Approuver et envoyer</button></div>
    </form></Overlay>}
    {templateOpen&&<Overlay title="Créer un modèle SMS ou e-mail" onClose={()=>setTemplateOpen(false)}><form className="entity-form" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);try{await createCommunicationTemplate({channel,name:String(form.get('name')),subject:String(form.get('subject')||''),body:String(form.get('body'))});setTemplateOpen(false);setNotice('Modèle enregistré.');await reload()}catch(error){setNotice(error instanceof Error?error.message:'Modèle impossible')}finally{setBusy(false)}}}><div className="form-grid"><label>Canal<select name="channel" defaultValue={channel}><option value="SMS">SMS</option><option value="EMAIL">E-mail</option></select></label><label>Nom du modèle<input name="name" required placeholder="Bienvenue nouveau client"/></label><label className="wide">Objet e-mail (optionnel)<input name="subject"/></label><label className="wide">Contenu<textarea name="body" rows={8} required placeholder="Bonjour {{nom}}, bienvenue chez Smartsell…"/></label></div><p className="muted">Variables disponibles : <code>{'{{nom}}'}</code>, <code>{'{{entreprise}}'}</code>, <code>{'{{lien}}'}</code>.</p><button className="primary-btn compact" disabled={busy}><Save/>Enregistrer le modèle</button></form></Overlay>}
    {activeCall&&<Overlay title={`Compte rendu · ${activeCall.contact.name}`} onClose={()=>setActiveCall(null)}><form className="entity-form" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget),outcome=String(form.get("outcome"));setBusy(true);try{await finishCall(activeCall.log.id,{status:"COMPLETED",outcome,notes:String(form.get("notes")||""),duration_seconds:elapsed,appointment_at:String(form.get("appointment_at")||"")||null});setActiveCall(null);setNotice("Appel et résultat enregistrés.");setQueue(await listCallListContacts(selectedList));await reload()}catch(error){setNotice(error instanceof Error?error.message:"Enregistrement impossible")}finally{setBusy(false)}}}>
      <div className="call-live"><span className="call-live-icon"><Phone/></span><div><strong>{activeCall.contact.phone}</strong><small>Chronomètre automatique : {duration(elapsed)}</small></div></div><div className="form-grid"><label>Résultat<select name="outcome"><option>RENDEZ-VOUS ACCEPTÉ</option><option>RENDEZ-VOUS REFUSÉ</option><option>À RELANCER</option><option>INJOIGNABLE</option><option>NON INTÉRESSÉ</option><option>MAUVAIS NUMÉRO</option><option>APPEL EFFECTUÉ</option></select></label><label>Date du rendez-vous<input name="appointment_at" type="datetime-local"/></label><label className="wide">Notes<textarea name="notes" rows={5}/></label></div><button className="primary-btn compact" disabled={busy}><CheckCircle2/>Terminer et enregistrer</button>
    </form></Overlay>}
  </section>
}
