import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarDays, CheckCircle2, FileSpreadsheet, Mail, Phone, Plus, Send, Upload, Users, X } from "lucide-react";
import { contactsFromFile, ImportedContact } from "./lib/contactImport";
import { createCallList, createCampaign, createContactGroup, finishCall, listCallListContacts, listCallLists, listCallLogs, listCampaigns, listClients, listContactGroups, listProspects, sendCommunication, startCall } from "./services/repository";
import type { CallList, CallListContact, CallLog, Campaign, Client, ContactGroup, Prospect } from "./types/models";

type Tool="MESSAGE"|"CAMPAIGNS"|"CALLS";
const duration=(seconds:number)=>`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m ${seconds%60}s`;
const humanStatus=(status:string)=>({TO_CALL:"À APPELER",DIALING:"EN APPEL",CALLED:"APPELÉ",CALLBACK:"À RELANCER",APPOINTMENT:"RENDEZ-VOUS"}[status]||status);
function Overlay({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal comm-modal" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button type="button" className="icon-btn" onClick={onClose}><X/></button></div>{children}</section></div>}

export default function CommunicationHub({onBack,onOpenIntegrations}:{onBack:()=>void;onOpenIntegrations?:()=>void}){
  const[tool,setTool]=useState<Tool>("MESSAGE"),[channel,setChannel]=useState<"SMS"|"EMAIL">("SMS"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const[to,setTo]=useState(""),[subject,setSubject]=useState(""),[message,setMessage]=useState("");
  const[campaigns,setCampaigns]=useState<Campaign[]>([]),[groups,setGroups]=useState<ContactGroup[]>([]),[clients,setClients]=useState<Client[]>([]),[prospects,setProspects]=useState<Prospect[]>([]);
  const[callLists,setCallLists]=useState<CallList[]>([]),[selectedList,setSelectedList]=useState(""),[queue,setQueue]=useState<CallListContact[]>([]),[calls,setCalls]=useState<CallLog[]>([]);
  const[campaignOpen,setCampaignOpen]=useState(false),[groupOpen,setGroupOpen]=useState(false),[activeCall,setActiveCall]=useState<{log:CallLog;contact:CallListContact;started:number}|null>(null),[elapsed,setElapsed]=useState(0);
  const[groupImports,setGroupImports]=useState<ImportedContact[]>([]),[groupSelected,setGroupSelected]=useState<string[]>([]),[campaignRecipients,setCampaignRecipients]=useState("");
  const reload=async()=>{try{const[a,b,c,d,e,f]=await Promise.all([listCampaigns(),listContactGroups(),listClients(),listProspects(),listCallLists(),listCallLogs()]);setCampaigns(a);setGroups(b);setClients(c);setProspects(d);setCallLists(e);setCalls(f);if(!selectedList&&e[0])setSelectedList(e[0].id)}catch(error){setNotice(error instanceof Error?error.message:"Chargement impossible")}};
  useEffect(()=>{void reload()},[]);
  useEffect(()=>{if(selectedList)void listCallListContacts(selectedList).then(setQueue).catch(error=>setNotice(error.message));else setQueue([])},[selectedList]);
  useEffect(()=>{if(!activeCall)return;setElapsed(0);const timer=window.setInterval(()=>setElapsed(Math.floor((Date.now()-activeCall.started)/1000)),1000);return()=>window.clearInterval(timer)},[activeCall]);
  const totalSeconds=queue.reduce((sum,item)=>sum+Number(item.total_call_seconds||0),0),called=queue.filter(item=>item.status!=="TO_CALL").length,appointments=queue.filter(item=>item.status==="APPOINTMENT").length;
  const candidates=useMemo(()=>[...clients.map(item=>({id:`client-${item.id}`,name:item.name,phone:item.phone||"",email:item.email||"",company:item.legal_name||item.name,tags:"Client"})),...prospects.map(item=>({id:`prospect-${item.id}`,name:item.contact_name||item.company,phone:item.phone||"",email:item.email||"",company:item.company,tags:"Prospect"})),...groupImports].filter(item=>item.phone||item.email),[clients,prospects,groupImports]);
  const importCallFile=async(file:File)=>{setBusy(true);try{const imported=(await contactsFromFile(file)).filter(contact=>contact.phone);const list=await createCallList({name:file.name.replace(/\.(xlsx|csv)$/i,""),source_filename:file.name,contacts:imported});setSelectedList(list.id);setNotice(`${imported.length} contact(s) ajoutés à la liste.`);await reload()}catch(error){setNotice(error instanceof Error?error.message:"Import impossible")}finally{setBusy(false)}};
  const placeCall=async(contact:CallListContact)=>{try{const log=await startCall({contact_type:"CALL_LIST",contact_id:contact.id,phone:contact.phone});setActiveCall({log,contact,started:Date.now()});location.href=`tel:${contact.phone.replace(/\s/g,"")}`}catch(error){setNotice(error instanceof Error?error.message:"Appel impossible")}};
  const chooseGroup=(id:string)=>{const group=groups.find(item=>item.id===id);setCampaignRecipients(Array.from(new Set((group?.contact_group_members||[]).map(member=>channel==="SMS"?member.phone:member.email).filter(Boolean) as string[])).join("\n"))};
  return <section className="communication-hub">
    <div className="module-head"><div><span className="eyebrow"><i/> COMMUNICATION & PROSPECTION</span><h1>Campagnes et centre d’appels</h1><p>Diffusez vos messages par personne ou groupe, puis mesurez chaque appel commercial.</p></div><div className="head-actions">{onOpenIntegrations&&<button className="ghost-action" onClick={onOpenIntegrations}><BarChart3/> Réseaux sociaux & connecteurs</button>}<button className="ghost-action" onClick={onBack}>← Retour</button></div></div>
    <div className="communication-mode-tabs"><button className={tool==="MESSAGE"?"active":""} onClick={()=>setTool("MESSAGE")}><Mail/>Message rapide</button><button className={tool==="CAMPAIGNS"?"active":""} onClick={()=>setTool("CAMPAIGNS")}><Send/>Campagnes</button><button className={tool==="CALLS"?"active":""} onClick={()=>setTool("CALLS")}><Phone/>Call center</button></div>
    {notice&&<button className="beta-notice" onClick={()=>setNotice("")}>{notice}<X size={15}/></button>}
    {tool==="MESSAGE"&&<form className="panel communication-compose hub-compose" onSubmit={async event=>{event.preventDefault();setBusy(true);try{const response=await sendCommunication({channel,recipients:to.split(/[;,\n]/).map(v=>v.trim()).filter(Boolean),subject,message});setNotice(`Envoi accepté pour ${response.recipientCount} destinataire(s).`)}catch(error){setNotice(error instanceof Error?error.message:"Envoi impossible")}finally{setBusy(false)}}}>
      <div className="channel-tabs"><button type="button" className={channel==="SMS"?"active":""} onClick={()=>setChannel("SMS")}>SMS</button><button type="button" className={channel==="EMAIL"?"active":""} onClick={()=>setChannel("EMAIL")}>E-mail</button></div>
      <label>Destinataires<textarea value={to} onChange={e=>setTo(e.target.value)} placeholder="Un numéro ou e-mail par ligne" required/></label>{channel==="EMAIL"&&<label>Objet<input value={subject} onChange={e=>setSubject(e.target.value)} required/></label>}<label>Message<textarea rows={7} value={message} onChange={e=>setMessage(e.target.value)} required/></label><button className="primary-btn compact" disabled={busy}><Send/>{busy?"Envoi…":"Envoyer"}</button>
    </form>}
    {tool==="CAMPAIGNS"&&<div className="campaign-workspace">
      <div className="panel campaign-toolbar"><div><span className="eyebrow"><i/> MARKETING</span><h2>Campagnes SMS & e-mail</h2><p>Une personne, une sélection manuelle ou un groupe enregistré.</p></div><div className="head-actions"><button className="ghost-action" onClick={()=>setGroupOpen(true)}><Users/>Nouveau groupe</button><button className="primary-btn compact" onClick={()=>{setCampaignRecipients("");setCampaignOpen(true)}}><Plus/>Nouvelle campagne</button></div></div>
      <div className="campaign-stats"><div className="panel"><b>{campaigns.length}</b><span>Campagnes</span></div><div className="panel"><b>{groups.length}</b><span>Groupes</span></div><div className="panel"><b>{campaigns.filter(item=>item.status==="SENT").length}</b><span>Envoyées</span></div><div className="panel"><b>{campaigns.reduce((sum,item)=>sum+Number(item.recipient_count),0)}</b><span>Destinataires</span></div></div>
      {!campaigns.length&&<div className="panel campaign-empty"><BarChart3/><div><h2>Votre espace marketing est prêt</h2><p>Créez un groupe ou lancez directement une campagne vers un numéro unique.</p></div><button className="primary-btn compact" onClick={()=>setCampaignOpen(true)}>Créer la première campagne</button></div>}
      <div className="records panel">{campaigns.map(item=><article key={item.id}><div className="record-main"><span className="record-avatar">{item.channel==="SMS"?"SM":"EM"}</span><div><strong>{item.name}</strong><small>{item.channel} · {item.recipient_count} destinataire(s)</small></div></div><span className="status">{item.status}</span><span className="record-meta">{item.scheduled_at?new Date(item.scheduled_at).toLocaleString("fr-FR"):"Immédiat"}</span><b className="record-amount">Suivi actif</b></article>)}</div>
    </div>}
    {tool==="CALLS"&&<div className="call-center">
      <div className="call-dashboard"><div className="panel"><span>Contacts</span><b>{queue.length}</b><small>liste active</small></div><div className="panel"><span>Appels traités</span><b>{called}</b><small>{queue.length?Math.round(called/queue.length*100):0}% de progression</small></div><div className="panel"><span>Temps d'appel</span><b>{duration(totalSeconds)}</b><small>temps cumulé</small></div><div className="panel"><span>Rendez-vous</span><b>{appointments}</b><small>{called?Math.round(appointments/called*100):0}% de conversion</small></div></div>
      <div className="panel call-list-toolbar"><div><h2>Base de contacts à appeler</h2><p>Importez un fichier Excel/CSV avec Nom et Téléphone.</p></div><select value={selectedList} onChange={e=>setSelectedList(e.target.value)}><option value="">Choisir une liste</option>{callLists.map(list=><option key={list.id} value={list.id}>{list.name} ({list.call_list_contacts?.[0]?.count||0})</option>)}</select><a className="ghost-action" href={`${import.meta.env.BASE_URL}templates/Modele-import-contacts-Smartsell.xlsx`} download><FileSpreadsheet/>Modèle</a><label className="primary-btn compact upload-inline"><Upload/>{busy?"Import…":"Importer Excel"}<input type="file" accept=".xlsx,.csv" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void importCallFile(file);e.currentTarget.value=""}}/></label></div>
      <div className="call-center-grid"><div className="panel call-queue"><div className="call-table-head"><span>Contact</span><span>Statut</span><span>Résultat</span><span>Temps</span><span/></div>{queue.map(contact=><div className="call-table-row" key={contact.id}><div><strong>{contact.name}</strong><small>{contact.company||"—"} · {contact.phone}</small></div><span className="status">{humanStatus(contact.status)}</span><span>{contact.outcome||"Pas encore appelé"}{contact.appointment_at&&<small>{new Date(contact.appointment_at).toLocaleString("fr-FR")}</small>}</span><b>{duration(contact.total_call_seconds||0)}</b><button onClick={()=>void placeCall(contact)}><Phone/>Appeler</button></div>)}{!queue.length&&<div className="empty-state"><Phone/><h3>Aucune liste active</h3><p>Importez votre fichier Excel pour démarrer.</p></div>}</div><aside className="panel call-history"><h3>Derniers appels</h3>{calls.slice(0,12).map(call=><div key={call.id}><span>{call.phone}</span><b>{call.outcome||call.status}</b><small>{duration(call.duration_seconds||0)} · {new Date(call.created_at).toLocaleString("fr-FR")}</small></div>)}</aside></div>
    </div>}
    {groupOpen&&<Overlay title="Créer un groupe de campagne" onClose={()=>setGroupOpen(false)}><form className="entity-form" onSubmit={async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),members=candidates.filter(item=>groupSelected.includes(item.id));if(!members.length){setNotice("Sélectionnez au moins un contact.");return}setBusy(true);try{await createContactGroup({name:String(form.get("name")),description:String(form.get("description")||""),members});setGroupOpen(false);setGroupSelected([]);setGroupImports([]);setNotice(`Groupe créé avec ${members.length} contact(s).`);await reload()}catch(error){setNotice(error instanceof Error?error.message:"Création impossible")}finally{setBusy(false)}}}>
      <div className="form-grid"><label>Nom du groupe<input name="name" required placeholder="Ex. Prospects Conakry"/></label><label>Description<input name="description"/></label></div><label className="upload-card compact-upload"><Upload/><span>Ajouter des contacts Excel/CSV</span><input type="file" accept=".xlsx,.csv" onChange={async e=>{const file=e.target.files?.[0];if(file)setGroupImports(await contactsFromFile(file))}}/></label><div className="group-member-list">{candidates.map(item=><label key={item.id}><input type="checkbox" checked={groupSelected.includes(item.id)} onChange={e=>setGroupSelected(e.target.checked?[...groupSelected,item.id]:groupSelected.filter(id=>id!==item.id))}/><span><strong>{item.name}</strong><small>{item.phone||item.email} · {item.company}</small></span></label>)}</div><button className="primary-btn compact" disabled={busy}><Users/>Créer le groupe ({groupSelected.length})</button>
    </form></Overlay>}
    {campaignOpen&&<Overlay title="Nouvelle campagne marketing" onClose={()=>setCampaignOpen(false)}><form className="entity-form" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget),action=((event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement)?.value||"schedule",recipients=campaignRecipients.split(/[;,\n]/).map(v=>v.trim()).filter(Boolean);if(!recipients.length){setNotice("Ajoutez au moins un destinataire.");return}setBusy(true);try{await createCampaign({name:String(form.get("name")),channel,subject:String(form.get("subject")||""),message:String(form.get("message")),recipients:Array.from(new Set(recipients)),scheduled_at:String(form.get("scheduled_at")||"")||null,send_now:action==="now"});setCampaignOpen(false);setNotice(action==="now"?"Campagne lancée.":"Campagne planifiée.");await reload()}catch(error){setNotice(error instanceof Error?error.message:"Campagne impossible")}finally{setBusy(false)}}}>
      <div className="form-grid"><label>Nom<input name="name" required/></label><label>Canal<select value={channel} onChange={e=>{setChannel(e.target.value as "SMS"|"EMAIL");setCampaignRecipients("")}}><option value="SMS">SMS</option><option value="EMAIL">E-mail</option></select></label>{channel==="EMAIL"&&<label className="wide">Objet<input name="subject" required/></label>}<label className="wide">Audience<select defaultValue="" onChange={e=>chooseGroup(e.target.value)}><option value="">Numéro unique / saisie manuelle</option>{groups.map(group=><option key={group.id} value={group.id}>Groupe : {group.name} ({group.contact_group_members?.length||0})</option>)}</select><div className="campaign-audience-actions"><button type="button" onClick={()=>setCampaignRecipients(clients.map(item=>channel==="SMS"?item.phone:item.email).filter(Boolean).join("\n"))}>Tous les clients</button><button type="button" onClick={()=>setCampaignRecipients(prospects.filter(item=>item.marketing_opt_in).map(item=>channel==="SMS"?item.phone:item.email).filter(Boolean).join("\n"))}>Prospects consentants</button></div><textarea rows={5} value={campaignRecipients} onChange={e=>setCampaignRecipients(e.target.value)} placeholder="Un destinataire par ligne" required/></label><label className="wide">Message<textarea name="message" rows={6} required/></label><label className="wide">Date/heure<input name="scheduled_at" type="datetime-local" defaultValue={new Date(Date.now()+3600000).toISOString().slice(0,16)}/></label></div><div className="form-actions"><button className="ghost-action" value="schedule" disabled={busy}><CalendarDays/>Planifier</button><button className="primary-btn compact" value="now" disabled={busy}><Send/>Envoyer maintenant</button></div>
    </form></Overlay>}
    {activeCall&&<Overlay title={`Compte rendu · ${activeCall.contact.name}`} onClose={()=>setActiveCall(null)}><form className="entity-form" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget),outcome=String(form.get("outcome"));setBusy(true);try{await finishCall(activeCall.log.id,{status:"COMPLETED",outcome,notes:String(form.get("notes")||""),duration_seconds:elapsed,appointment_at:String(form.get("appointment_at")||"")||null});setActiveCall(null);setNotice("Appel et résultat enregistrés.");setQueue(await listCallListContacts(selectedList));await reload()}catch(error){setNotice(error instanceof Error?error.message:"Enregistrement impossible")}finally{setBusy(false)}}}>
      <div className="call-live"><span className="call-live-icon"><Phone/></span><div><strong>{activeCall.contact.phone}</strong><small>Chronomètre automatique : {duration(elapsed)}</small></div></div><div className="form-grid"><label>Résultat<select name="outcome"><option>RENDEZ-VOUS ACCEPTÉ</option><option>RENDEZ-VOUS REFUSÉ</option><option>À RELANCER</option><option>INJOIGNABLE</option><option>NON INTÉRESSÉ</option><option>MAUVAIS NUMÉRO</option><option>APPEL EFFECTUÉ</option></select></label><label>Date du rendez-vous<input name="appointment_at" type="datetime-local"/></label><label className="wide">Notes<textarea name="notes" rows={5}/></label></div><button className="primary-btn compact" disabled={busy}><CheckCircle2/>Terminer et enregistrer</button>
    </form></Overlay>}
  </section>
}
