import {useEffect,useRef,useState} from 'react'
import {Plus,ShoppingCart,Wallet,X} from 'lucide-react'
import {loadCompanyCosts,saveCompanyExpense,companyPurchaseAction,deleteCompanyExpense,type CompanyPurchase} from './services/companyPurchases'
import type {Expense,Project,Supplier} from './types/models'
import {statusTone} from './lib/statusTone'
import './companyCosts.css'
type Rights={view:boolean;create:boolean;update:boolean;delete:boolean}
const money=(n:number,currency:string)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency,maximumFractionDigits:0}).format(n)
const statuses:Record<string,string>={BROUILLON:'À approuver',EN_ATTENTE:'En attente',APPROUVE:'Approuvé',REFUSE:'Refusé',CONVERTI:'Enregistré en charge'}
export default function CompanyCosts({tenantOwnerId,rights,canProjects=false,canSuppliers=false,blocked=false}:{tenantOwnerId:string;rights:Rights;canProjects?:boolean;canSuppliers?:boolean;blocked?:boolean}){
 const [data,setData]=useState<{expenses:Expense[];purchases:CompanyPurchase[];projects:Project[];suppliers:Supplier[]}|null>(null),[tab,setTab]=useState<'DEPENSE'|'ACHAT'|'REQUEST'>('DEPENSE'),[currency,setCurrency]=useState('GNF'),[search,setSearch]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState<'EXPENSE'|'PURCHASE'|'CONVERT'|null>(null),[selected,setSelected]=useState<Expense|null>(null),[purchase,setPurchase]=useState<CompanyPurchase|null>(null);
 const lock=useRef(false);
 const load=async()=>setData(await loadCompanyCosts(tenantOwnerId,canProjects,canSuppliers));
 useEffect(()=>{let active=true;if(rights.view)loadCompanyCosts(tenantOwnerId,canProjects,canSuppliers).then(result=>{if(active)setData(result)}).catch(reason=>{if(active)setError(reason.message)});return()=>{active=false}},[tenantOwnerId,rights.view,canProjects,canSuppliers]);
 const run=async(action:()=>Promise<unknown>,message:string)=>{if(lock.current||blocked)return;lock.current=true;setBusy(true);setError('');try{await action();setNotice(message);try{await load()}catch{setError('Enregistrement effectué, mais actualisation impossible. Actualisez avant de réessayer.')}}catch(reason){setError(reason instanceof Error?reason.message:'Action impossible')}finally{lock.current=false;setBusy(false)}};
 if(!rights.view)return <p>Accès à la comptabilité non autorisé.</p>;
 const expenses=(data?.expenses||[]).filter(e=>e.currency===currency),approved=expenses.filter(e=>e.status==='APPROUVE'),pending=expenses.filter(e=>['BROUILLON','EN_ATTENTE'].includes(e.status));
 const total=(rows:Expense[])=>rows.reduce((sum,e)=>sum+Number(e.amount),0);
 const rows=expenses.filter(e=>(e.kind||'DEPENSE')===tab&&`${e.description} ${e.category||''} ${e.suppliers?.name||''} ${e.reference||''}`.toLowerCase().includes(search.toLowerCase()));
 const close=()=>{if(!busy){setMode(null);setSelected(null);setPurchase(null);setError('')}};
 return <section className="company-costs"><header className="page-header"><div><span className="eyebrow"><i/> FINANCE INTERNE</span><h1>Achats & dépenses</h1><p>Les achats fournisseurs, frais et charges de l’entreprise — séparés des factures de vos clients.</p></div><div className="form-actions">{rights.create&&<><button className="ghost-action" disabled={blocked||busy||!data} onClick={()=>{setSelected(null);setMode('PURCHASE')}}><ShoppingCart/>Demander un achat</button><button className="primary-btn compact" disabled={blocked||busy||!data} onClick={()=>{setSelected(null);setMode('EXPENSE')}}><Plus/>{tab==='ACHAT'?'Enregistrer un achat':'Nouvelle dépense'}</button></>}</div></header>
  {error&&!mode&&<p className="equipment-alert" role="alert">{error}</p>}{notice&&<p className="equipment-notice" role="status">{notice}</p>}
  <div className="cost-toolbar"><label>Devise des indicateurs<select value={currency} onChange={e=>setCurrency(e.target.value)}>{['GNF','EUR','USD'].map(c=><option key={c}>{c}</option>)}</select></label><label>Rechercher une charge<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="ghost-action" disabled={busy} onClick={()=>void run(async()=>{},'Registre actualisé.')}>Actualiser</button></div>
  {data&&<><div className="cost-kpis"><div className="panel"><Wallet/><span>Charges approuvées</span><strong>{money(total(approved),currency)}</strong><small>{approved.length} charge(s)</small></div><div className="panel"><span>À approuver</span><strong>{money(total(pending),currency)}</strong><small>Les charges refusées sont exclues</small></div><div className="panel"><span>Achats enregistrés</span><strong>{money(total(expenses.filter(e=>e.kind==='ACHAT'&&e.status!=='REFUSE')),currency)}</strong><small>Demandes non converties exclues</small></div></div><p className="muted">Une charge approuvée n’est pas une preuve de paiement. Les devis clients et les budgets d’achat ne sont pas additionnés aux dépenses.</p></>}
  <nav className="cost-tabs" aria-label="Registre des achats et dépenses">{[['DEPENSE','Dépenses & charges'],['ACHAT','Achats fournisseurs'],['REQUEST','Demandes d’achat']].map(([key,name])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key as typeof tab)}>{name}</button>)}</nav>
  {!data?<p>Chargement du registre…</p>:tab==='REQUEST'?<div className="cost-list">{data.purchases.filter(p=>p.currency===currency&&`${p.title} ${p.justification}`.toLowerCase().includes(search.toLowerCase())).map(p=><article className="panel cost-record" key={p.id}><div><strong>{p.title}</strong><p>{p.justification}</p><span className={`status ${statusTone(p.status)}`}>{statuses[p.status]||p.status}</span></div><b>{money(Number(p.estimated_cost),p.currency)}</b>{rights.update&&!blocked&&<div className="form-actions">{['EN_ATTENTE','BROUILLON'].includes(p.status)&&<><button disabled={busy} className="primary-btn compact" onClick={()=>void run(()=>companyPurchaseAction('APPROVE',{id:p.id}),'Achat approuvé.')}>Approuver</button><button disabled={busy} className="danger-btn" onClick={()=>void run(()=>companyPurchaseAction('REJECT',{id:p.id}),'Demande d’achat refusée.')}>Refuser</button></>}{p.status==='APPROUVE'&&<button className="ghost-action" disabled={busy} onClick={()=>{setPurchase(p);setMode('CONVERT')}}>Enregistrer la charge réelle</button>}</div>}</article>)}{!data.purchases.length&&<p className="panel cost-empty">Aucune demande d’achat enregistrée.</p>}</div>:<div className="cost-list">{rows.map(e=><article className="panel cost-record" key={e.id}><div><strong>{e.description}</strong><small>{e.category||'Autre'} · {e.spent_on} · {e.suppliers?.name||'Sans fournisseur renseigné'}</small><small>{e.reference||'Sans référence'}</small><span className={`status ${statusTone(e.status)}`}>{statuses[e.status]||e.status}</span></div><b>{money(Number(e.amount),e.currency)}</b><div className="form-actions"><button className="ghost-action" onClick={()=>{setSelected(e);setMode('EXPENSE')}}>{rights.update&&!blocked?'Voir / modifier':'Voir la fiche'}</button>{rights.update&&!blocked&&e.status==='BROUILLON'&&<button className="primary-btn compact" disabled={busy} onClick={()=>void run(()=>saveCompanyExpense(tenantOwnerId,{status:'APPROUVE'},e.id),'Charge approuvée.')}>Approuver</button>}</div></article>)}{!rows.length&&<p className="panel cost-empty">Aucune charge dans cette vue.</p>}</div>}
  {mode&&<div className="equipment-backdrop"><section className="equipment-dialog" role="dialog" aria-modal="true" aria-label={mode==='PURCHASE'?'Demande d’achat':mode==='CONVERT'?'Enregistrer la charge réelle':'Fiche achat ou dépense'}><div className="equipment-dialog-head"><h2>{mode==='PURCHASE'?'Demande d’achat':mode==='CONVERT'?'Enregistrer la charge réelle':selected?'Fiche achat ou dépense':'Nouvelle charge'}</h2><button className="icon-btn" disabled={busy} onClick={close} aria-label="Fermer la fiche de charge"><X/></button></div>{error&&<p className="equipment-alert" role="alert">{error}</p>}
   <form className="entity-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run(async()=>{
    const amount=Number(form.get('amount'));if(!Number.isFinite(amount)||amount<=0)throw new Error('Montant positif requis.');
    if(mode==='PURCHASE')await companyPurchaseAction('CREATE',{title:String(form.get('description')),justification:String(form.get('notes')),amount,currency:String(form.get('currency'))});
    else if(mode==='CONVERT')await companyPurchaseAction('CONVERT',{id:purchase!.id,amount,date:String(form.get('spent_on')),supplier_id:String(form.get('supplier_id')||''),project_id:String(form.get('project_id')||''),reference:String(form.get('reference')||'')});
    else await saveCompanyExpense(tenantOwnerId,{description:String(form.get('description')),kind:String(form.get('kind')) as 'ACHAT'|'DEPENSE',category:String(form.get('category')||'')||null,amount,currency:String(form.get('currency')),spent_on:String(form.get('spent_on')),supplier_id:String(form.get('supplier_id')||'')||null,project_id:String(form.get('project_id')||'')||null,reference:String(form.get('reference')||'')||null,notes:String(form.get('notes')||'')||null,...(selected?{status:String(form.get('status'))}: {})},selected?.id);
    setMode(null);setSelected(null);setPurchase(null);
   },'Opération enregistrée.');}}>
    <fieldset disabled={busy||blocked||(!!selected&&!rights.update)}><legend>Informations de l’opération</legend>{mode==='EXPENSE'&&<label>Type<select name="kind" defaultValue={selected?.kind||(tab==='ACHAT'?'ACHAT':'DEPENSE')}><option value="DEPENSE">Dépense / charge interne</option><option value="ACHAT">Achat fournisseur</option></select></label>}<label>Objet / description<input name="description" required defaultValue={selected?.description||purchase?.title||''} readOnly={mode==='CONVERT'}/></label><label>Montant {mode==='CONVERT'?'réel':'prévu'}<input name="amount" type="number" min="0.01" step="0.01" required defaultValue={selected?.amount||purchase?.estimated_cost||''}/></label><label>Devise<select name="currency" defaultValue={selected?.currency||purchase?.currency||currency} disabled={mode==='CONVERT'}>{['GNF','EUR','USD'].map(c=><option key={c}>{c}</option>)}</select></label>
     {mode!=='PURCHASE'&&<><label>Date de la charge<input name="spent_on" type="date" required defaultValue={selected?.spent_on||new Date().toISOString().slice(0,10)}/></label><label>Fournisseur<select name="supplier_id" defaultValue={selected?.supplier_id||''}><option value="">Sans fournisseur</option>{selected?.supplier_id&&!data?.suppliers.some(s=>s.id===selected.supplier_id)&&<option value={selected.supplier_id}>{selected.suppliers?.name||'Fournisseur enregistré'}</option>}{data?.suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Projet / centre de coûts<select name="project_id" defaultValue={selected?.project_id||''}><option value="">Frais généraux</option>{selected?.project_id&&!data?.projects.some(p=>p.id===selected.project_id)&&<option value={selected.project_id}>Projet enregistré</option>}{data?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Référence facture fournisseur / reçu<input name="reference" defaultValue={selected?.reference||''}/></label></>}
     {mode==='EXPENSE'&&<label>Catégorie<input name="category" list="company-cost-categories" defaultValue={selected?.category||''}/><datalist id="company-cost-categories">{['Loyer','Salaires','Transport','Internet & téléphone','Électricité','Abonnements logiciels','Achat matériel','Prestations fournisseurs','Autre'].map(c=><option key={c}>{c}</option>)}</datalist></label>}
     {mode!=='CONVERT'&&<label>{mode==='PURCHASE'?'Justification de l’achat':'Notes'}<textarea name="notes" required={mode==='PURCHASE'} defaultValue={selected?.notes||''}/></label>}{selected&&<label>Validation<select name="status" defaultValue={selected.status}>{Object.entries(statuses).filter(([s])=>['BROUILLON','APPROUVE','REFUSE'].includes(s)||s===selected.status).map(([s,name])=><option key={s} value={s}>{name}</option>)}</select></label>}
    </fieldset>{(!selected?rights.create||mode==='CONVERT':rights.update)&&!blocked&&<button className="primary-btn" disabled={busy}>{busy?'Enregistrement…':'Enregistrer'}</button>}{selected&&rights.delete&&!selected.source_purchase_id&&!blocked&&<button type="button" className="danger-btn" disabled={busy} onClick={()=>{if(confirm('Supprimer cette charge du registre ?'))void run(async()=>{await deleteCompanyExpense(tenantOwnerId,selected.id);setMode(null);setSelected(null)},'Charge supprimée.')}}>Supprimer la charge</button>}
   </form>
  </section></div>}
 </section>
}
