import{useEffect,useRef,useState,type FormEvent}from'react'
import type{CreativeApproval}from'./types/models'
import{addCreativeAnnotation,listCreativeAnnotations,type Annotation}from'./services/agencyWorkflow'
import './agency-workflow.css'
export default function CreativeReview({approval,canComment=false,previous}:{approval:CreativeApproval;canComment?:boolean;previous?:CreativeApproval}){
 const[rows,setRows]=useState<Annotation[]>([]),[point,setPoint]=useState<{x:number;y:number}|null>(null),[time,setTime]=useState<number|null>(null),[body,setBody]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[compare,setCompare]=useState(false);const video=useRef<HTMLVideoElement>(null)
 useEffect(()=>{let active=true;void listCreativeAnnotations(approval.id).then(data=>{if(active)setRows(data)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[approval.id])
 const editable=canComment&&approval.status==='A_VALIDER';const isVideo=/VIDEO|REEL/i.test(approval.asset_type),safeUrl=approval.asset_url&&/^https?:\/\//i.test(approval.asset_url)?approval.asset_url:null
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!editable||busy||!body.trim())return;setBusy(true);setError('');try{const result=await addCreativeAnnotation(approval.id,body,point?.x??null,point?.y??null,time);setRows(current=>[...current,result]);setBody('');setPoint(null);setTime(null)}catch(e){setError(e instanceof Error?e.message:'Annotation non envoyée. Votre texte est conservé.')}finally{setBusy(false)}}
 return <section className="agency-workflow" aria-label={`Commentaires visuels version ${approval.version}`}><h4>Commentaires sur la version {approval.version}</h4>{safeUrl&&isVideo?<><video className="annotation-video" ref={video} src={safeUrl} controls/>{editable&&<button type="button" onClick={()=>{setTime(Math.round((video.current?.currentTime||0)*10)/10);setPoint(null)}}>Commenter ce moment de la vidéo</button>}</>:safeUrl&&!/DOCUMENT/i.test(approval.asset_type)&&<div className="annotation-image" onClick={e=>{if(!editable)return;const rect=e.currentTarget.getBoundingClientRect();setPoint({x:Math.min(1,Math.max(0,(e.clientX-rect.left)/rect.width)),y:Math.min(1,Math.max(0,(e.clientY-rect.top)/rect.height))});setTime(null)}}><img src={safeUrl} alt={approval.title}/>{rows.filter(row=>row.x!==null&&row.y!==null).map((row,index)=><span className="annotation-pin" title={row.body} style={{left:`${Number(row.x)*100}%`,top:`${Number(row.y)*100}%`}} key={row.id}>{index+1}</span>)}{point&&<span className="annotation-pin" style={{left:`${point.x*100}%`,top:`${point.y*100}%`}}>+</span>}</div>}{editable&&<form onSubmit={submit}><p>{point?'Position sélectionnée sur le visuel.':time!==null?`Moment sélectionné : ${time} secondes.`:'Cliquez sur le visuel pour placer un commentaire, ou écrivez un commentaire général.'}</p><label>Votre commentaire<textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} required rows={3}/></label><button disabled={busy||!body.trim()}>{busy?'Envoi…':'Enregistrer le commentaire'}</button><button type="button" onClick={()=>{setPoint(null);setTime(null)}}>Commentaire général</button></form>}{error&&<p role="alert">{error}</p>}<ol className="annotation-comments">{rows.map(row=><li key={row.id}><small>{row.time_seconds!==null?`Vidéo : ${row.time_seconds} s`:row.x!==null?'Repère sur le visuel':'Commentaire général'} · {new Date(row.created_at).toLocaleString('fr-FR')}</small><p>{row.body}</p></li>)}</ol>{previous&&<><button type="button" onClick={()=>setCompare(!compare)}>{compare?'Masquer':'Comparer avec'} la version {previous.version}</button>{compare&&<div className="agency-form-grid"><article><strong>Version {previous.version}</strong><p>{previous.description}</p>{previous.asset_url&&/^https?:\/\//i.test(previous.asset_url)&&!/VIDEO|REEL|DOCUMENT/i.test(previous.asset_type)&&<img style={{width:'100%'}} src={previous.asset_url} alt="Version précédente"/>}</article><article><strong>Version {approval.version}</strong><p>{approval.description}</p>{safeUrl&&!/VIDEO|REEL|DOCUMENT/i.test(approval.asset_type)&&<img style={{width:'100%'}} src={safeUrl} alt="Version actuelle"/>}</article></div>}</>}</section>
}
