import { useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import type { EditorialItem } from './types/models'
import { statusTone } from './lib/statusTone'
import './editorial-calendar.css'

const days=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim']
const dayKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
const dateOf=(item:EditorialItem)=>item.publish_at?new Date(item.publish_at):null
const validDate=(item:EditorialItem)=>{const date=dateOf(item);return date&&!Number.isNaN(date.getTime())?date:null}
const shortStatus=(status:string)=>({A_REDIGER:'À rédiger',EN_CREATION:'En création',A_VALIDER:'À valider',VALIDE_CLIENT:'Validé',PLANIFIE:'Planifié',PUBLIE:'Publié',REPORTE:'Reporté'} as Record<string,string>)[status]||status.replaceAll('_',' ')

export default function EditorialCalendar({items,onSelect}:{items:EditorialItem[];onSelect:(item:EditorialItem)=>void}){
  const [anchor,setAnchor]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1))
  const [view,setView]=useState<'MONTH'|'WEEK'>('MONTH')
  const [selectedDay,setSelectedDay]=useState<string|null>(null)
  const today=dayKey(new Date())
  const start=useMemo(()=>{const date=new Date(anchor.getFullYear(),anchor.getMonth(),view==='MONTH'?1:anchor.getDate());date.setDate(date.getDate()-(date.getDay()+6)%7);return date},[anchor,view])
  const cells=useMemo(()=>Array.from({length:view==='MONTH'?42:7},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return date}),[start,view])
  const byDay=useMemo(()=>{const map=new Map<string,EditorialItem[]>();for(const item of items){const date=validDate(item);if(!date)continue;const key=dayKey(date);map.set(key,[...(map.get(key)||[]),item])}for(const entries of map.values())entries.sort((a,b)=>(a.publish_at||'').localeCompare(b.publish_at||''));return map},[items])
  const visible=useMemo(()=>items.filter(item=>{const date=validDate(item);return date&&(view==='MONTH'?date.getFullYear()===anchor.getFullYear()&&date.getMonth()===anchor.getMonth():date>=start&&date<new Date(start.getFullYear(),start.getMonth(),start.getDate()+7))}).sort((a,b)=>(a.publish_at||'').localeCompare(b.publish_at||'')),[items,anchor,start,view])
  const agenda=selectedDay?byDay.get(selectedDay)||[]:visible
  const move=(amount:number)=>{setSelectedDay(null);setAnchor(current=>view==='MONTH'?new Date(current.getFullYear(),current.getMonth()+amount,1):new Date(current.getFullYear(),current.getMonth(),current.getDate()+amount*7))}
  const selectDate=(date:Date)=>{setSelectedDay(dayKey(date));if(view==='MONTH'&&date.getMonth()!==anchor.getMonth())setAnchor(new Date(date.getFullYear(),date.getMonth(),1))}
  return <section className="panel editorial-month-calendar" aria-label="Calendrier des publications">
    <div className="editorial-calendar-toolbar"><div><span className="eyebrow"><i/> CALENDRIER ÉDITORIAL</span><h2>{anchor.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</h2><p>{visible.length} publication{visible.length>1?'s':''} sur cette période</p></div><div className="editorial-calendar-controls"><button type="button" className="editorial-today" onClick={()=>{const now=new Date();setAnchor(new Date(now.getFullYear(),now.getMonth(),now.getDate()));setSelectedDay(today)}}>Aujourd’hui</button><button type="button" className="icon-btn" aria-label="Période précédente" onClick={()=>move(-1)}><ChevronLeft/></button><button type="button" className="icon-btn" aria-label="Période suivante" onClick={()=>move(1)}><ChevronRight/></button><div className="segmented"><button type="button" className={view==='MONTH'?'active':''} onClick={()=>{setView('MONTH');setSelectedDay(null)}}>Mois</button><button type="button" className={view==='WEEK'?'active':''} onClick={()=>{setView('WEEK');setSelectedDay(null)}}>Semaine</button></div></div></div>
    <div className="editorial-calendar-layout"><div className="editorial-calendar-grid"><div className="editorial-calendar-days">{days.map(day=><strong key={day}>{day}</strong>)}</div><div className={`editorial-calendar-cells ${view==='WEEK'?'week':''}`}>{cells.map(date=>{const key=dayKey(date),entries=byDay.get(key)||[];return <div className={`editorial-calendar-day ${date.getMonth()!==anchor.getMonth()&&view==='MONTH'?'outside':''} ${selectedDay===key?'selected':''} ${key===today?'today':''}`} key={key}><button type="button" className="editorial-day-number" onClick={()=>selectDate(date)} aria-label={`${date.toLocaleDateString('fr-FR',{dateStyle:'full'})}, ${entries.length} publication(s)`}><time dateTime={key}>{date.getDate()}</time>{entries.length>0&&<span className="editorial-day-count">{entries.length}</span>}</button><div className="editorial-calendar-posts">{entries.slice(0,3).map(item=><button type="button" key={item.id} className={`editorial-calendar-post ${statusTone(item.status)}`} onClick={()=>onSelect(item)} title={`${item.title} — ${item.clients?.name||'Sans client'}`}><span className="editorial-post-label">{item.post_type||item.content_type||shortStatus(item.status)}</span><strong>{item.title}{item.canva_design_id&&<span className="editorial-canva-tag"> · Canva</span>}</strong><small>{dateOf(item)?.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})} · {item.clients?.name||'Sans client'}</small></button>)}{entries.length>3&&<button type="button" className="editorial-more" onClick={()=>selectDate(date)}>+ {entries.length-3} autres</button>}</div></div>})}</div></div>
    <aside className="editorial-calendar-agenda"><div className="editorial-agenda-head"><div><span className="eyebrow"><i/> PUBLICATIONS</span><h3>{selectedDay?new Date(`${selectedDay}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'}):'Sur cette période'}</h3></div>{selectedDay&&<button type="button" onClick={()=>setSelectedDay(null)}>Tout voir</button>}</div><div className="editorial-agenda-list">{agenda.length?agenda.map(item=><button type="button" className="editorial-agenda-item" key={item.id} onClick={()=>onSelect(item)}><span className="editorial-agenda-visual">{item.asset_urls?.[0]?<img src={item.asset_urls[0]} alt="" loading="lazy"/>:<span>{(item.post_type||item.title).slice(0,1).toUpperCase()}</span>}</span><span className="editorial-agenda-copy"><small>{validDate(item)?.toLocaleDateString('fr-FR',{day:'numeric',month:'short'})} · {validDate(item)?.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small><strong>{item.title}{item.canva_design_id&&<span className="editorial-canva-tag"> · Canva</span>}</strong><em>{item.clients?.name||'Sans client'} · {(item.platforms?.length?item.platforms:[item.platform]).filter(Boolean).join(', ')||'Sans réseau'}</em><span className={`status ${statusTone(item.status)}`}>{shortStatus(item.status)}</span></span></button>):<p className="editorial-agenda-empty">Aucune publication pour cette sélection.</p>}</div></aside></div>
    <p className="editorial-calendar-note">Sélectionnez un jour pour voir ses publications, puis une carte pour ouvrir le contenu complet.</p>
  </section>
}
