import { useMemo, useState } from 'react'
import { FileSpreadsheet, Upload, X } from 'lucide-react'
import { googleSheetCsvUrl } from './lib/contactImport'
import { editorialFromCsv, editorialFromFile, type EditorialImportRow } from './lib/editorialImport'
import { statusTone } from './lib/statusTone'
import { createEditorialItemsBatch } from './services/repository'
import type { Client, EditorialItem, Project } from './types/models'
import './editorial-import.css'

const normalized=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase()

export default function EditorialImportPanel({clients,projects,existing,onImported}:{clients:Client[];projects:Project[];existing:EditorialItem[];onImported:(count:number)=>void}){
  const[open,setOpen]=useState(false),[rows,setRows]=useState<EditorialImportRow[]>([]),[source,setSource]=useState(''),[sheetUrl,setSheetUrl]=useState(''),[defaultClient,setDefaultClient]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const analyzed=useMemo(()=>rows.map(row=>{
    const clientName=row.client.trim(),client=clientName?clients.find(item=>normalized(item.name)===normalized(clientName)):clients.find(item=>item.id===defaultClient)
    const projectName=row.project.trim(),project=projectName?projects.find(item=>normalized(item.name)===normalized(projectName)&&(!client||item.client_id===client.id)):null
    const duplicate=existing.some(item=>item.client_id===client?.id&&normalized(item.title)===normalized(row.title)&&item.publish_at?.slice(0,10)===row.publish_at.slice(0,10))
    const issues=[row.error,!client?'Choisissez un client existant':'',clientName&&!client?`Client inconnu : ${clientName}`:'',projectName&&!project?`Projet inconnu : ${projectName}`:'',duplicate?'Publication déjà présente pour ce client et cette date':''].filter(Boolean)
    return {...row,clientId:client?.id||null,projectId:project?.id||null,issue:issues.join(' · ')}
  }),[rows,clients,projects,existing,defaultClient])
  const invalid=analyzed.filter(row=>row.issue).length
  const fromFile=async(file:File)=>{setBusy(true);setError('');try{setRows(await editorialFromFile(file));setSource(file.name);setOpen(true)}catch(cause){setError(cause instanceof Error?cause.message:'Lecture du fichier impossible.');setOpen(true)}finally{setBusy(false)}}
  const fromSheet=async()=>{setBusy(true);setError('');try{const response=await fetch(googleSheetCsvUrl(sheetUrl));if(!response.ok)throw new Error('Partagez la feuille Google en lecture puis réessayez.');setRows(editorialFromCsv(await response.text()));setSource('Google Sheets');setOpen(true)}catch(cause){setError(cause instanceof Error?cause.message:'Import Google Sheets impossible.');setOpen(true)}finally{setBusy(false)}}
  const confirm=async()=>{if(!analyzed.length||invalid||busy)return;setBusy(true);setError('');try{const count=await createEditorialItemsBatch(analyzed.map(row=>({title:row.title,publish_at:row.publish_at,platform:row.platforms[0]||null,platforms:row.platforms,content_type:row.content_type,caption:row.caption,client_id:row.clientId,project_id:row.projectId,status:row.status,theme:row.theme,post_type:row.post_type,objective:row.objective,visual_title:row.visual_title,visual_subtitle:row.visual_subtitle,hashtags:row.hashtags,production_notes:row.production_notes,week_label:row.week_label})));onImported(count);setOpen(false);setRows([]);setSource('')}catch(cause){setError(cause instanceof Error?cause.message:'Enregistrement impossible. Aucune ligne n’a été importée.')}finally{setBusy(false)}}
  return <>
    <button type="button" className="ghost-action" onClick={()=>setOpen(true)}><FileSpreadsheet/>Importer un calendrier</button>
    {open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><section className="modal editorial-import-modal" role="dialog" aria-modal="true" aria-label="Importer un calendrier éditorial" onMouseDown={event=>event.stopPropagation()}>
      <div className="modal-head"><div><span className="eyebrow"><i/> STUDIO ÉDITORIAL</span><h2>Importer votre calendrier</h2></div><button type="button" className="icon-btn" onClick={()=>setOpen(false)} aria-label="Fermer"><X/></button></div>
      <p>Remplissez le modèle Excel ou CSV, puis vérifiez l’aperçu avant de créer les publications. Date et titre sont obligatoires ; les noms de clients et projets doivent exister dans votre espace.</p>
      <div className="editorial-import-sources"><a className="ghost-action" href={`${import.meta.env.BASE_URL}templates/modele-calendrier-editorial-smartsell.xlsx`} download><FileSpreadsheet/> Télécharger le modèle Excel</a><a className="ghost-action" href={`${import.meta.env.BASE_URL}templates/modele-calendrier-editorial-smartsell.csv`} download>Modèle CSV</a><label className="ghost-action upload-label"><Upload/>{busy?'Lecture…':'Choisir CSV / Excel'}<input type="file" accept=".csv,.xlsx,text/csv" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void fromFile(file);event.currentTarget.value=''}}/></label></div>
      <div className="editorial-sheet-input"><label>Lien Google Sheets — onglet sélectionné<input value={sheetUrl} onChange={event=>setSheetUrl(event.target.value)} placeholder="https://docs.google.com/spreadsheets/d/…#gid=…"/></label><button type="button" className="ghost-action" disabled={!sheetUrl||busy} onClick={()=>void fromSheet()}>Prévisualiser</button></div>
      <p className="editorial-import-hint">Pour importer tous les onglets d’un coup, téléchargez le Sheet au format Excel (.xlsx) puis choisissez ce fichier. Un lien Google Sheets importe l’onglet indiqué par son URL.</p>
      <label className="editorial-default-client">Client de ce calendrier (obligatoire)<select value={defaultClient} onChange={event=>setDefaultClient(event.target.value)}><option value="">Choisir un client</option>{clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></label>
      {error&&<div className="error-banner" role="alert">{error}</div>}
      {rows.length>0&&<><div className="editorial-import-summary"><strong>{rows.length} ligne(s) · {invalid?`${invalid} à corriger`:'prêtes à importer'}</strong><span>{source}</span></div><div className="editorial-import-preview"><table><thead><tr><th>Onglet / ligne</th><th>Publication</th><th>Date</th><th>Réseaux</th><th>Client / projet</th><th>État à importer</th><th>Action</th></tr></thead><tbody>{analyzed.map((row,index)=><tr key={`${row.sheet}-${row.line}-${index}`}><td>{row.sheet}<small>ligne {row.line}</small></td><td><strong>{row.title||'—'}</strong><small>{row.theme}{row.objective?` · ${row.objective}`:''}</small><small>{row.caption.slice(0,100)}</small></td><td><input type="datetime-local" aria-label={`Date ligne ${row.line}`} value={row.publish_at?new Date(row.publish_at).toISOString().slice(0,16):''} onChange={event=>setRows(current=>current.map((item,i)=>i===index?{...item,publish_at:event.target.value?new Date(event.target.value).toISOString():'',error:item.error?.replace('Date invalide ou manquante','').replace(/ · $/,'')||null}:item))}/></td><td>{row.platforms.join(', ')||'—'}</td><td>{row.client||clients.find(c=>c.id===defaultClient)?.name||'—'}{row.project?` · ${row.project}`:''}</td><td><select aria-label={`État ligne ${row.line}`} value={row.status} onChange={event=>setRows(current=>current.map((item,i)=>i===index?{...item,status:event.target.value,error:item.error?.replace('Statut inconnu','').replace(/ · $/,'')||null}:item))}>{['A_REDIGER','EN_CREATION','A_VALIDER','PLANIFIE','PUBLIE','REPORTE'].map(status=><option key={status} value={status}>{status.replaceAll('_',' ')}</option>)}</select><span className={`status ${row.issue?'danger':statusTone(row.status)}`}>{row.issue||'Prêt'}</span></td><td><button type="button" className="ghost-action" onClick={()=>setRows(current=>current.filter((_,i)=>i!==index))}>Exclure</button></td></tr>)}</tbody></table></div><div className="form-actions"><button type="button" className="ghost-action" onClick={()=>setRows([])}>Remplacer le fichier</button><button type="button" className="primary-btn compact" disabled={invalid>0||busy} onClick={()=>void confirm()}>{busy?'Import en cours…':`Importer ${rows.length} publication(s)`}</button></div></>}
    </section></div>}
  </>
}
