import {useEffect,useRef,useState} from 'react'
import {Camera,ClipboardCheck,Plus,RefreshCw,X} from 'lucide-react'
import {loadEquipmentWorkspace,configureEquipmentReviewer,submitEquipmentRequest,decideEquipmentRequest,checkoutEquipmentRequest,returnEquipmentRequest,uploadEquipmentPhoto,getEquipmentPhotoUrl,discardEquipmentPhotos,validateEquipmentPhoto,type EquipmentWorkspace,type EquipmentRequest,type EquipmentEvidence} from './services/equipmentRequests'
import './equipmentRequests.css'
const labels:Record<string,string>={EN_ATTENTE:'En attente',APPROUVEE:'Approuvée · matériel réservé',REFUSEE:'Refusée',SORTIE:'Matériel sorti',RETOUR_PARTIEL:'Retour partiel',RETOURNEE:'Tout retourné',CONFORME:'Conforme au départ',DEGRADE:'Dégradé · maintenance',HORS_SERVICE:'Hors service'}
const formatDate=(value:string)=>new Date(value).toLocaleString('fr-FR',{timeZone:'Africa/Conakry',dateStyle:'short',timeStyle:'short'})
type EvidenceDraft={selected:boolean;notes:string;condition:string;files:File[];paths:string[]}
function Photos({paths}:{paths:string[]}){
 const [urls,setUrls]=useState<string[]>([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;Promise.all(paths.map(getEquipmentPhotoUrl)).then(result=>{if(active)setUrls(result)}).catch(()=>{if(active)setError('Photos momentanément indisponibles. Rouvrez le bon pour réessayer.')});return()=>{active=false}},[paths]);
 return <div className="equipment-photos">{urls.map((url,index)=><a key={paths[index]} href={url} target="_blank" rel="noreferrer"><img src={url} alt={`Photo de constat ${index+1}`} loading="lazy"/></a>)}{error&&<small role="alert">{error}</small>}</div>
}
export default function EquipmentRequests({tenantOwnerId,blocked=false}:{tenantOwnerId:string;blocked?:boolean}){
 const [workspace,setWorkspace]=useState<EquipmentWorkspace|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[selected,setSelected]=useState<EquipmentRequest|null>(null),[stage,setStage]=useState<'OUT'|'IN'|null>(null),[draft,setDraft]=useState<Record<string,EvidenceDraft>>({}),[decisionNotes,setDecisionNotes]=useState(''),[filter,setFilter]=useState('ALL'),[chosen,setChosen]=useState<string[]>([]);
 const lock=useRef(false);
 const load=async()=>{const data=await loadEquipmentWorkspace();setWorkspace(data);setSelected(old=>old?data.requests.find(r=>r.id===old.id)||null:null)};
 useEffect(()=>{let active=true;const refresh=()=>{loadEquipmentWorkspace().then(data=>{if(active){setWorkspace(data);setSelected(old=>old?data.requests.find(r=>r.id===old.id)||null:null)}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Chargement impossible')})};refresh();const timer=window.setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh)}},[tenantOwnerId]);
 const run=async(action:()=>Promise<unknown>,message:string)=>{if(lock.current||blocked)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await action();setNotice(message);try{await load()}catch{setError('Action enregistrée, mais actualisation impossible. Actualisez avant de réessayer.')}}catch(reason){setError((reason instanceof Error?reason.message:'Action impossible')+' Si la connexion a été interrompue, actualisez avant de réessayer.')}finally{lock.current=false;setBusy(false)}};
 const startEvidence=(kind:'OUT'|'IN')=>{if(!selected)return;setDraft(Object.fromEntries(selected.items.filter(i=>kind==='OUT'||!i.returned_at).map(i=>[i.equipment_id,{selected:kind==='OUT',notes:kind==='OUT'?(workspace?.equipment.find(e=>e.id===i.equipment_id)?.condition||''):'',condition:'CONFORME',files:[],paths:[]}])));setStage(kind)};
 const evidenceSubmit=async()=>{if(!selected||!stage)return;const items:EquipmentEvidence[]=[];
  for(const [id,item] of Object.entries(draft).filter(([,d])=>d.selected)){
   if(!item.notes.trim())throw new Error('Renseignez les observations pour chaque matériel.');
   if(item.files.length+item.paths.length<1||item.files.length+item.paths.length>5)throw new Error('Ajoutez entre 1 et 5 photos par matériel.');
   while(item.files.length){const file=item.files[0];const path=await uploadEquipmentPhoto(tenantOwnerId,selected.id,id,stage,file);item.paths.push(path);item.files.shift();setDraft(old=>({...old,[id]:{...item,paths:[...item.paths],files:[...item.files]}}))}
   items.push({equipment_id:id,notes:item.notes.trim(),photos:item.paths,condition:item.condition});
  }
  if(!items.length)throw new Error('Sélectionnez au moins un matériel retourné.');
  if(stage==='OUT')await checkoutEquipmentRequest(selected.id,items);else await returnEquipmentRequest(selected.id,items);setStage(null);setDraft({});
 };
 const close=()=>{if(busy)return;const paths=Object.values(draft).flatMap(d=>d.paths);if(paths.length)void discardEquipmentPhotos(paths).catch(()=>{});setStage(null);setSelected(null);setOpen(false);setDraft({});setError('')};
 const rows=workspace?.requests.filter(r=>filter==='ALL'||r.status===filter)||[];
 return <section className="equipment-requests">
  <header className="page-header"><div><span className="eyebrow"><i/> SORTIES & RETOURS</span><h1>Demandes matériel</h1><p>Demander, valider, remettre et contrôler le retour — avec photos privées de chaque équipement.</p></div><div className="form-actions"><button className="ghost-action" disabled={busy} onClick={()=>void run(async()=>{},'Liste actualisée.')}><RefreshCw/>Actualiser</button>{workspace?.can_request&&<button className="primary-btn compact" disabled={busy||blocked} onClick={()=>{setChosen([]);setOpen(true)}}><Plus/>Demander un bon de sortie</button>}</div></header>
  {error&&!open&&!selected&&<p className="equipment-alert" role="alert">{error}</p>}{notice&&<p role="status" className="equipment-notice">{notice}</p>}
  {!workspace?<p>Chargement des demandes…</p>:<>
   <div className="panel equipment-routing"><ClipboardCheck/><div><strong>Responsable : {workspace.reviewer_name||'propriétaire uniquement'}</strong><p>Le propriétaire reçoit une copie. Une validation suffit ; le propriétaire peut annuler une approbation avant la remise.</p></div>{workspace.can_configure&&<label>Responsable matériel<select aria-label="Responsable matériel" disabled={busy||blocked} value={workspace.reviewer_id||''} onChange={event=>{const value=event.target.value;void run(()=>configureEquipmentReviewer(value||null),'Responsable enregistré.')}}><option value="">Propriétaire uniquement</option>{workspace.staff.filter(p=>p.id!==tenantOwnerId).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>}</div>
   <div className="equipment-kpis">{['EN_ATTENTE','APPROUVEE','SORTIE','RETOUR_PARTIEL'].map(status=><div className={`panel equipment-state state-${status}`} key={status}><b>{workspace.requests.filter(r=>r.status===status).length}</b><span>{labels[status]}</span></div>)}</div>
   <label className="equipment-filter">Afficher<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">Toutes mes demandes accessibles</option>{Object.entries(labels).filter(([key])=>!['CONFORME','DEGRADE','HORS_SERVICE'].includes(key)).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label>
   <div className="equipment-request-list">{rows.map(r=><button className="panel equipment-request-card" key={r.id} onClick={()=>{setSelected(r);setDecisionNotes('');setError('')}}><span className={`equipment-state state-${r.status}`}>{labels[r.status]}</span><strong>{r.reason}</strong><span>{r.requester_name} · {r.items.length} équipement(s)</span><small>Bon {r.id.slice(0,8)} · {r.destination}</small><small>Retour attendu : {formatDate(r.expected_return_at)}</small>{['SORTIE','RETOUR_PARTIEL'].includes(r.status)&&Date.parse(r.expected_return_at)<Date.now()&&<b className="equipment-alert">Retour en retard</b>}</button>)}{!rows.length&&<div className="panel equipment-empty">Aucune demande à afficher. Les collaborateurs voient leurs demandes ; les responsables voient les demandes de leur entreprise.</div>}</div>
  </>}
  {(open||selected)&&<div className="equipment-backdrop"><section className="equipment-dialog" role="dialog" aria-modal="true" aria-label={open?'Demander un bon de sortie':'Bon de sortie et de retour'}><div className="equipment-dialog-head"><h2>{open?'Demander un bon de sortie':stage==='OUT'?'Remise du matériel':stage==='IN'?'Contrôle du retour':'Bon de sortie et de retour'}</h2><button type="button" className="icon-btn" aria-label="Fermer le bon" disabled={busy} onClick={close}><X/></button></div>{error&&<p className="equipment-alert" role="alert">{error}</p>}
   {open&&<form className="entity-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run(async()=>{if(!chosen.length)throw new Error('Sélectionnez du matériel.');await submitEquipmentRequest({reason:String(form.get('reason')),destination:String(form.get('destination')),returnAt:new Date(String(form.get('return_at'))+'Z').toISOString(),equipment:chosen});setOpen(false)},'Demande transmise au responsable et au propriétaire.')}}>
    <label>Motif / mission<input name="reason" required maxLength={2000}/></label><label>Lieu / destination<input name="destination" required maxLength={500}/></label><label>Retour prévu (heure de Conakry)<input type="datetime-local" name="return_at" required/></label><fieldset><legend>Matériel demandé — une unité par référence</legend>{workspace?.equipment.map(e=><label className="equipment-checkbox" key={e.id}><input type="checkbox" checked={chosen.includes(e.id)} disabled={!e.available||busy} onChange={event=>setChosen(old=>event.target.checked?[...old,e.id]:old.filter(id=>id!==e.id))}/><span><strong>{e.name}</strong><small>{e.code} · {e.available?'Disponible':'Indisponible ou réservé'}</small></span></label>)}</fieldset><button className="primary-btn" disabled={busy||blocked||!chosen.length}>{busy?'Enregistrement…':'Transmettre la demande'}</button>
   </form>}
   {selected&&!stage&&<><div className="equipment-bon-summary"><span className={`equipment-state state-${selected.status}`}>{labels[selected.status]}</span><strong>Bon {selected.id.slice(0,8)}</strong><p>{selected.requester_name} · {selected.reason}</p><p>{selected.destination} · Retour prévu : {formatDate(selected.expected_return_at)}</p>{selected.decision_at&&<p>Décision : {selected.decision_name} · {formatDate(selected.decision_at)}<br/>{selected.decision_notes}</p>}</div>
    {selected.items.map(item=><article className="panel equipment-condition" key={item.id}><h3>{item.equipment_code} · {item.equipment_name}</h3><div className="equipment-comparison"><div><h4><Camera/>Au départ</h4><p>{item.condition_out||'Remise non enregistrée'}</p><Photos paths={item.condition_out_photos}/></div><div><h4><Camera/>Au retour</h4><span className={`equipment-state state-${item.return_condition||'EN_ATTENTE'}`}>{item.return_condition?labels[item.return_condition]:'Pas encore retourné'}</span><p>{item.condition_in||'—'}</p>{item.returned_at&&<small>{formatDate(item.returned_at)}</small>}<Photos paths={item.condition_in_photos}/></div></div></article>)}
    {workspace?.can_review&&!blocked&&<div className="entity-form">{(selected.status==='EN_ATTENTE'||(workspace.can_configure&&selected.status==='APPROUVEE'))&&<><label>Note de décision / motif de refus<textarea value={decisionNotes} maxLength={2000} onChange={e=>setDecisionNotes(e.target.value)}/></label><div className="form-actions">{selected.status==='EN_ATTENTE'&&<button className="primary-btn compact" disabled={busy} onClick={()=>void run(()=>decideEquipmentRequest(selected.id,true,decisionNotes),'Demande approuvée ; matériel réservé.')}>Approuver</button>}<button className="danger-btn" disabled={busy||!decisionNotes.trim()} onClick={()=>void run(()=>decideEquipmentRequest(selected.id,false,decisionNotes),'Demande refusée.')}>{selected.status==='APPROUVEE'?'Annuler l’approbation':'Refuser'}</button></div></>}{selected.status==='APPROUVEE'&&<button className="primary-btn" disabled={busy} onClick={()=>startEvidence('OUT')}>Enregistrer la remise + photos</button>}{['SORTIE','RETOUR_PARTIEL'].includes(selected.status)&&<button className="primary-btn" disabled={busy} onClick={()=>startEvidence('IN')}>Enregistrer un retour + photos</button>}</div>}
   </>}
   {selected&&stage&&<form className="entity-form" onSubmit={event=>{event.preventDefault();void run(evidenceSubmit,stage==='OUT'?'Bon de sortie enregistré avec photos.':'Bon de retour enregistré avec comparaison des états.')}}><p>{stage==='OUT'?'La sortie devient effective seulement après ce contrôle.':'Sélectionnez les équipements revenus. Ceux qui manquent restent en mission.'} 1 à 5 photos JPG, PNG ou WebP, 5 Mo maximum par photo.</p>{selected.items.filter(i=>draft[i.equipment_id]).map(item=>{const d=draft[item.equipment_id];const update=(patch:Partial<EvidenceDraft>)=>setDraft(old=>({...old,[item.equipment_id]:{...old[item.equipment_id],...patch}}));return <fieldset key={item.id}><legend>{item.equipment_code} · {item.equipment_name}</legend>{stage==='IN'&&<><label className="equipment-checkbox"><input type="checkbox" checked={d.selected} disabled={busy} onChange={e=>update({selected:e.target.checked})}/>Ce matériel est revenu</label><p>État au départ : {item.condition_out}</p><Photos paths={item.condition_out_photos}/></>}{d.selected&&<>{stage==='IN'&&<label>Comparaison avec l’état au départ<select value={d.condition} disabled={busy} onChange={e=>update({condition:e.target.value})}>{['CONFORME','DEGRADE','HORS_SERVICE'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>}<label>Observations {stage==='OUT'?'au départ':'au retour'}<textarea required maxLength={2000} disabled={busy} value={d.notes} onChange={e=>update({notes:e.target.value})}/></label><label>Photos {stage==='OUT'?'au départ':'au retour'}<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy||d.paths.length>0} onChange={event=>{try{const files=Array.from(event.target.files||[]);if(files.length+d.paths.length>5)throw new Error('Maximum 5 photos par matériel');files.forEach(validateEquipmentPhoto);update({files});setError('')}catch(reason){event.target.value='';update({files:[]});setError(reason instanceof Error?reason.message:'Photo invalide')}}}/></label><small>{d.files.length} photo(s) à charger · {d.paths.length} chargée(s)</small></>}</fieldset>})}<div className="form-actions"><button type="button" className="ghost-action" disabled={busy} onClick={()=>{const paths=Object.values(draft).flatMap(d=>d.paths);void discardEquipmentPhotos(paths).catch(()=>{});setDraft({});setStage(null)}}>Annuler</button><button className="primary-btn compact" disabled={busy||blocked}>{busy?'Photos et enregistrement…':stage==='OUT'?'Confirmer la sortie':'Confirmer le retour'}</button></div></form>}
  </section></div>}
 </section>
}
