import { useState } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { ArrowRight, BellRing, CalendarDays, Check, ChevronLeft, ChevronRight, KanbanSquare, Megaphone, MessageSquareText, Sparkles } from 'lucide-react'
import './innovation-showcase.css'

type Language = 'fr' | 'en'
type Scene = 'tasks' | 'editorial' | 'campaigns' | 'messages'

const scenes: { id: Scene; icon: typeof KanbanSquare; fr: { name: string; title: string; copy: string }; en: { name: string; title: string; copy: string } }[] = [
  { id: 'tasks', icon: KanbanSquare, fr: { name: 'Projets & tâches', title: 'Chacun sait ce qu’il doit faire.', copy: 'Passez de vos missions à la vue globale. Les affectations et réaffectations déclenchent une notification.' }, en: { name: 'Projects & tasks', title: 'Everyone knows what comes next.', copy: 'Move between your own work and the team-wide view. Assignments and reassignments trigger an alert.' } },
  { id: 'editorial', icon: CalendarDays, fr: { name: 'Calendrier éditorial', title: 'La stratégie prend forme dans un calendrier.', copy: 'Visualisez chaque publication, son canal, sa date et son étape de validation.' }, en: { name: 'Editorial calendar', title: 'Your content strategy becomes a calendar.', copy: 'See every post, channel, date and approval stage in context.' } },
  { id: 'campaigns', icon: Megaphone, fr: { name: 'Campagnes', title: 'Une campagne se pilote, elle ne se devine pas.', copy: 'Préparez vos audiences et suivez vos campagnes SMS depuis une vue dédiée.' }, en: { name: 'Campaigns', title: 'Run campaigns with a clear picture.', copy: 'Prepare audiences and follow SMS campaigns from a dedicated view.' } },
  { id: 'messages', icon: MessageSquareText, fr: { name: 'Équipe & messages', title: 'Le bon message arrive à la bonne personne.', copy: 'Discussions privées, notifications ciblées et raccourci de messagerie dans l’application.' }, en: { name: 'Team & messages', title: 'The right message reaches the right person.', copy: 'Private conversations, targeted alerts and a messaging shortcut inside the app.' } },
]

function Screen({ scene, language }: { scene: Scene; language: Language }) {
  const en = language === 'en'
  if (scene === 'tasks') return <div className="innovation-screen-content innovation-tasks">
    <div className="innovation-app-heading"><div><small>{en ? 'WORKSPACE / TASKS' : 'ESPACE / TÂCHES'}</small><h3>{en ? 'Tasks' : 'Tâches'}</h3></div><span className="innovation-new">+ {en ? 'New task' : 'Nouvelle tâche'}</span></div>
    <div className="innovation-scope"><span className="active">{en ? 'My tasks' : 'Mes tâches'} <b>03</b></span><span>{en ? 'All tasks' : 'Toutes les tâches'} <b>12</b></span></div>
    <div className="innovation-kanban">{(en ? [['TO DO','Campaign brief','Prepare the visual concept'],['IN PROGRESS','Client proposal','Review the final offer'],['DONE','Kick-off meeting','Meeting notes approved']] : [['À FAIRE','Brief de campagne','Préparer la piste créative'],['EN COURS','Proposition client','Relire l’offre finale'],['TERMINÉ','Réunion de lancement','Compte rendu validé']]).map(([status, first, second], index) => <div className="innovation-column" key={status}><header><i className={`tone-${index}`}/>{status}<b>{index === 0 ? '2' : '1'}</b></header><article><small>{index === 0 ? 'STUDIO NOVA' : index === 1 ? 'KALOUM DIGITAL' : 'PROJET ALPHA'}</small><strong>{first}</strong><span>{en ? 'Assigned to me' : 'Ma mission'} · {index === 2 ? '100%' : `${35 + index * 25}%`}</span></article>{index === 0 && <article className="innovation-card-secondary"><strong>{second}</strong><span>{en ? 'Tomorrow' : 'Demain'} · 10:00</span></article>}</div>)}</div>
  </div>
  if (scene === 'editorial') return <div className="innovation-screen-content innovation-editorial">
    <div className="innovation-app-heading"><div><small>{en ? 'CONTENT / EDITORIAL' : 'CONTENU / ÉDITORIAL'}</small><h3>{en ? 'Editorial calendar' : 'Calendrier éditorial'}</h3></div><span className="innovation-new">+ {en ? 'Post' : 'Publication'}</span></div>
    <div className="innovation-calendar-heading"><span>‹</span><strong>{en ? 'October 2026' : 'Octobre 2026'}</strong><span>›</span><small>{en ? 'Month view' : 'Vue mois'}</small></div>
    <div className="innovation-calendar">{(en ? ['MON','TUE','WED','THU','FRI','SAT','SUN'] : ['LUN','MAR','MER','JEU','VEN','SAM','DIM']).map(day => <b key={day}>{day}</b>)}{Array.from({ length: 28 }, (_, index) => <div key={index}><small>{index + 1}</small>{index === 3 && <span className="post purple">Instagram · {en ? 'Draft' : 'Brouillon'}</span>}{index === 9 && <span className="post yellow">LinkedIn · {en ? 'Review' : 'À valider'}</span>}{index === 15 && <span className="post blue">Facebook · {en ? 'Scheduled' : 'Planifié'}</span>}{index === 22 && <span className="post green">TikTok · {en ? 'Published' : 'Publié'}</span>}</div>)}</div>
  </div>
  if (scene === 'campaigns') return <div className="innovation-screen-content innovation-campaigns">
    <div className="innovation-app-heading"><div><small>{en ? 'COMMUNICATION / CAMPAIGNS' : 'COMMUNICATION / CAMPAGNES'}</small><h3>{en ? 'SMS campaigns' : 'Campagnes SMS'}</h3></div><span className="innovation-new">+ {en ? 'Campaign' : 'Campagne'}</span></div>
    <div className="innovation-campaign-stats">{(en ? [['04','Campaigns'],['02','Scheduled'],['03','Groups'],['01','To review']] : [['04','Campagnes'],['02','Planifiées'],['03','Groupes'],['01','À vérifier']]).map(([value,label])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div>
    <div className="innovation-campaign-table"><div><b>{en ? 'Campaign' : 'Campagne'}</b><b>{en ? 'Audience' : 'Audience'}</b><b>{en ? 'Status' : 'Statut'}</b></div><div><strong>{en ? 'October launch' : 'Lancement octobre'}</strong><span>{en ? 'Clients · 48 contacts' : 'Clients · 48 contacts'}</span><em className="scheduled">{en ? 'Scheduled' : 'Planifiée'}</em></div><div><strong>{en ? 'Event invitation' : 'Invitation événement'}</strong><span>{en ? 'Prospects · 32 contacts' : 'Prospects · 32 contacts'}</span><em className="draft">{en ? 'Draft' : 'Brouillon'}</em></div><div><strong>{en ? 'Follow-up' : 'Relance ciblée'}</strong><span>{en ? 'Partners · 12 contacts' : 'Partenaires · 12 contacts'}</span><em className="complete">{en ? 'Completed' : 'Terminée'}</em></div></div>
  </div>
  return <div className="innovation-screen-content innovation-messages">
    <div className="innovation-app-heading"><div><small>{en ? 'TEAM / MESSAGING' : 'ÉQUIPE / MESSAGERIE'}</small><h3>{en ? 'Team conversations' : 'Discussions d’équipe'}</h3></div><BellRing/></div>
    <div className="innovation-messaging"><aside><strong>{en ? 'Conversations' : 'Conversations'}</strong><div className="selected"><i>AM</i><span><b>Aïssatou M.</b><small>{en ? 'Private message' : 'Message privé'}</small></span><em>1</em></div><div><i>EQ</i><span><b>{en ? 'Team' : 'Équipe'}</b><small>{en ? 'Project updates' : 'Suivi des projets'}</small></span></div></aside><section><header><i>AM</i><span><strong>Aïssatou M.</strong><small>{en ? 'Private conversation' : 'Conversation privée'}</small></span></header><p className="received">{en ? 'I have reviewed the client brief. Can we validate the next step?' : 'J’ai relu le brief client. Peut-on valider la suite ?'}</p><p className="sent">{en ? 'Yes, let’s review it together today.' : 'Oui, regardons-le ensemble aujourd’hui.'}<Check/></p><div className="innovation-message-input">{en ? 'Write a message…' : 'Écrire un message…'} <ArrowRight/></div></section></div>
  </div>
}

export default function InnovationShowcase({ language, onSignUp }: { language: Language; onSignUp: () => void }) {
  const [active, setActive] = useState(0)
  const reduced = useReducedMotion()
  const en = language === 'en'
  const scene = scenes[active]
  const change = (step: number) => setActive(index => (index + step + scenes.length) % scenes.length)
  return <section className="innovation-showcase" id="nouveautes" aria-label={en ? 'Latest product updates' : 'Dernières nouveautés'}>
    <div className="innovation-intro"><span><Sparkles/> {en ? 'NEW IN SMARTSELL MANAGEMENT' : 'NOUVEAU DANS SMARTSELL MANAGEMENT'}</span><h2>{en ? <>The platform is evolving.<br/><em>See what changed.</em></> : <>La plateforme évolue.<br/><em>Voyez ce qui change.</em></>}</h2><p>{en ? 'A closer look at the latest improvements for teams, content and communication.' : 'Un aperçu concret des dernières avancées pour les équipes, les contenus et la communication.'}</p></div>
    <div className="innovation-tabs" role="tablist" aria-label={en ? 'Choose a product preview' : 'Choisir un aperçu produit'}>{scenes.map((item,index)=><button key={item.id} type="button" role="tab" aria-selected={index===active} className={index===active?'active':''} onClick={()=>setActive(index)}><item.icon/><span>{item[language].name}</span></button>)}</div>
    <div className="innovation-feature"><div className="innovation-description"><span>0{active+1} / 0{scenes.length}</span><motion.div key={`${language}-${scene.id}`} initial={reduced?false:{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.35}}><h3>{scene[language].title}</h3><p>{scene[language].copy}</p></motion.div><button type="button" onClick={onSignUp}>{en ? 'Explore it in your workspace' : 'Découvrir dans mon espace'} <ArrowRight/></button><div className="innovation-controls"><button type="button" onClick={()=>change(-1)} aria-label={en?'Previous preview':'Aperçu précédent'}><ChevronLeft/></button><button type="button" onClick={()=>change(1)} aria-label={en?'Next preview':'Aperçu suivant'}><ChevronRight/></button></div></div><div className="innovation-shot" role="tabpanel" aria-label={scene[language].name}><div className="innovation-shot-bar"><span><i/><i/><i/></span><strong>Smartsell Management</strong><small>{en ? 'ILLUSTRATIVE SCREEN' : 'APERÇU ILLUSTRATIF'}</small></div><motion.div key={`${scene.id}-${language}`} initial={reduced?false:{opacity:0,x:22}} animate={{opacity:1,x:0}} transition={{duration:.38}}><Screen scene={scene.id} language={language}/></motion.div></div></div>
    <p className="innovation-disclaimer">{en ? 'Interface previews use fictional data. External social account connections are not shown as active.' : 'Aperçus de l’interface avec données fictives. Les connexions aux comptes sociaux externes ne sont pas présentées comme actives.'}</p>
  </section>
}
