import { CSSProperties, FormEvent, useEffect, useMemo, useState } from 'react'
import { Activity, BarChart3, CheckCircle2, CircleDollarSign, Copy, Gauge, Megaphone, RefreshCw, Save, ShieldCheck, Sparkles, Target, TrendingUp, Users, WalletCards, XCircle } from 'lucide-react'
import { generateCampaignPlan, generateCommercialRadar, generateDigitalTwin, listAgencyScenarios, listCampaignAiDrafts, updateCampaignAiDraftStatus } from './services/repository'
import type { AgencyScenario, CampaignAiDraft, CommercialRadar, DigitalTwinSnapshot } from './types/models'

const money=(value:number,currency='GNF')=>new Intl.NumberFormat('fr-FR',{style:'currency',currency,maximumFractionDigits:currency==='GNF'?0:2}).format(Number(value||0))

function Loading({label}:{label:string}){return <div className="innovation-loading"><Sparkles/><strong>{label}</strong><span>L’analyse utilise uniquement les données disponibles dans SmartSell.</span></div>}
function ErrorBox({message}:{message:string}){return message?<div className="error-banner">{message}</div>:null}

export function DigitalTwinPage(){
  const[data,setData]=useState<DigitalTwinSnapshot|null>(null),[scenarios,setScenarios]=useState<AgencyScenario[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState('')
  const run=async(input?:{name?:string;client_delay_days?:number;new_contract_value?:number;expense_change_percent?:number})=>{setBusy(true);setError('');try{const result=await generateDigitalTwin(input);setData(result);if(input?.name)setScenarios(await listAgencyScenarios())}catch(e){setError(e instanceof Error?e.message:'Simulation impossible')}finally{setBusy(false)}}
  useEffect(()=>{void Promise.all([run(),listAgencyScenarios().then(setScenarios).catch(()=>setScenarios([]))])},[])
  const max=Math.max(1,...(data?.projections.flatMap(row=>[Math.abs(row.revenue),Math.abs(row.expenses)])||[1]))
  return <div className="innovation-page">
    <section className="innovation-hero twin-hero"><div><span className="eyebrow"><i/> JUMEAU NUMÉRIQUE</span><h1>Simulez demain avant de décider.</h1><p>Trésorerie, rentabilité, retards clients et capacité projet réunis dans un modèle vivant de l’agence.</p></div><div className="twin-core"><Gauge/><strong>{data?money(data.kpis.forecast_30d):'—'}</strong><span>projection nette à 30 jours</span></div></section>
    <ErrorBox message={error}/>
    <form className="panel scenario-console" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run({name:String(f.get('name')||''),client_delay_days:Number(f.get('client_delay_days')||0),new_contract_value:Number(f.get('new_contract_value')||0),expense_change_percent:Number(f.get('expense_change_percent')||0)})}}>
      <div><span className="eyebrow"><i/> LABORATOIRE DE DÉCISION</span><h2>Créer un scénario</h2><p>Modifiez les hypothèses, puis comparez immédiatement leur effet sur la trésorerie.</p></div>
      <label>Nom du scénario<input name="name" required placeholder="Ex. Retard client + nouveau contrat"/></label>
      <label>Retard d’encaissement<input name="client_delay_days" type="number" min="0" defaultValue="0"/><small>jours</small></label>
      <label>Nouveau contrat<input name="new_contract_value" type="number" min="0" defaultValue="0"/><small>GNF</small></label>
      <label>Variation des dépenses<input name="expense_change_percent" type="number" defaultValue="0"/><small>%</small></label>
      <button className="primary-btn compact" disabled={busy}><Save/>{busy?'Simulation…':'Simuler et enregistrer'}</button>
    </form>
    {busy&&!data?<Loading label="Construction du jumeau numérique…"/>:data&&<>
      <section className="twin-kpis">
        <article><WalletCards/><span>Trésorerie actuelle</span><strong>{money(data.kpis.cash)}</strong></article>
        <article><CircleDollarSign/><span>À recevoir</span><strong>{money(data.kpis.receivables)}</strong></article>
        <article><TrendingUp/><span>Projection 90 jours</span><strong>{money(data.kpis.forecast_90d)}</strong></article>
        <article><Activity/><span>Marge observée</span><strong>{data.kpis.margin_rate}%</strong></article>
      </section>
      <section className="twin-grid"><article className="panel twin-chart"><div className="section-title"><div><span className="eyebrow"><i/> PROJECTION</span><h2>Trajectoire des six prochains mois</h2></div><BarChart3/></div><div className="projection-chart">{data.projections.map(row=><div key={row.label}><div className="projection-bars"><i style={{height:`${Math.max(5,Math.abs(row.revenue)/max*100)}%`}}/><b style={{height:`${Math.max(5,Math.abs(row.expenses)/max*100)}%`}}/></div><span>{row.label}</span><small>{money(row.cash)}</small></div>)}</div><div className="chart-key"><span><i/>Encaissements</span><span><i/>Dépenses</span></div></article><aside className="panel twin-signals"><h2>Signaux de décision</h2><div className="risk-stack">{data.risks.length?data.risks.map((item,index)=><p className="risk" key={index}>! {item}</p>):<p className="safe">✓ Aucun risque critique détecté.</p>}</div>{data.recommendations.map((item,index)=><div className="recommendation" key={index}><span>{index+1}</span><p>{item}</p></div>)}</aside></section>
    </>}
    <section className="panel scenario-history"><div className="section-title"><div><span className="eyebrow"><i/> MÉMOIRE</span><h2>Scénarios enregistrés</h2></div><b>{scenarios.length}</b></div>{scenarios.length?<div className="scenario-list">{scenarios.map(item=><button key={item.id} onClick={()=>setData(item.result)}><strong>{item.name}</strong><span>Retard {item.parameters.client_delay_days||0} j · Contrat {money(item.parameters.new_contract_value||0)}</span><small>{new Date(item.created_at).toLocaleString('fr-FR')}</small></button>)}</div>:<p className="muted">Vos simulations apparaîtront ici pour comparaison.</p>}</section>
  </div>
}

export function CommercialRadarPage(){
  const[data,setData]=useState<CommercialRadar|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState<'CLIENTS'|'PROSPECTS'>('CLIENTS')
  const load=async()=>{setBusy(true);setError('');try{setData(await generateCommercialRadar())}catch(e){setError(e instanceof Error?e.message:'Radar indisponible')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[])
  return <div className="innovation-page"><section className="innovation-hero radar-hero"><div><span className="eyebrow"><i/> RADAR COMMERCIAL</span><h1>Voyez les risques et les opportunités avant tout le monde.</h1><p>Chaque client et prospect reçoit un score explicable, fondé sur les projets, paiements, interactions et relances.</p></div><button className="ghost-action" disabled={busy} onClick={()=>void load()}><RefreshCw/>{busy?'Analyse…':'Rafraîchir les scores'}</button></section><ErrorBox message={error}/>{busy&&!data?<Loading label="Calcul des signaux commerciaux…"/>:data&&<>
    <section className="radar-kpis"><article><ShieldCheck/><strong>{data.summary.healthy}</strong><span>clients sains</span></article><article><Activity/><strong>{data.summary.watch}</strong><span>à surveiller</span></article><article><XCircle/><strong>{data.summary.critical}</strong><span>critiques</span></article><article><Target/><strong>{data.summary.hot_prospects}</strong><span>prospects chauds</span></article></section>
    <div className="radar-tabs"><button className={tab==='CLIENTS'?'active':''} onClick={()=>setTab('CLIENTS')}>Santé clients</button><button className={tab==='PROSPECTS'?'active':''} onClick={()=>setTab('PROSPECTS')}>Scoring prospects</button></div>
    {tab==='CLIENTS'?<section className="radar-cards">{data.clients.map(item=><article className={`panel health-card ${item.status.toLowerCase()}`} key={item.client_id}><div className="score-ring" style={{'--score':`${item.score*3.6}deg`} as CSSProperties}><strong>{item.score}</strong></div><div><span className="status">{item.status.replaceAll('_',' ')}</span><h2>{item.client_name}</h2><p>{item.recommendation}</p><small>{money(item.revenue)} facturé · {item.overdue_invoices} facture(s) en retard · {item.active_projects} projet(s) actif(s)</small></div></article>)}</section>:<section className="prospect-radar panel">{data.prospects.map((item,index)=><article key={item.prospect_id}><b>{String(index+1).padStart(2,'0')}</b><div><strong>{item.company}</strong><small>{item.contact_name||'Contact non renseigné'} · {item.stage}</small><p>{item.recommended_action}</p><div>{item.signals.map(signal=><span key={signal}>{signal}</span>)}</div></div><em>{item.score}<small>/100</small></em></article>)}</section>}
  </>}</div>
}

export function CampaignStudioPage({onOpenCampaigns}:{onOpenCampaigns:()=>void}){
  const[drafts,setDrafts]=useState<CampaignAiDraft[]>([]),[selected,setSelected]=useState<CampaignAiDraft|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const load=()=>listCampaignAiDrafts().then(rows=>{setDrafts(rows);if(selected)setSelected(rows.find(row=>row.id===selected.id)||null)}).catch(e=>setError(e instanceof Error?e.message:'Chargement impossible'))
  useEffect(()=>{void load()},[])
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{const f=new FormData(e.currentTarget),channels=f.getAll('channels').map(String);const {draft}=await generateCampaignPlan({name:String(f.get('name')),objective:String(f.get('objective')),audience:String(f.get('audience')),offer:String(f.get('offer')||''),channels:channels.length?channels:['EMAIL'],tone:String(f.get('tone')),budget:Number(f.get('budget')||0),currency:'GNF'});setSelected(draft);setDrafts(rows=>[draft,...rows]);setNotice('Plan généré et placé en attente de validation humaine.')}catch(x){setError(x instanceof Error?x.message:'Génération impossible')}finally{setBusy(false)}}
  const approve=async(status:'APPROUVE'|'REJETE')=>{if(!selected)return;const updated=await updateCampaignAiDraftStatus(selected.id,status);setSelected(updated);setDrafts(rows=>rows.map(row=>row.id===updated.id?updated:row));setNotice(status==='APPROUVE'?'Plan approuvé. Il peut maintenant être préparé dans Campagnes.':'Plan rejeté. Aucun envoi ne sera effectué.')}
  const plan=selected?.plan,maxBudget=useMemo(()=>drafts.reduce((sum,row)=>sum+Number(row.budget||0),0),[drafts])
  return <div className="innovation-page"><section className="innovation-hero campaign-ai-hero"><div><span className="eyebrow"><i/> STUDIO CAMPAGNES IA</span><h1>De l’objectif au plan multicanal en quelques secondes.</h1><p>L’IA prépare les angles, messages, séquences et indicateurs. Vous gardez la décision finale.</p></div><div className="approval-seal"><ShieldCheck/><strong>Human in control</strong><span>Aucun envoi automatique</span></div></section><ErrorBox message={error}/>{notice&&<div className="success-banner">{notice}</div>}
    <section className="campaign-ai-grid"><form className="panel campaign-brief" onSubmit={submit}><div className="section-title"><div><span className="eyebrow"><i/> BRIEF INTELLIGENT</span><h2>Nouvelle stratégie</h2></div><Sparkles/></div><label>Nom de la campagne<input name="name" required placeholder="Ex. Offre rentrée digitale"/></label><label>Objectif<textarea name="objective" required placeholder="Obtenir 20 rendez-vous qualifiés…"/></label><label>Audience<textarea name="audience" required placeholder="PME de Conakry, décideurs marketing…"/></label><label>Offre ou promesse<textarea name="offer" placeholder="Audit offert, forfait lancement…"/></label><div className="form-grid"><label>Ton<select name="tone"><option value="PROFESSIONNEL">Professionnel</option><option value="DYNAMIQUE">Dynamique</option><option value="PREMIUM">Premium</option><option value="PEDAGOGIQUE">Pédagogique</option></select></label><label>Budget maximal<input name="budget" type="number" min="0" defaultValue="0"/></label></div><fieldset><legend>Canaux</legend><label><input type="checkbox" name="channels" value="EMAIL" defaultChecked/> E-mail</label><label><input type="checkbox" name="channels" value="SMS"/> SMS</label><label><input type="checkbox" name="channels" value="SOCIAL"/> Réseaux sociaux</label></fieldset><button className="primary-btn" disabled={busy}><Sparkles/>{busy?'Création du plan…':'Générer le plan complet'}</button></form>
      <div className="campaign-plan">{selected&&plan?<><article className="panel plan-overview"><div><span className={`status ${selected.status==='REJETE'?'danger':''}`}>{selected.status.replaceAll('_',' ')}</span><h2>{selected.name}</h2><p>{plan.summary}</p><small>{plan.audience_strategy}</small></div><div className="plan-actions">{selected.status==='A_VALIDER'&&<><button className="primary-btn compact" onClick={()=>void approve('APPROUVE')}><CheckCircle2/>Approuver</button><button className="danger-btn" onClick={()=>void approve('REJETE')}><XCircle/>Rejeter</button></>}{selected.status==='APPROUVE'&&<button className="primary-btn compact" onClick={onOpenCampaigns}><Megaphone/>Préparer la diffusion</button>}</div></article><div className="variant-grid">{plan.variants.map((variant,index)=><article className="panel" key={`${variant.channel}-${index}`}><header><span>{variant.channel}</span><b>VARIANTE {index+1}</b></header><h3>{variant.name}</h3>{variant.subject&&<small>Objet : {variant.subject}</small>}<p>{variant.message}</p><footer><strong>{variant.cta}</strong><button title="Copier" onClick={()=>void navigator.clipboard.writeText(`${variant.subject?variant.subject+'\n':''}${variant.message}\n${variant.cta}`)}><Copy/></button></footer></article>)}</div><article className="panel campaign-sequence"><h2>Séquence recommandée</h2>{plan.schedule.map((step,index)=><div key={index}><b>J+{Math.floor(step.offset_hours/24)}</b><span>{step.channel}</span><p>{step.purpose}</p></div>)}</article><section className="plan-lists"><article className="panel"><h3>Indicateurs</h3>{plan.kpis.map(item=><p key={item}>↗ {item}</p>)}</article><article className="panel"><h3>Garde-fous</h3>{plan.safeguards.map(item=><p key={item}>✓ {item}</p>)}</article></section></>:<Loading label="Votre plan stratégique apparaîtra ici…"/>}</div>
    </section>
    <section className="panel campaign-draft-history"><div className="section-title"><div><span className="eyebrow"><i/> PORTEFEUILLE</span><h2>Plans enregistrés</h2></div><span>{money(maxBudget)} budgétés</span></div><div>{drafts.map(item=><button className={selected?.id===item.id?'active':''} onClick={()=>setSelected(item)} key={item.id}><strong>{item.name}</strong><span>{item.channels.join(' + ')} · {item.status.replaceAll('_',' ')}</span><small>{new Date(item.created_at).toLocaleDateString('fr-FR')}</small></button>)}</div></section>
  </div>
}
