import { useEffect, useState, type FormEvent } from 'react'
import { Activity, Bell, Building2, Check, Download, FileArchive, FileSpreadsheet, Gauge, LockKeyhole, RefreshCw, Save, Settings2, ShieldCheck, Sparkles } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import { getAutopilotSettings, getCompanySettings, listActivityLogs, listClients, listExpenses, listInvoices, listNotifications, listProjects, listUserSessions, markAllNotificationsRead, markNotificationRead, saveAutopilotSettings, updateCompanySettings } from './services/repository'
import type { ActivityLog, AutopilotSettings, Client, CompanySettings, Expense, Invoice, Notification, Profile, Project, UserSession } from './types/models'

type Tab = 'notifications'|'audit'|'export'|'automation'|'security'|'kpi'|'company'
const tabs:Array<[Tab,string,typeof Bell]> = [['notifications','Notifications',Bell],['audit','Journal d’audit',Activity],['export','Sauvegarde & export',FileArchive],['automation','Automatisation commerciale',Sparkles],['security','Sécurité & conformité',ShieldCheck],['kpi','Indicateurs de performance',Gauge],['company','Paramètres entreprise',Building2]]
const fmt=(value?:string|null)=>value?new Date(value).toLocaleString('fr-FR'):'—'
const csv=(rows:Array<Record<string,unknown>>)=>{const keys=[...new Set(rows.flatMap(row=>Object.keys(row)))];return [keys.join(';'),...rows.map(row=>keys.map(key=>JSON.stringify(row[key]??'')).join(';'))].join('\n')}
function download(name:string,body:string,type='text/csv'){const blob=new Blob([body],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}

export function NotificationBell(){
  const [open,setOpen]=useState(false),[rows,setRows]=useState<Notification[]>([])
  const load=()=>listNotifications().then(setRows).catch(()=>undefined)
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),60_000);return()=>window.clearInterval(timer)},[])
  const unread=rows.filter(row=>!row.read_at).length
  return <div className="notification-wrap"><button className="icon-btn notification-trigger" onClick={()=>setOpen(value=>!value)} aria-label="Notifications"><Bell/>{unread>0&&<b>{unread>99?'99+':unread}</b>}</button><AnimatePresence>{open&&<motion.div className="notification-popover" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}><div className="notification-head"><div><span className="eyebrow"><i/> CENTRE DE NOTIFICATION</span><h3>Vos alertes</h3></div><button className="ghost-action" onClick={async()=>{await markAllNotificationsRead();await load()}}>Tout lire</button></div>{rows.length?rows.slice(0,8).map(row=><button key={row.id} className={`notification-item ${row.read_at?'read':''}`} onClick={async()=>{if(!row.read_at){await markNotificationRead(row.id);await load()}}}><span className="notification-dot"/><span><strong>{row.title}</strong><small>{row.body||'—'}</small><time>{fmt(row.created_at)}</time></span></button>):<p className="muted notification-empty">Aucune notification.</p>}</motion.div>}</AnimatePresence></div>
}

export function OperationsCenter({profile}:{profile:Profile}){
  const [tab,setTab]=useState<Tab>('notifications'),[notifications,setNotifications]=useState<Notification[]>([]),[logs,setLogs]=useState<ActivityLog[]>([]),[sessions,setSessions]=useState<UserSession[]>([]),[clients,setClients]=useState<Client[]>([]),[projects,setProjects]=useState<Project[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[company,setCompany]=useState<CompanySettings|null>(null),[autopilot,setAutopilot]=useState<AutopilotSettings|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const reload=async()=>{setBusy(true);setError('');try{if(tab==='notifications'){setNotifications(await listNotifications())}else if(tab==='audit'){const [a,s]=await Promise.all([listActivityLogs(),listUserSessions()]);setLogs(a);setSessions(s)}else if(tab==='export'||tab==='kpi'){const [c,p,i,e]=await Promise.all([listClients(),listProjects(),listInvoices(),listExpenses()]);setClients(c);setProjects(p);setInvoices(i);setExpenses(e)}else if(tab==='automation'){setAutopilot(await getAutopilotSettings())}else if(tab==='company'){setCompany(await getCompanySettings())}}catch(e){setError(e instanceof Error?e.message:'Chargement impossible')}finally{setBusy(false)}}
  useEffect(()=>{void reload()},[tab])
  const unread=notifications.filter(row=>!row.read_at).length
  const billed=invoices.reduce((sum,row)=>sum+Number(row.total||0),0), collected=invoices.flatMap(row=>row.payments||[]).reduce((sum,row)=>sum+Number(row.amount||0),0), spent=expenses.reduce((sum,row)=>sum+Number(row.amount||0),0)
  const exportAll=()=>download(`smartsell-export-${new Date().toISOString().slice(0,10)}.csv`,csv([...clients.map(row=>({type:'client',id:row.id,nom:row.name,email:row.email,statut:row.status})),...projects.map(row=>({type:'projet',id:row.id,nom:row.name,statut:row.status,budget:row.budget})),...invoices.map(row=>({type:'facture',id:row.id,numero:row.number,total:row.total,statut:row.status})),...expenses.map(row=>({type:'depense',id:row.id,description:row.description,amount:row.amount,statut:row.status}))]))
  const saveCompany=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!company)return;try{const f=Object.fromEntries(new FormData(e.currentTarget));const next=await updateCompanySettings(f);setCompany(next);setMessage('Paramètres entreprise enregistrés.')}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible')}}
  return <div className="operations-center"><div className="module-head"><div><span className="eyebrow"><i/> GOUVERNANCE SMARTSELL</span><h1>Centre de contrôle</h1><p>Notifications, conformité, performance et paramètres réunis dans un espace administrateur.</p></div><div className="head-actions"><button className="ghost-action" onClick={()=>void reload()}><RefreshCw/>Actualiser</button></div></div>{message&&<div className="success-banner">{message}</div>}{error&&<div className="error-banner">{error}</div>}<div className="operations-tabs">{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon/><span>{label}</span>{key==='notifications'&&unread>0&&<b>{unread}</b>}</button>)}</div>
  {tab==='notifications'&&<section className="operations-grid"><article className="panel operations-hero"><div className="ai-orb compact"><Bell/></div><div><span className="eyebrow"><i/> CENTRE DE NOTIFICATION</span><h2>{unread?`${unread} notification(s) à traiter`:'Tout est à jour'}</h2><p>Les événements importants, rappels de tâches, validations et alertes de sécurité apparaissent ici.</p></div><button className="primary-btn compact" onClick={async()=>{await markAllNotificationsRead();await reload()}}><Check/>Marquer comme lu</button></article><section className="panel notification-list">{notifications.length?notifications.map(row=><div className={`notification-item wide ${row.read_at?'read':''}`} key={row.id}><span className="notification-dot"/><div><strong>{row.title}</strong><p>{row.body||'—'}</p><small>{fmt(row.created_at)} · {row.channel}</small></div>{!row.read_at&&<button className="ghost-action" onClick={async()=>{await markNotificationRead(row.id);await reload()}}>Lu</button>}</div>):<p className="muted">Aucune notification enregistrée.</p>}</section></section>}
  {tab==='audit'&&<section className="report-grid"><article className="panel report-panel"><div className="command-panel-head"><div><span className="eyebrow"><i/> JOURNAL D’AUDIT</span><h2>Actions récentes</h2></div><b>{logs.length}</b></div>{logs.slice(0,80).map(row=><div className="audit-row" key={row.id}><span className="record-avatar">{(row.profiles?.full_name||'U').slice(0,2)}</span><div><strong>{row.profiles?.full_name||'Utilisateur'} · {row.action}</strong><small>{row.entity_type} · {Object.keys(row.metadata||{}).length} détail(s)</small></div><time>{fmt(row.created_at)}</time></div>)}</article><article className="panel report-panel"><div className="command-panel-head"><div><span className="eyebrow"><i/> SESSIONS</span><h2>Temps et présence</h2></div><b>{sessions.length}</b></div>{sessions.slice(0,50).map(row=><div className="audit-row" key={row.id}><span className="record-avatar">{(row.profiles?.full_name||'U').slice(0,2)}</span><div><strong>{row.profiles?.full_name||'Utilisateur'}</strong><small>Dernière activité {fmt(row.last_seen_at)}</small></div><b>{Math.round(row.active_seconds/60)} min</b><time>{row.pages_viewed} pages</time></div>)}</article></section>}
  {tab==='export'&&<section className="operations-grid"><article className="panel operations-hero"><div className="ai-orb compact"><FileArchive/></div><div><span className="eyebrow"><i/> SAUVEGARDE LOGIQUE</span><h2>Exporter les données métier</h2><p>Générez un export CSV lisible de clients, projets, factures et dépenses pour archivage externe.</p></div><button className="primary-btn compact" onClick={exportAll}><Download/>Télécharger l’export</button></article><article className="panel checklist"><h2>Plan de sauvegarde recommandé</h2><label><input type="checkbox" checked readOnly/> Export CSV avant chaque clôture mensuelle</label><label><input type="checkbox" checked readOnly/> Conservation chiffrée hors plateforme</label><label><input type="checkbox" checked readOnly/> Test de restauration trimestriel</label><small>Le plan gratuit Supabase ne fournit pas de téléchargement des sauvegardes automatiques : cet export applicatif est le filet de sécurité immédiat.</small></article></section>}
  {tab==='automation'&&!autopilot&&<div className="panel empty-state">Chargement des réglages d’automatisation…</div>}
  {tab==='automation'&&autopilot&&<section className="operations-grid"><article className="panel automation-card"><div className="command-panel-head"><div><span className="eyebrow"><i/> AUTOPILOT IA</span><h2>Automatisation commerciale</h2></div><Sparkles/></div><p>Préparez les relances, priorisez les prospects et surveillez les factures sans envoyer d’action risquée automatiquement.</p><label className="switch-card"><input type="checkbox" checked={autopilot.enabled} onChange={e=>setAutopilot({...autopilot,enabled:e.target.checked})}/><span>Activer le copilote commercial</span></label><label>Mode<select value={autopilot.mode} onChange={e=>setAutopilot({...autopilot,mode:e.target.value as AutopilotSettings['mode']})}><option>OBSERVATION</option><option>COPILOTE</option><option>AUTOPILOTE</option></select></label><label>Actions maximum par passage<input type="number" min="1" max="50" value={autopilot.max_actions_per_run} onChange={e=>setAutopilot({...autopilot,max_actions_per_run:Number(e.target.value)})}/></label><button className="primary-btn compact" onClick={async()=>{await saveAutopilotSettings(autopilot);setMessage('Automatisation commerciale enregistrée.')}}><Save/>Enregistrer</button></article><article className="panel checklist"><h2>Garde-fous actifs</h2><label><input type="checkbox" checked readOnly/> Validation humaine avant envoi</label><label><input type="checkbox" checked readOnly/> Journalisation de chaque recommandation</label><label><input type="checkbox" checked readOnly/> Respect des droits et plafonds utilisateur</label><p className="muted">L’IA prépare et explique ; l’équipe conserve le contrôle des décisions sensibles.</p></article></section>}
  {tab==='security'&&<section className="operations-grid"><article className="panel checklist"><div className="command-panel-head"><div><span className="eyebrow"><i/> SÉCURITÉ & CONFORMITÉ</span><h2>Contrôles recommandés</h2></div><LockKeyhole/></div><label><input type="checkbox" checked readOnly/> Accès par rôle et permissions détaillées</label><label><input type="checkbox" checked readOnly/> Journal d’audit réservé aux administrateurs</label><label><input type="checkbox" checked readOnly/> Sessions et temps de connexion suivis</label><label><input type="checkbox" checked readOnly/> Consentement marketing conservé par contact</label><label><input type="checkbox" checked readOnly/> Données sensibles jamais exportées dans les journaux</label></article><article className="panel security-score"><span className="eyebrow"><i/> SCORE DE MATURITÉ</span><strong>82<span>/100</span></strong><p>Socle opérationnel solide. Prochaine priorité : revue trimestrielle des accès et vérification de restauration.</p><div className="progress-track"><i style={{width:'82%'}}/></div></article></section>}
  {tab==='kpi'&&<section className="command-metrics"><article className="command-metric tone-purple"><span>Chiffre facturé</span><strong>{billed.toLocaleString('fr-FR')} GNF</strong><small>{invoices.length} facture(s)</small></article><article className="command-metric tone-green"><span>Encaissements</span><strong>{collected.toLocaleString('fr-FR')} GNF</strong><small>Trésorerie collectée</small></article><article className="command-metric tone-red"><span>Dépenses</span><strong>{spent.toLocaleString('fr-FR')} GNF</strong><small>Engagé sur la période</small></article><article className="command-metric tone-blue"><span>Portefeuille</span><strong>{clients.length}</strong><small>{projects.length} projet(s) suivis</small></article><article className="panel kpi-wide"><h2>Lecture rapide</h2><div className="detail-line"><strong>Taux d’encaissement</strong><b>{billed?Math.round(collected/billed*100):0}%</b></div><div className="detail-line"><strong>Valeur moyenne facture</strong><b>{invoices.length?Math.round(billed/invoices.length).toLocaleString('fr-FR'):'0'} GNF</b></div><div className="detail-line"><strong>Rentabilité brute indicative</strong><b>{(collected-spent).toLocaleString('fr-FR')} GNF</b></div></article></section>}
  {tab==='company'&&!company&&<div className="panel empty-state">Chargement des paramètres entreprise…</div>}
  {tab==='company'&&company&&<form className="panel entity-form company-settings" onSubmit={saveCompany}><div className="command-panel-head"><div><span className="eyebrow"><i/> PARAMÈTRES D’ENTREPRISE</span><h2>Identité et coordonnées</h2></div><Settings2/></div><div className="form-grid"><label>Nom de l’entreprise<input name="company_name" defaultValue={company.company_name}/></label><label>E-mail principal<input name="email" type="email" defaultValue={company.email||''}/></label><label>Téléphone<input name="phone" defaultValue={company.phone||''}/></label><label>WhatsApp<input name="whatsapp" defaultValue={company.whatsapp||''}/></label><label>Site web<input name="website" defaultValue={company.website||''}/></label><label>Identifiant fiscal<input name="tax_id" defaultValue={company.tax_id||''}/></label><label className="wide">Adresse<textarea name="address" rows={3} defaultValue={company.address||''}/></label></div><button className="primary-btn compact"><Save/>Enregistrer les paramètres</button></form>}
  </div>
}
