import {useEffect,useRef,useState} from 'react'
import {analyzeOrchestration,confirmQuoteAcceptance,executeOrchestration,loadOrchestration,type FlowJob,type FlowState} from './services/orchestration'
import './orchestration.css'
const jobLabels={A_VALIDER:'À valider',TERMINE:'Terminé',IGNORE:'Ignoré',ERREUR:'À reprendre'}
export default function OrchestrationCenter({onNavigate}:{onNavigate?:(page:'Projets'|'Tâches'|'Facturation',clientId:string)=>void}){
 const [data,setData]=useState<FlowState|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string|null>(null);const lock=useRef(false)
 const load=async()=>{setData(await loadOrchestration())}
 useEffect(()=>{let current=true;void loadOrchestration().then(s=>{if(current)setData(s)}).catch(e=>{if(current)setError(e.message)});return()=>{current=false}},[])
 const run=async(fn:()=>Promise<unknown>,message:string)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();setNotice(message);try{await load()}catch{setError('Action enregistrée. Actualisez le centre avant de réessayer.')}}catch(e){setError(e instanceof Error?e.message:'Action impossible');try{await load()}catch{/* preserve current state and user draft */}}finally{lock.current=false;setBusy(false)}}
 return <section className="flow-center"><header className="panel flow-hero"><span className="eyebrow">LES MODULES TRAVAILLENT ENSEMBLE</span><h2>Centre d’automatisations commerciales</h2><p>Prospect → client → devis → projet et tâches → facture → encaissements → objectifs.</p><p>Les événements préparent des propositions. Vous confirmez les créations ; aucun message marketing ni encaissement n’est déclenché ici.</p><div className="flow-actions"><button disabled={busy} onClick={()=>void run(async()=>load(),'Centre actualisé.')}>Actualiser</button>{data?.rights.convert&&<button disabled={busy} onClick={()=>void run(analyzeOrchestration,'Dossiers analysés ; propositions préparées sans créer de projet ni de facture.')}>Analyser les dossiers existants</button>}</div></header>
 {error&&<p role="alert" className="error-banner">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!data&&!error&&<p>Chargement des relations…</p>}
 {data&&<><div className="flow-kpis">{[['A_VALIDER','Propositions'],['ERREUR','À reprendre'],['TERMINE','Parcours exécutés']].map(([s,l])=><article className="panel" key={s}><strong>{data.jobs.filter(j=>j.status===s).length}</strong><span>{l}</span></article>)}</div>
 {data.rights.accept_quote&&<form className="panel flow-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>confirmQuoteAcceptance(String(f.get('quote')),String(f.get('note'))),'Accord client confirmé ; proposition de démarrage disponible.')}}><h3>Confirmer un accord client</h3><p>Seulement après avoir obtenu l’accord réel du client.</p><label>Devis<select name="quote" required disabled={busy}><option value="">Choisir un devis</option>{data.quotes.filter(q=>!['ACCEPTE','ACCEPTEE','FACTURE','REFUSE','REFUSEE','ANNULE','ANNULEE','EXPIRE'].includes(q.status)).map(q=><option key={q.id} value={q.id}>{q.number} · {data.clients.find(c=>c.id===q.client_id)?.name}</option>)}</select></label><label>Preuve / contexte de l’accord<textarea name="note" required minLength={5} maxLength={1000} placeholder="Ex. accord reçu par e-mail le…" disabled={busy}/></label><button disabled={busy}>Confirmer l’acceptation</button></form>}
 {!data.jobs.length&&<p className="panel">Aucune proposition. Gagnez un prospect, confirmez un devis ou analysez les dossiers existants.</p>}
 <div className="flow-jobs">{data.jobs.map(job=><article className="panel" key={job.id}><header><h3>{job.title||'Dossier supprimé'}</h3><span className={'flow-status '+job.status}>{jobLabels[job.status]}</span></header><p>{job.kind==='PROSPECT_CLIENT'?'Prospect gagné → client, sans ressaisie':'Devis accepté → projet, tâches et facture proposés'}</p>{job.error&&<p role="status">Dernière tentative : {job.error}</p>}
 {job.status==='TERMINE'?<><p>Relations enregistrées. Aucun doublon ne sera créé en actualisant.</p>{job.kind==='PROSPECT_CLIENT'&&job.result.client_id&&data.rights.view_billing&&onNavigate&&<button onClick={()=>onNavigate('Facturation',job.result.client_id!)}>Préparer un devis pour ce client</button>}{job.result.client_id&&onNavigate&&<div className="flow-actions">{data.rights.view_projects&&job.result.project_id&&<button onClick={()=>onNavigate('Projets',job.result.client_id!)}>Voir le projet</button>}{data.rights.view_tasks&&Boolean(job.result.task_ids?.length)&&<button onClick={()=>onNavigate('Tâches',job.result.client_id!)}>Voir les tâches</button>}{data.rights.view_billing&&job.result.invoice_id&&<button onClick={()=>onNavigate('Facturation',job.result.client_id!)}>Voir la facture et les paiements</button>}</div>}</>:<>{((job.kind==='PROSPECT_CLIENT'&&data.rights.convert)||(job.kind==='QUOTE_DELIVERY'&&data.rights.delivery))&&<button disabled={busy} onClick={()=>setSelected(selected===job.id?null:job.id)}>{selected===job.id?'Fermer la proposition':job.status==='ERREUR'?'Corriger et reprendre':'Examiner et valider'}</button>}{selected===job.id&&<FlowEditor job={job} data={data} busy={busy} run={run}/>}</>}
 </article>)}</div>
 <section className="panel"><h3>Historique du circuit</h3><p>Les encaissements restent enregistrés dans Facturation. Ils mettent à jour le statut de la facture et les objectifs automatiques à leur actualisation.</p>{!data.events.length&&<p>Aucune opération enregistrée par ce circuit.</p>}{data.events.map(e=><article className="flow-event" key={e.id}><strong>{e.event.startsWith('PAYMENT_')?'Paiement mis à jour':({ACCORD_CONFIRME:'Accord confirmé',EXECUTE:'Exécution réussie',ECHEC:'Échec à reprendre'} as Record<string,string>)[e.event]||e.event}</strong><time>{new Date(e.created_at).toLocaleString('fr-FR')}</time><p>{e.detail}</p></article>)}</section>
 </>}
 </section>
}
function FlowEditor({job,data,busy,run}:{job:FlowJob;data:FlowState;busy:boolean;run:(fn:()=>Promise<unknown>,message:string)=>Promise<void>}){
 const quote=data.quotes.find(q=>q.id===job.source_id),[invoice,setInvoice]=useState(false),[tasks,setTasks]=useState(false),[ends,setEnds]=useState('')
 return <form className="flow-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const payload=job.kind==='PROSPECT_CLIENT'?{client_id:String(f.get('client_id')||'')}:{name:String(f.get('name')),starts:String(f.get('starts')),ends:String(f.get('ends')),invoice,due:String(f.get('due')||''),tasks:tasks?(quote?.items||[]).map(i=>({item_id:i.id,title:String(f.get('title:'+i.id)),assignee_id:String(f.get('assignee:'+i.id)||''),due_on:String(f.get('taskdue:'+i.id))})):[]};void run(()=>executeOrchestration(job.id,payload),'Parcours exécuté : les modules sont reliés.')}}>
 {job.kind==='PROSPECT_CLIENT'?<label>Créer ou rattacher le client<select name="client_id" disabled={busy}><option value="">Créer un client avec les coordonnées du prospect</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>:<><div className="flow-grid"><label>Nom du projet<input name="name" required maxLength={200} defaultValue={'Mission '+(quote?.number||'client')} disabled={busy}/></label><label>Début<input name="starts" type="date" required disabled={busy}/></label><label>Livraison prévue<input name="ends" type="date" required value={ends} onChange={e=>setEnds(e.target.value)} disabled={busy}/></label></div><p>Le client, le budget, la devise et les prestations proviennent du devis. Un projet déjà rattaché sera récupéré.</p>
 {data.rights.tasks&&<label className="flow-checkbox"><input type="checkbox" checked={tasks} onChange={e=>setTasks(e.target.checked)} disabled={busy}/>Préparer une tâche par prestation (à ajuster ci-dessous)</label>}
 {tasks&&quote?.items.map(item=><fieldset key={item.id}><legend>{item.description}</legend><label>Titre de la tâche<input name={'title:'+item.id} maxLength={200} defaultValue={item.description.slice(0,200)} required disabled={busy}/></label><label>Responsable<select name={'assignee:'+item.id} disabled={busy}><option value="">Non attribuée</option>{data.staff.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Échéance<input name={'taskdue:'+item.id} type="date" defaultValue={ends} required disabled={busy}/></label></fieldset>)}
 {data.rights.invoice&&<label className="flow-checkbox"><input type="checkbox" checked={invoice} onChange={e=>setInvoice(e.target.checked)} disabled={busy}/>Créer ou récupérer la facture du devis</label>}{invoice&&<label>Échéance de paiement<input name="due" type="date" required disabled={busy}/></label>}
 </>}
 <label className="flow-checkbox"><input type="checkbox" required disabled={busy}/>Je valide ces créations et les relations proposées.</label><button className="primary-btn compact" disabled={busy}>{busy?'Enregistrement…':'Valider le parcours'}</button></form>
}
