// @vitest-environment jsdom
import {beforeEach,afterEach,describe,it,vi,expect} from 'vitest'
import {cleanup,render,screen,fireEvent,waitFor} from '@testing-library/react'
const api=vi.hoisted(()=>({load:vi.fn(),analyze:vi.fn(),accept:vi.fn(),execute:vi.fn()}))
vi.mock('./services/orchestration',()=>({loadOrchestration:api.load,analyzeOrchestration:api.analyze,confirmQuoteAcceptance:api.accept,executeOrchestration:api.execute}))
import OrchestrationCenter from './OrchestrationCenter'
const rights={convert:true,accept_quote:true,delivery:true,tasks:true,invoice:true}
const base={jobs:[{id:'j',kind:'QUOTE_DELIVERY',source_id:'q',status:'A_VALIDER',title:'DEV-TEST',error:null,result:{}}],quotes:[{id:'q',number:'DEV-TEST',client_id:'c',status:'ACCEPTE',project_id:null,items:[{id:'i',description:'Community management'}]}],clients:[{id:'c',name:'Client test'}],staff:[{id:'u',name:'Membre de mon équipe'}],events:[],rights}
beforeEach(()=>{vi.resetAllMocks();api.load.mockResolvedValue(base);api.execute.mockResolvedValue({ok:true,result:{}})})
afterEach(cleanup)
describe('centre des relations commerciales',()=>{
 it('prépare sans exécuter automatiquement et laisse facture et tâches optionnelles',async()=>{render(<OrchestrationCenter/>);fireEvent.click(await screen.findByText('Examiner et valider'));expect(api.execute).not.toHaveBeenCalled();expect((screen.getByLabelText(/Créer ou récupérer la facture/) as HTMLInputElement).checked).toBe(false);expect((screen.getByLabelText(/Préparer une tâche/) as HTMLInputElement).checked).toBe(false)})
 it('permet une validation explicite avec une équipe filtrée',async()=>{render(<OrchestrationCenter/>);fireEvent.click(await screen.findByText('Examiner et valider'));fireEvent.change(screen.getByLabelText('Début'),{target:{value:'2026-10-01'}});fireEvent.change(screen.getByLabelText('Livraison prévue'),{target:{value:'2026-10-31'}});fireEvent.click(screen.getByLabelText(/Préparer une tâche/));fireEvent.change(screen.getByLabelText('Responsable'),{target:{value:'u'}});fireEvent.click(screen.getByLabelText(/Je valide/));fireEvent.click(screen.getByText('Valider le parcours'));await waitFor(()=>expect(api.execute).toHaveBeenCalledWith('j',expect.objectContaining({invoice:false,tasks:[{item_id:'i',title:'Community management',assignee_id:'u',due_on:'2026-10-31'}]})))})
 it('préserve les saisies après une erreur et bloque le double clic',async()=>{api.execute.mockRejectedValue(new Error('Attribution refusée'));render(<OrchestrationCenter/>);fireEvent.click(await screen.findByText('Examiner et valider'));fireEvent.change(screen.getByLabelText('Nom du projet'),{target:{value:'Mission personnalisée'}});fireEvent.change(screen.getByLabelText('Début'),{target:{value:'2026-10-01'}});fireEvent.change(screen.getByLabelText('Livraison prévue'),{target:{value:'2026-10-31'}});fireEvent.click(screen.getByLabelText(/Je valide/));fireEvent.click(screen.getByText('Valider le parcours'));await screen.findByText('Attribution refusée');expect((screen.getByLabelText('Nom du projet') as HTMLInputElement).value).toBe('Mission personnalisée')})
 it('ne montre pas les commandes quand les droits sont retirés',async()=>{api.load.mockResolvedValue({...base,rights:{convert:false,accept_quote:false,delivery:false,tasks:false,invoice:false}});render(<OrchestrationCenter/>);await screen.findByText('DEV-TEST');expect(screen.queryByText('Examiner et valider')).toBeNull();expect(screen.queryByText('Confirmer l’acceptation')).toBeNull();expect(screen.queryByText('Analyser les dossiers existants')).toBeNull()})
 it('ne transforme pas un échec de chargement en état vide réussi',async()=>{api.load.mockRejectedValue(new Error('Réseau indisponible'));render(<OrchestrationCenter/>);await screen.findByRole('alert');expect(screen.queryByText(/Aucune proposition/)).toBeNull()})
})
