import {useEffect,useState} from 'react'
import {performanceGoals,askAiAssistant} from './services/repository'
import {distributeGoal,goalTotals,type GoalState,type PerformanceGoal,type GoalStep} from './lib/performanceGoals'
import './performance-goals.css'
const statusLabels={DRAFT:'Brouillon',ACTIVE:'En cours',CLOSED:'Clôturé'}
export function PerformanceGoals(){
 const [state,setState]=useState<GoalState|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[creating,setCreating]=useState(false);
 const run=async(body:Record<string,unknown>)=>{setBusy(true);setError('');try{setState(await performanceGoals(body));if(body.mode!=='list')setNotice('Enregistré.');return true}catch(e){setError(e instanceof Error?e.message:'Action impossible');return false}finally{setBusy(false)}};
 useEffect(()=>{void run({mode:'list'})},[]);
 return <section className="operations-center performance-goals"><header className="module-head"><div><span className="eyebrow">PILOTAGE DES ÉQUIPES</span><h1>Objectifs & performance</h1><p>Fixer une cible, valider sa répartition et suivre les résultats semaine après semaine.</p></div><button disabled={busy} onClick={()=>void run({mode:'list'})}>Actualiser</button></header>
 {error&&<p role="alert" className="error-banner">{error}</p>}{notice&&<p role="status">{notice}</p>}{!state&&<p>{busy?'Chargement…':'Service indisponible. Actualisez pour réessayer.'}</p>}
 {state&&<><div className="goal-kpis"><div><strong>{state.goals.filter(g=>g.status==='ACTIVE').length}</strong> Objectifs en cours</div><div><strong>{state.goals.filter(g=>g.status==='DRAFT').length}</strong> À valider</div><div><strong>{state.goals.filter(g=>g.status==='CLOSED').length}</strong> Bilans clôturés</div></div>
 {state.can_manage&&<button className="primary-btn" onClick={()=>setCreating(!creating)}>Nouvel objectif mensuel</button>}
 {!state.can_manage&&<p>Vous voyez les objectifs qui vous sont attribués. Vous pouvez mettre à jour vos propres étapes.</p>}
 {creating&&<form className="panel entity-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),people=f.getAll('people').map(String),target=Number(f.get('target')),period=String(f.get('period')),title=String(f.get('title'));const plan=distributeGoal(target,period,people,String(f.get('activity')));if(!plan.length){setError('Sélectionnez des responsables et une cible suffisante pour quatre étapes par personne.');return}if(await run({mode:'create',title,metric:String(f.get('metric')),target,period:period+'-01',plan}))setCreating(false)}}>
 <h2>Définir la cible</h2><div className="form-grid"><label>Objectif<input name="title" required maxLength={200}/></label><label>Indicateur<select name="metric"><option>GNF de chiffre d’affaires</option><option>clients convertis</option><option>services vendus</option><option>tâches terminées</option><option>campagnes publiées</option></select></label><label>Cible mensuelle<input name="target" type="number" min="0.01" step="0.01" required/></label><label>Mois<input name="period" type="month" defaultValue={new Date().toISOString().slice(0,7)} required/></label></div>
 <label>Activité opérationnelle à répartir<input name="activity" required maxLength={500} placeholder="Ex. Prospecter, qualifier puis relancer les prospects"/></label>
 <fieldset><legend>Responsables (plusieurs possibles)</legend><div className="goal-people">{state.team.map(p=><label key={p.id}><input type="checkbox" name="people" value={p.id}/>{p.name}</label>)}</div></fieldset><p>La proposition répartit la cible à parts égales sur quatre périodes. Vous pourrez modifier les équipes, les cibles et les activités avant validation.</p><button className="primary-btn" disabled={busy}>Créer le brouillon de répartition</button></form>}
 {!state.goals.length&&<div className="panel"><h2>Aucun objectif pour le moment</h2><p>{state.can_manage?'Créez votre première cible mensuelle pour organiser votre équipe.':'Votre manager peut vous attribuer un objectif.'}</p></div>}
 {state.goals.map(goal=><GoalCard key={goal.id+'-'+goal.revision} goal={goal} state={state} busy={busy} run={run}/>)}</>}
 </section>
}
function GoalCard({goal,state,busy,run}:{goal:PerformanceGoal;state:GoalState;busy:boolean;run:(body:Record<string,unknown>)=>Promise<boolean>}){
 const [plan,setPlan]=useState(goal.plan),[review,setReview]=useState(goal.review),[advice,setAdvice]=useState(''),[aiBusy,setAiBusy]=useState(false);
 const totals=goalTotals(plan),percent=totals.target?Math.round(totals.actual/totals.target*100):0;
 const patch=(id:string,value:Partial<GoalStep>)=>setPlan(rows=>rows.map(s=>s.id===id?{...s,...value}:s));
 const action=(body:Record<string,unknown>)=>run({id:goal.id,revision:goal.revision,...body});
 return <article className="panel goal-card"><header><div><span className={'goal-status '+goal.status}>{statusLabels[goal.status]}</span><h2>{goal.title}</h2><p>{goal.period.slice(0,7)} · {goal.metric}</p></div><strong>{totals.actual.toLocaleString('fr-FR')} / {totals.target.toLocaleString('fr-FR')}</strong></header>
 <progress max={100} value={Math.min(100,percent)} aria-label="Progression de l’objectif"/><p>{percent}% atteint · Écart restant : {Math.max(0,totals.target-totals.actual).toLocaleString('fr-FR')} {goal.metric}</p>
 {state.can_manage&&goal.status==='DRAFT'&&<><p>Cible globale : {goal.target.toLocaleString('fr-FR')} · Répartition : {totals.target.toLocaleString('fr-FR')}. Ajustez avant validation.</p><button disabled={busy||aiBusy} onClick={async()=>{setAiBusy(true);try{setAdvice(await askAiAssistant(`Propose un plan opérationnel concis sur quatre semaines pour cet objectif : ${goal.title}, cible ${goal.target} ${goal.metric}, mois ${goal.period}. ${new Set(plan.map(s=>s.profile_id)).size} responsables. Indique tes hypothèses, ne présente pas de taux de conversion inventés comme des faits. Aucune action ne sera exécutée automatiquement.`, 'Conseil pour objectif mensuel'))}catch(e){setAdvice(e instanceof Error?e.message:'IA indisponible')}finally{setAiBusy(false)}}}>{aiBusy?'Conseil en cours…':'Demander des suggestions IA'}</button>{advice&&<p className="goal-advice">{advice}</p>}</>}
 <div className="goal-step-list">{plan.map(step=><section className="goal-step" key={step.id}><h3>Semaine {step.week} · {state.team.find(p=>p.id===step.profile_id)?.name||'Responsable'}</h3>
 {goal.status==='DRAFT'&&state.can_manage?<div className="form-grid"><label>Responsable<select value={step.profile_id} onChange={e=>patch(step.id,{profile_id:e.target.value})}>{state.team.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Équipe / pôle<input value={step.team} maxLength={100} onChange={e=>patch(step.id,{team:e.target.value})}/></label><label>Activité<input value={step.activity} maxLength={500} onChange={e=>patch(step.id,{activity:e.target.value})}/></label><label>Cible<input type="number" min="0.01" step="0.01" value={step.target} onChange={e=>patch(step.id,{target:Number(e.target.value)})}/></label><label>Échéance<input type="date" value={step.due_on} onChange={e=>patch(step.id,{due_on:e.target.value})}/></label></div>:<><p>{step.team} · {step.activity}</p><p>Échéance : {step.due_on} · Cible : {step.target} · Réalisé : {step.actual||0}</p>{goal.status==='ACTIVE'&&step.actual<step.target&&step.due_on<new Date().toISOString().slice(0,10)&&<p className="goal-late">Échéance dépassée</p>}
 {goal.status==='ACTIVE'&&(state.can_manage||state.actor_id===step.profile_id)?<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({mode:'progress',step_id:step.id,actual:Number(f.get('actual')),note:String(f.get('note'))})}}><label>Réalisé cumulé pour cette étape<input name="actual" type="number" min="0" step="0.01" defaultValue={step.actual||0} required/></label><label>Commentaire / résultat obtenu<textarea name="note" maxLength={2000} defaultValue={step.note}/></label><button disabled={busy}>Enregistrer la progression</button></form>:<p>{step.note}</p>}</>}
 </section>)}</div>
 {state.can_manage&&goal.status==='DRAFT'&&<div className="goal-actions"><button disabled={busy} onClick={()=>void action({mode:'plan',plan})}>Enregistrer le brouillon</button><button className="primary-btn" disabled={busy||Math.abs(totals.target-goal.target)>0.01} onClick={()=>{if(confirm('Valider cette répartition ? Les responsables pourront alors renseigner leurs résultats.'))void action({mode:'validate',plan})}}>Valider et attribuer</button></div>}
 {state.can_manage&&goal.status==='ACTIVE'&&<form onSubmit={e=>{e.preventDefault();if(confirm('Clôturer cet objectif et figer son bilan ?'))void action({mode:'close',review})}}><label>Bilan du manager<textarea required maxLength={4000} value={review} onChange={e=>setReview(e.target.value)} placeholder="Résultats, difficultés, enseignements et prochaines actions"/></label><button disabled={busy}>Clôturer et enregistrer le bilan</button></form>}
 {goal.status==='CLOSED'&&<section><h3>Bilan</h3><p className="goal-advice">{goal.review}</p><p>{percent>=100?'Objectif atteint':'Objectif partiellement atteint'} · {percent}%</p></section>}
 </article>
}
