import { useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import type { Task } from './types/models'
import { statusTone } from './lib/statusTone'
import './planning-calendar.css'

const weekdays=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim']
const dayKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
const taskDate=(task:Task)=>{const date=task.due_at?new Date(task.due_at):null;return date&&!Number.isNaN(date.getTime())?date:null}

export default function PlanningCalendar({tasks,onSelect}:{tasks:Task[];onSelect:(task:Task)=>void}){
  const [anchor,setAnchor]=useState(()=>new Date())
  const [view,setView]=useState<'WEEK'|'MONTH'|'YEAR'>('WEEK')
  const [selectedDay,setSelectedDay]=useState<string|null>(null)
  const start=useMemo(()=>{const date=new Date(anchor.getFullYear(),anchor.getMonth(),view==='MONTH'?1:anchor.getDate());date.setDate(date.getDate()-(date.getDay()+6)%7);return date},[anchor,view])
  const days=useMemo(()=>Array.from({length:view==='MONTH'?42:7},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i)),[start,view])
  const byDay=useMemo(()=>{const map=new Map<string,Task[]>();for(const task of tasks){const date=taskDate(task);if(!date)continue;const key=dayKey(date);map.set(key,[...(map.get(key)||[]),task])}return map},[tasks])
  const move=(direction:number)=>{setSelectedDay(null);setAnchor(current=>view==='YEAR'?new Date(current.getFullYear()+direction,0,1):view==='MONTH'?new Date(current.getFullYear(),current.getMonth()+direction,1):new Date(current.getFullYear(),current.getMonth(),current.getDate()+direction*7))}
  const today=dayKey(new Date())
  const period=view==='YEAR'?String(anchor.getFullYear()):view==='MONTH'?anchor.toLocaleDateString('fr-FR',{month:'long',year:'numeric'}):`${days[0].toLocaleDateString('fr-FR',{day:'numeric',month:'short'})} – ${days[6].toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'})}`
  const selectedTasks=selectedDay?byDay.get(selectedDay)||[]:[]
  return <section className="panel planning-calendar" aria-label="Vue globale du planning"><div className="planning-calendar-head"><div><span className="eyebrow"><i/> VUE GLOBALE</span><h2>{period}</h2><p>Tâches et échéances de votre espace</p></div><div className="planning-calendar-actions"><button type="button" onClick={()=>{setAnchor(new Date());setSelectedDay(today)}}>Aujourd’hui</button><button type="button" aria-label="Période précédente" onClick={()=>move(-1)}><ChevronLeft size={18}/></button><button type="button" aria-label="Période suivante" onClick={()=>move(1)}><ChevronRight size={18}/></button><div className="segmented">{([['WEEK','Semaine'],['MONTH','Mois'],['YEAR','Année']] as const).map(([key,label])=><button type="button" key={key} className={view===key?'active':''} onClick={()=>{setView(key);setSelectedDay(null)}}>{label}</button>)}</div></div></div>
  {view==='YEAR'?<div className="planning-year-scroll"><div className="planning-year-grid"><div className="planning-year-label">Échéances</div>{Array.from({length:12},(_,i)=><div className="planning-year-month" key={i}>{new Date(anchor.getFullYear(),i,1).toLocaleDateString('fr-FR',{month:'short'})}</div>)}{tasks.filter(task=>taskDate(task)?.getFullYear()===anchor.getFullYear()).sort((a,b)=>(a.due_at||'').localeCompare(b.due_at||'')).map(task=>{const date=taskDate(task)!;return <button type="button" key={task.id} className={`planning-year-task ${statusTone(task.status)}`} style={{gridColumn:`${date.getMonth()+2} / span 1`}} onClick={()=>onSelect(task)} title={`${task.title} · ${date.toLocaleDateString('fr-FR')}`}><span>{task.title}</span></button>})}</div></div>:<><div className="planning-calendar-weekdays">{weekdays.map(day=><strong key={day}>{day}</strong>)}</div><div className={`planning-calendar-days ${view==='WEEK'?'week':''}`}>{days.map(date=>{const key=dayKey(date),entries=byDay.get(key)||[];return <div className={`planning-calendar-day ${key===today?'today':''} ${selectedDay===key?'selected':''} ${view==='MONTH'&&date.getMonth()!==anchor.getMonth()?'outside':''}`} key={key}><button type="button" className="planning-calendar-date" onClick={()=>setSelectedDay(key)}><time dateTime={key}>{date.getDate()}</time>{entries.length>0&&<span>{entries.length}</span>}</button><div className="planning-calendar-entries">{entries.slice(0,4).map(task=><button type="button" key={task.id} className={`planning-calendar-entry ${statusTone(task.status)}`} onClick={()=>onSelect(task)}><strong>{task.title}</strong><small>{taskDate(task)?.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})} · {task.projects?.name||'Sans projet'}</small></button>)}{entries.length>4&&<button type="button" className="planning-calendar-more" onClick={()=>setSelectedDay(key)}>+ {entries.length-4} autres</button>}</div></div>})}</div>{selectedDay&&<div className="planning-selected-day"><div><strong>{new Date(`${selectedDay}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})}</strong><button type="button" onClick={()=>setSelectedDay(null)}>Fermer</button></div>{selectedTasks.length?selectedTasks.map(task=><button type="button" key={task.id} onClick={()=>onSelect(task)}>{task.title}<span>{task.projects?.name||'Sans projet'}</span></button>):<p>Aucune tâche prévue ce jour.</p>}</div>}</>}
  <p className="planning-calendar-note">Cliquez sur une tâche pour afficher sa fiche. Les tâches assignées restent synchronisées avec Google Agenda lorsque le collaborateur a connecté son compte.</p></section>
}
