import { useState } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { ArrowLeft, ArrowRight, CheckCircle2, Gift, Link2, ShieldCheck } from 'lucide-react'
import SiteFooter from './SiteFooter'
import './referral.css'

export default function ReferralLandingPage({onBack,onSignUp,onLogin}:{onBack:()=>void;onSignUp:()=>void;onLogin:()=>void}){
  const [plan,setPlan]=useState<'Essentiel'|'Croissance'|'Entreprise'>('Essentiel')
  const amounts={Essentiel:300000,Croissance:700000,Entreprise:1000000}
  const reduced=Boolean(useReducedMotion())
  const format=(amount:number)=>new Intl.NumberFormat('fr-FR').format(amount)+' GNF'
  return <><main className="referral-page">
    <header className="referral-header"><button onClick={onBack}><ArrowLeft/> Retour au site</button><strong>SMARTSELL MANAGEMENT <span>· PARRAINAGE</span></strong><button onClick={onLogin}>Se connecter</button></header>
    <motion.section className="referral-hero" initial={reduced?false:{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.6}}><span><Gift/> INVITEZ UNE ENTREPRISE, GRANDISSEZ ENSEMBLE</span><h1>Votre réseau mérite<br/><em>de vrais avantages.</em></h1><p>Faites découvrir Smartsell Management à une entreprise. Elle profite de 10 % sur son premier paiement mensuel ; vous recevez 10 % en crédit sur votre prochaine mensualité, après confirmation de son premier paiement.</p><div className="referral-actions"><button onClick={onSignUp}>Créer mon espace gratuit <ArrowRight/></button><button onClick={onLogin}>Obtenir mon lien de parrainage <Link2/></button></div></motion.section>
    <section className="referral-steps" aria-label="Comment fonctionne le parrainage">{[['01','Partagez votre lien','Depuis votre espace Smartsell Management, copiez votre lien personnel et transmettez-le à l’entreprise que vous recommandez.'],['02','Votre filleul s’inscrit','Il crée son propre espace, indépendant du vôtre, et peut tester la solution pendant 72 heures.'],['03','Le paiement valide les avantages','À son premier paiement mensuel confirmé, sa réduction de 10 % s’applique et votre crédit de 10 % devient disponible pour votre prochaine mensualité.']].map(([number,title,copy],index)=><motion.article key={number} initial={reduced?false:{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.08}}><b>{number}</b><h2>{title}</h2><p>{copy}</p></motion.article>)}</section>
    <section className="referral-calculator"><div><span>SIMULER LES AVANTAGES</span><h2>Voyez ce que 10 % représentent.</h2><p>Choisissez une formule mensuelle pour visualiser l’avantage. Il ne s’agit pas d’un crédit acquis avant paiement confirmé.</p></div><div><div className="referral-plan-options" role="group" aria-label="Choisir une formule mensuelle">{(Object.keys(amounts) as (keyof typeof amounts)[]).map(name=><button key={name} className={plan===name?'active':''} onClick={()=>setPlan(name)} aria-pressed={plan===name}>{name}</button>)}</div><motion.div className="referral-result" key={plan} initial={reduced?false:{opacity:0,y:9}} animate={{opacity:1,y:0}}><span><small>Réduction du filleul</small><strong>{format(amounts[plan]/10)}</strong></span><span><small>Crédit du parrain</small><strong>{format(amounts[plan]/10)}</strong></span></motion.div></div></section>
    <section className="referral-terms"><ShieldCheck/><div><h2>Des règles simples et transparentes</h2><p><CheckCircle2/> Aucun avantage n’est déclenché par une simple inscription ou une demande de paiement.</p><p><CheckCircle2/> L’offre concerne les mensualités uniquement ; elle ne se cumule pas avec la remise annuelle.</p><p><CheckCircle2/> Un filleul ne peut utiliser qu’une seule recommandation et chaque premier paiement ne génère qu’un crédit parrain.</p><p>Le paiement mobile est en cours de raccordement : vous pouvez déjà partager votre lien et suivre les inscriptions, mais les crédits ne seront acquis qu’après confirmation effective d’un paiement.</p></div></section>
  </main><SiteFooter onHome={onBack} onSignUp={onSignUp} onLogin={onLogin}/></>
}
