import { useEffect, useState } from 'react'
import './sms-settings.css'
import { Settings2, Save, Send, RefreshCw } from 'lucide-react'
import { tenantSmsSettings, type TenantSmsState } from './services/repository'
const labels:Record<string,string>={REQUESTED:'Accompagnement demandé',CONFIGURED:'Configuration enregistrée',ACTIVE:'SMS activés',PAUSED:'SMS en pause'}
export function SmsSettings(){
 const [state,setState]=useState<TenantSmsState|null>(null),[tenant,setTenant]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=async(id='')=>{setBusy(true);setError('');setState(null);try{const result=await tenantSmsSettings({mode:'get',tenant_owner_id:id||undefined});setState(result);setTenant(result.tenant_owner_id)}catch(e){setError(e instanceof Error?e.message:'Chargement impossible')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const run=async(body:Record<string,unknown>)=>{setBusy(true);setError('');setNotice('');try{const result=await tenantSmsSettings({...body,tenant_owner_id:tenant});if(body.mode==='test')setNotice(result.message||'Test transmis');else{setState(result);setNotice(body.mode==='request'?'Votre demande est enregistrée.':'Configuration enregistrée.')}}catch(e){setError(e instanceof Error?e.message:'Action impossible')}finally{setBusy(false)}}
 return <div className="operations-center sms-settings"><div className="module-head"><div><span className="eyebrow"><i/> CONFIGURATION ACCOMPAGNÉE</span><h1>Paramètres SMS</h1><p>Votre organisation Nimba, votre expéditeur et vos crédits SMS.</p></div><button className="ghost-action" disabled={busy} onClick={()=>void load(tenant)}><RefreshCw/>Actualiser</button></div>
 {error&&<div className="error-banner" role="alert">{error}</div>}{notice&&<div className="success-banner" role="status">{notice}</div>}{busy&&!state&&<p role="status">Chargement…</p>}
 {state&&<><section className="panel entity-form company-settings"><div className="command-panel-head"><h2>{state.settings?labels[state.settings.status]:'SMS non configurés'}</h2><Settings2/></div>
 {state.can_manage&&<label>Entreprise à accompagner<select disabled={busy} value={tenant} onChange={e=>void load(e.target.value)}>{state.tenants.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
 <div className="detail-line"><span>Organisation Nimba</span><strong>{state.settings?.organization_name||'À configurer'}</strong></div><div className="detail-line"><span>Nom d’expéditeur</span><strong>{state.settings?.sender_name||'À configurer'}</strong></div>
 <p>Les notifications internes restent disponibles pendant la configuration SMS.</p>
 {!state.can_manage&&<><p>Smartsell vous accompagne pour créer votre organisation Nimba, faire valider votre expéditeur et connecter vos envois.</p><button className="primary-btn compact" disabled={busy||!!state.settings} onClick={()=>void run({mode:'request'})}>{state.settings?'Demande prise en compte':'Demander mon activation SMS'}</button></>}
 </section>
 {state.can_manage&&<form key={tenant+'-'+state.settings?.updated_at} className="panel entity-form company-settings" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const fields=Object.fromEntries(new FormData(form));await run({mode:'save',...fields});form.querySelectorAll<HTMLInputElement>('input[type=password]').forEach(input=>input.value='')}}><h2>Connexion de l’entreprise</h2><p>Renseignez les clés de son organisation Nimba et son expéditeur approuvé.</p><a href="https://www.nimbasms.com/app/api-keys" target="_blank" rel="noreferrer">Ouvrir Nimba SMS</a><div className="form-grid"><label>Organisation Nimba<input required maxLength={150} name="organization_name" defaultValue={state.settings?.organization_name||''}/></label><label>Nom d’expéditeur approuvé<input required maxLength={50} name="sender_name" defaultValue={state.settings?.sender_name||''}/></label><label>SID<input type="password" name="service_id" autoComplete="new-password" placeholder={state.settings?.credentials_saved?'Enregistré — vide pour conserver':'SID de cette organisation'}/></label><label>Secret Token<input type="password" name="secret_token" autoComplete="new-password" placeholder={state.settings?.credentials_saved?'Enregistré — vide pour conserver':'Secret Token de cette organisation'}/></label><label>État<select name="status" defaultValue={state.settings?.status==='REQUESTED'?'CONFIGURED':state.settings?.status||'CONFIGURED'}><option value="CONFIGURED">En préparation</option><option value="ACTIVE">Activer les SMS</option><option value="PAUSED">Suspendre les SMS</option></select></label></div><p>Les clés sont conservées dans un coffre côté serveur et ne sont jamais réaffichées.</p><button className="primary-btn compact" disabled={busy}><Save/>Enregistrer</button></form>}
 {state.can_manage&&state.settings?.status==='ACTIVE'&&<form className="panel entity-form company-settings" onSubmit={e=>{e.preventDefault();void run({mode:'test',phone:String(new FormData(e.currentTarget).get('phone')||'')})}}><h2>Tester la connexion</h2><p>Ce test consomme les crédits Nimba de l’entreprise sélectionnée.</p><label>Numéro de réception<input name="phone" type="tel" required placeholder="+224…"/></label><button className="primary-btn compact" disabled={busy}><Send/>Envoyer un SMS de test</button></form>}</>}
 </div>
}
