import {useEffect,useRef,useState,type FormEvent} from 'react'
import {loadWorkspaceSettings,saveWorkspaceSettings,type WorkspaceSettings as Settings} from './services/workspaceFinance'
import './workspace-finance.css'
const fields=[['company_name','Nom de l’entreprise'],['email','E-mail'],['phone','Téléphone'],['whatsapp','WhatsApp'],['address','Adresse'],['website','Site web HTTPS'],['tax_id','Identifiant fiscal'],['logo_light','Logo pour fond sombre (URL HTTPS)'],['logo_dark','Logo pour fond clair (URL HTTPS)'],['invoice_prefix','Préfixe souhaité des factures'],['quote_prefix','Préfixe souhaité des devis'],['payment_terms','Conditions de paiement']] as const
export default function WorkspaceSettings(){
 const [state,setState]=useState<Settings|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false)
 const load=()=>loadWorkspaceSettings().then(setState).catch(e=>setError(e.message));useEffect(()=>{void load()},[])
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(lock.current||!state?.can_edit)return;lock.current=true;setBusy(true);setError('');setNotice('');const body=Object.fromEntries(new FormData(e.currentTarget));try{const company=await saveWorkspaceSettings(body,Number(state.company?.settings_revision||0));setState({...state,company});window.dispatchEvent(new Event('smartsell-company-updated'));setNotice('Réglages enregistrés. L’identité de votre espace est actualisée.')}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible')}finally{lock.current=false;setBusy(false)}}
 return <section className="workspace-finance"><header><h1>Paramètres entreprise</h1><p>Identité et préférences propres à votre espace, sans modifier celles des autres entreprises.</p></header>{error&&<p role="alert" className="error-banner">{error}</p>}{notice&&<p role="status" className="success-banner">{notice}</p>}{!state?<button onClick={()=>void load()}>Charger les réglages</button>:<form key={String(state.company?.settings_revision||0)} className="panel entity-form" onSubmit={submit}><fieldset disabled={busy||!state.can_edit}><legend>Identité, documents et préférences</legend><div className="wf-form-grid">{fields.map(([key,label])=><label key={key}>{label}<input name={key} type={key==='email'?'email':'text'} required={key==='company_name'} maxLength={['payment_terms','address'].includes(key)?2000:key.startsWith('logo')?2048:160} defaultValue={String(state.company?.[key]||'')}/></label>)}<label>Devise par défaut<select name="currency" defaultValue={String(state.company?.currency||'GNF')}><option>GNF</option><option>EUR</option><option>USD</option></select></label><label>Langue préférée<select name="locale" defaultValue={String(state.company?.locale||'fr')}><option value="fr">Français</option><option value="en">English</option></select></label><label>Fuseau horaire<select name="timezone" defaultValue={String(state.company?.timezone||'Africa/Conakry')}>{[...new Set([String(state.company?.timezone||'Africa/Conakry'),'Africa/Conakry','Africa/Abidjan','Africa/Dakar','Africa/Casablanca','Europe/Paris','UTC'])].map(v=><option key={v}>{v}</option>)}</select></label>{[['primary_color','Couleur principale','#6A2B85'],['secondary_color','Couleur de fond','#0A0A0D'],['accent_color','Couleur d’accent','#FAEE35']].map(([key,label,value])=><label key={key}>{label}<input type="color" name={key} defaultValue={String(state.company?.[key]||value)}/></label>)}</div></fieldset><p>Le téléphone et l’e-mail renseignés sont des coordonnées : ils ne configurent pas automatiquement un fournisseur SMS ou e-mail. Les préfixes et préférences sont conservés, sans renuméroter vos documents existants.</p>{state.can_edit&&<button className="primary-btn compact" disabled={busy}>{busy?'Enregistrement…':'Enregistrer les réglages'}</button>}</form>}</section>
}
